### ISSUE TITLE
Release Plan

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#100]
**Release candidate**
- [x] Remove any unneeded files to reduce game file size
- [x] Update loadscreen art
- [x] Run full 4 player runs on all gamemode types
  - [x] Express
  - [x] Rush
  - [x] Chaos

---

**Workshop release**
- [x] Fresh workshop upload so the update log is neater. Verify that all files are compiled!
- [x] Republish GDS schema
- [x] Workshop screenshots
- [x] Finish workshop text

---

**External content**
- [x] Finish initial web leaderboard
- [x] Hype thread

---

I'll keep this updated until release.

**Comment by ynohtna92** [comment]
Initial web leaderboard has been completed on hatinacat.com/leaderboard

**Comment by MNoya** [comment]
Loading screen updated.

[Workshop image link](https://github.com/Karawasa/Element-TD/blob/master/content/dota_addons/element_td/panorama/images/custom_game/loading_screen/workshop.png)

**Comment by MNoya** [comment]
Ok guys map is up to date with what I believe should be the last code version for release, please test every mode in multiplayer to avoid any undetected problem.

**Comment by Karawasa** [comment]
I updated the workshop submission. Please, no more change notes until release (there is a bug I'm about to report though!).

**Comment by Karawasa** [comment]
Not sure why my upload is larger in size than ETD test. At any rate, I would be comfortable with one changelog (since I think every upload automatically generates one) note from you for the very final upload (after I submitted, just to be sure it's all kosher) saying like "Ready for release" or something.

**Comment by Karawasa** [comment]
How does the workshop text look?

**Comment by MNoya** [comment]
Looking good.

I just uploaded to ETD Test the latest version including #133 and #134. Everyone give it a try

**Comment by MNoya** [comment]
Need decent screenshots on Lava/Winter/Desert

**Comment by MNoya** [comment]
Done!
