### ISSUE TITLE
Not getting lumber on some waves in Rush mode

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#103]
I finished a Rush mode with 10 total lumber given to me

**Comment by WindStrike72** [comment]
Kay, I think I know what happened, cause I had this happen to me. Wave 34, I kill most of it, but not all of it. Wave 35, I end up killing first, and then I killed Wave 34, and it didn't give me the lumber.

However, that's not even supposed to happen that way, cause in Rush mode, as soon as 'every 5th wave finishes spawning', that's when you're supposed to get this lumber, cause that's when the cooldown timer for the next wave begins.

Likewise in Express, as soon as 'every 3rd wave finishes spawning', get a lumber. Not when you kill the wave.
