### ISSUE TITLE
Rush Mode, Bonus Bounty or Hyper Interest

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#104]
So hyper interest is hilarious, but it's only good if you have enough money on the side to invest. Newbs won't be able to test the difference between 5 and 15 second interest, while pros will abuse the crap out of 5 second interest. Not to mention random mode, it becomes even more abusable..... and screw-overable. I just had a random game where I had waaaay more gold than intended for the first half of the game, and then I end up with a sucky element combination, so I'm forced to use all my gold to survive, and interest completely stops, so I immediately die.

Anyhow, thinkin' it should switch back to 15 second interest and then 20% bounty bonus. Thoughts?

**Comment by Karawasa** [comment]
Sounds good to me. But @MNoya make sure the bounty percentage at the bottom of voting reflects the 20% bonus bounty when you select Rush.
