### ISSUE TITLE
Score Balance

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#107]
First off, clean wave combo bonus gets stupidly stupid. Starts at what, 25%? So pull clean wave each wave and eventually, speed bonus or heck any other bonus won't matter by comparison, cause it gets to nearly 300% at the end. Clean wave combo bonus should probably be the same as speed combo bonus, +1% per consecutive wave.

Secondly, in Very Hard, my score on my best build comes to about 300k. In Normal..... it came out to be almost 300k, despite a difficulty modifier of x3 for Very Hard. Reason being in Normal, I cleared frigin' 12 icefrog waves out, giving a super substantial bonus on that total score percentage modifier. Honestly, that shouldn't be there, it's screwing over the score balance between difficulties. Highest difficulty should always end up on top in score, provided the skill to be able to beat the game. Things would be better off just having the frogs' score go up per wave instead of a multiplier on the total score.

**Comment by WindStrike72** [comment]
New OSFrog scoring system:
- 100 \* Score Multiplier per Icefrog kill. This should apply to your score every kill, not total per wave.
- With each wave killed, the base score goes up by 10 points. So Icefrog Wave 1, 100 \* SM | Wave 2, 110 \* SM | Wave 3, 120 \* SM, etc.

**Comment by MNoya** [comment]
Ok so boss bonus applying over everything just goes away.

**Comment by WindStrike72** [comment]
Yup.

**Comment by Karawasa** [comment]
Probably for the best. By the way, curious what the score is per creep kill normally? Is it just wave number \* SM?

**Comment by WindStrike72** [comment]
Yup. Works out pretty good, save for the clean wave bonus goin' waaaaaay off the deep end.
