### ISSUE TITLE
Flamethrower towers stacked create many popups

### ISSUE THREAD

**Issue by ynohtna92** [Karawasa/Element-TD#109]
Where then is more than one runic tower the popup stack heavily in one area

**Comment by MNoya** [comment]
I see no popup on Runic tower lua, are you sure it wasn't another tower?

**Comment by WindStrike72** [comment]
Might be flamethrower, though technically, you get lots of pop-ups with just one flamethrower tower.

**Comment by MNoya** [comment]
If it is flamethrower, how would we fix it? There is a bunch of damage instances all being triggered at the same time

**Comment by ynohtna92** [comment]
One per explosion perhaps instead of triggering the visual on all targets it has hit.
