### ISSUE TITLE
farz not working on main client

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#112]
![img](http://puu.sh/n9aui/bfc078ab0c.jpg)

**Comment by ynohtna92** [comment]
Is there some clipping flag that you forgot to enable?

**Comment by MNoya** [comment]
`SendToServerConsole('r_farz 10000')` only works on tools mode, I'm uploading a test with `Convars:SetInt('r_farz', 10000)`

**Comment by MNoya** [comment]
Need to do the Convars call on a lua client modifier too.
