### ISSUE TITLE
Life Tower Tooltip

### ISSUE THREAD

**Issue by elklopso** [Karawasa/Element-TD#115]
Maybe it would be nice to change the Tooltip if you are over 50 life? Like an Aghs Upgrade style that you need 9 kills now and it goes away when you drop below 50 again? Or maybe just Change the Color of the "50" and "9" in the Toopltip to make them more obvious?

**Comment by MNoya** [comment]
It's impossible to dynamically change tooltips, but we can make the part of the tooltip that talks about the 50 lives more clear.

**Comment by elklopso** [comment]
I know its a bit wacky but what if you really make it an aghs upgrade that you apply like alchemists buff but you wpnt show the buff in the bar? And debuff the towers when the lifes drop?

**Comment by MNoya** [comment]
Not sure, the tower already has 2 buff tooltips, wouldn't want to add one more just for a mechanic that can be read directly from the main ability tooltip
