### ISSUE TITLE
Quark Tower needs to be AoE

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#117]
As it is, it's a horrible synergy with its natural builds. Go for fire (to have blacksmith), it's nothing but single-target (Electricity isn't really AoE). Go for dark (to have trickery), you've got gunpowder, but you've got a triple-element tower of the same damage type that's also single-target. In general, this tower would be far more useful if it was changed to 100/200 AoE.

EDIT: I just ran a set-up of 100k networth end-game, cause that's usually how much I get by then with that build. It is an incredible tower end-game, once you have the full support for it, but until then, it is really, really bad. Overall, it really needs to change to AoE.

**Comment by MNoya** [comment]
Gotta update the tooltip later
