### ISSUE TITLE
Portal Visuals

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#12]
- [x] Add 200% from .., 50% from ... indicator http://puu.sh/lQkuc/e9c6cd0e36.jpg
- [x] Create custom portal particle with color change

**Comment by ynohtna92** [comment]
The first one seems redundant as the wave info UI displays damage multipliers.
Not sure about the second, it may be too visually overwhelming with all the stuff already.

**Comment by MNoya** [comment]
You still have to hover over the wave info UI to show it, I think it's ok to notify it, but the world-UI seems hard to do.

For the second one I wanted to use [these particles](http://puu.sh/m1LEd/2bd115e203.jpg), not sure if it will be good but we can always scrap it.

**Comment by MNoya** [comment]
Thoughts http://puu.sh/mOsaP/b21521955f.jpg ?

I think the default chat bubbles look meh (not to mention we need 8 and the api supports only 4 at a time), and if we end up using the spiral we'll need to disable the lightrays on the map
