### ISSUE TITLE
Elemental Summoner despawning on death

### ISSUE THREAD

**Issue by elklopso** [Karawasa/Element-TD#120]
When a Player dies the Elemental Summoner despawns, but the runes and elementals stay on the map. I think it would be nicer if the summoner would still be below the runes?
http://puu.sh/n9hmu/79f2a67cca.png vs https://puu.sh/n9hiD/8ebd7a60f7.png

**Comment by MNoya** [comment]
Yeah I guess I can keep the summoner pedestal but remove the items and abilities
