### ISSUE TITLE
Quark + Blacksmith = Incredulous damage

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#121]
So Quark + Blacksmith results in some rather hilarious damage numbers that are not supposed to happen. Anyhow, this is what's supposed to happen:

Quark tower with base 4000 damage. Level 3 blacksmith buffing it by +3600 damage. Consecutive attacks should apply +25% to both of those numbers, so:
1. 4000 + 3600 = 7600
2. (_1.25) 5000 + 4500 = 9500
3. (_1.25 \* 1.25) 6250 + 5625 = 11875
4. (*1.25 \* 1.25 \* 1.25) 7813 + 7031 = 14844

This is what's actually happening. The base damage of the next attack is being based off the total damage from the base + blacksmith.
1. 4000 + 3600 = 7600
2. (_1.25) 9500 + 8550 = 18050
3. (_1.25 \* 1.25) 22562 + 20306 = 42868
4. (*1.25 \* 1.25 \* 1.25) 53585 + 48227 = 101812

... it is just slightly silly.

**Comment by MNoya** [comment]
`OnAttackLanded with    3 consecutive attacks  Damage:  14842`

Should be working as intended now
