### ISSUE TITLE
Ephemeral resets instantly

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#126]
When Ephemeral tower drops down 7 phasing stacks (aka, below 40% damage, the minimum), it instantly resets back to max damage instead of taking 3 seconds to reset.

**Comment by Karawasa** [comment]
2 seconds.

**Comment by MNoya** [comment]
Adjusted to 2 seconds and the intended reset logic. Please review the balance of this tower ingame, it wasn't working as expected but recently received a nerf (and this fix is another nerf to its effectiveness)

**Comment by WindStrike72** [comment]
While it's resetting, specifically when its damage drops too low, it should not be firing. Currently it is.

**Comment by MNoya** [comment]
Oh wait it should be disabled completely? That's just a huge nerf, isn't it?

**Comment by ynohtna92** [comment]
It always was like that. When we had the channelled ability it would stop attacking.

**Comment by WindStrike72** [comment]
It's a huge nerf, but the tower needs it, it's still OP.

**Comment by Karawasa** [comment]
Let's try 20% minimum instead of disable.
