### ISSUE TITLE
Damage and Build Summaries

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#13]
On demand (button click) display how much % does the player do to each element, considering all its tower damage/DPS, and each % chosen buildings

![img](http://puu.sh/lSjEA/d74c504b4d.jpg)

**Comment by Karawasa** [comment]
Hmm. Not sure if this was useful in WC3. What do you guys think?

**Comment by ynohtna92** [comment]
It probably should be redesigned so that it is easier and more intuitive to understand.

**Comment by Karawasa** [comment]
I'm leaning towards axing it. Bringing this up is just one additional UI element. Information overload is not good. I don't think the information provided is really that useful.
