### ISSUE TITLE
Score Multiplier

### ISSUE THREAD

**Issue by Karawasa** [Karawasa/Element-TD#131]
Specifically, Rush and Chaos. Right now, they just add. They don't multiply. I tried Very Hard with both and got;

3.75

I should have got;

5.25

Rush and Chaos are additive but the sum is then multiplied with the base. So the maximum score possible is;

4 \* 1.75 = 7.

**Comment by MNoya** [comment]
What about the backend? [voting.lua](https://github.com/Karawasa/Element-TD/blob/master/game/dota_addons/element_td/scripts/vscripts/scoring.lua#L205) still sums all the bonus together.
