### ISSUE TITLE
Upload size discrepancy

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#132]
I downloaded the vpk to see whats inside it.

@Karawasa please remove the following files from your game folder:
- kvgen.jar
- flash folder
- materials folder: [all these vtex_c](http://puu.sh/ncom2/085cd2eaf5.png) 
- panorama images folder: [some of these vtex_c](http://puu.sh/ncote/ca57989254.png)
- [all dat flash](http://puu.sh/ncovc/adddeba892.png)

Then discard changes & sync with the repo again to make sure you got only the required files. This was my mistake for not remembering you could have leftover files even tho I removed them from the repository.

I can take care of the 'ready to release' upload as you said.

**Comment by ynohtna92** [comment]
Do we not need the killcam nuke?

**Comment by MNoya** [comment]
yes but after syncing the repo again you would get it so its the same.

Anyway I'll be doing the next release-upload so this doesn't matter much.
