### ISSUE TITLE
Nerf Normal Bounty (Classic)

### ISSUE THREAD

**Issue by Karawasa** [Karawasa/Element-TD#135]
Change the bounty base to 1.091 for normal difficulty on classic mode. Remember, the % increase for other difficulties (for voting UI) goes to;

Hard = 131%
Very Hard = 149%
Insane = 171%

That is just for display of course, the bounties for other difficulties do not actually change.

**Comment by MNoya** [comment]
Can I 130 150 170? ^^

**Comment by Karawasa** [comment]
Yes.
