### ISSUE TITLE
Electricity upgrade 2 shows lvl 3

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#139]
![img](http://puu.sh/ndRTv/c665ffee50.jpg)

**Comment by MNoya** [comment]
> Hewdraw: also the upgrade item damage value for the zeus tower doesnt match, it has one that says DAMAGE: 180/900/4000 and another that says DAMAGE: 170 or DAMAGE: 850

**Comment by WindStrike72** [comment]
It should be 170/850/4,250 damage. I'll double check that.

**Comment by WindStrike72** [comment]
Found the error. Upgrade tooltips are out of date.

... actually a lot of them are out of date. Twill be fixed by next upload.
