### ISSUE TITLE
Disconnecting before/during voting

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#144]
- Can cause the player to not spawn in properly and be placed on the middle of the map or dead
- Can make the voting screen never go away until it times out

**Comment by MNoya** [comment]
If you disconnect during voting then come back at after wave spawn, the interest and difficulty UI never show up.

**Comment by IPROJECT-7** [comment]
The disconnection during voting and crash are the same issue, as when the players load out due to alot of memory usage the machine hangs  for like 2-3 seconds and dota times out,hence disconecting.

**Comment by MNoya** [comment]
We just got dedicated servers, need to try it now and see if it still happens.

**Comment by MNoya** [comment]
Still happening

Logs: http://www.hastebin.com/raceyefefo.vbs

**Comment by ynohtna92** [comment]
![image](https://cloud.githubusercontent.com/assets/2245318/13200791/e367c7c2-d8ab-11e5-8e5b-742e5fe53511.png)

Screenshot of the problem

**Comment by IPROJECT-7** [comment]
As i said it is not the servers issue, it happens because the game freezes(100% memory usage) and then dota 2 times out

**Comment by MNoya** [comment]
Still happening? People should at least now get a Wisp after they reconnect

**Comment by IPROJECT-7** [comment]
Update: The game now works it does not crash or disconnect but it takes up alot of memory hence its laggy(at 70 ping)
