### ISSUE TITLE
Disconnect breaks scoreboard

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#145]
!! (s2r://panorama/scripts/custom_game/shared_scoreboard_updater.vjs_c, line:191, col:38) - Failed to set property value (property=color)(value=undefined)

**Comment by ynohtna92** [comment]
The scoreboard remains broken still when disconnected players are in the game.

**Comment by MNoya** [comment]
We will need to sit during a couple hours this weekend to fix all the disconnection errors.

**Comment by MNoya** [comment]
http://forums.eletd.com/topic/95370-end-game-scoreboard-is-kinda-bugged/
Still present and one of the most consistent bugs to fix, we should give this one more priority

**Comment by MNoya** [comment]
This should be fixed now.
