### ISSUE TITLE
Accidentally enabled a cheat

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#149]
I happened to say "stop" in a sentence in chat and it enabled a cheat. Doesn't matter where in the sentence I say it, it still enables it. Any chance we can get this to uhh... not happen by accident and require something like "-stop" in order to kick it in?

Or better yet, kill it on official release and keep it on the test version.

**Comment by Martan404** [comment]
Or maybe just allow it if you play solo?

**Comment by MNoya** [comment]
I'll make our developer cheats require `-` instead of being activated with or without -

**Comment by vladmarica** [comment]
All commands now require a `-` in front of them.
