### ISSUE TITLE
Add -sandbox

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#150]
A request from someone that wants to experiment, and this was a feature in the SC2 version, where, if the game is single-player only, if you typed in -sandbox, you'd be able to get access to all the cheats and mess around with whatever.

**Comment by MNoya** [comment]
I dislike stuff being hidden under a -command so we kinda need to add a panel for this kind of options in single player.

**Comment by MNoya** [comment]
We can also add a host_timescale slider bar in single player, sandbox or not

**Comment by MNoya** [comment]
I am gonna go with [this design style from Dota Demo](http://puu.sh/nmdwP/0634bc404e.jpg)
- [x] Enable Sandbox mode, single player only (or for devs)
- [x] Resources section
  - [x] Toggle Free Buildings
  - [x] Toggle God Mode
  - [x] Max Elements
  - [x] Full Life
  - [x] Set Gold/Lumber/Essence
  - [x] Set each of the 6 elements individually
- [ ] Spawn section
  - [ ] Set Wave X
  - [ ] Spawn Wave X
  - [ ] Spawn Boss Wave X
  - [x] Clear
  - [x] Stop
- [ ] Pause & Quit

**Comment by WindStrike72** [comment]
Any chance we could include a x2 timescale button?

**Comment by MNoya** [comment]
I'll try but I think host_timescale can't be used on dedicated servers
