### ISSUE TITLE
Scoreboard row stopped working

### ISSUE THREAD

**Issue by Karawasa** [Karawasa/Element-TD#151]
Minimap is totally off, see the pic. Also, my row in scoreboard stopped updating. Other people were fine.

![untitled](https://cloud.githubusercontent.com/assets/7691068/13195341/23bb5074-d775-11e5-9cf6-35db250b9472.png)

**Comment by MNoya** [comment]
Minimap is just your big resolution, nothing we can do

Your row in the scoreboard must be failing because you have a disconnected player on top

**Comment by MNoya** [comment]
Also related to #145

**Comment by ynohtna92** [comment]
Potentially fixed in https://github.com/Karawasa/Element-TD/commit/afc79b98872e977846ad2ffd67443dd5a172e9f8
