### ISSUE TITLE
Incorporating Toyoka's Wisp set in the game

### ISSUE THREAD

**Issue by ghost** [Karawasa/Element-TD#154]
I talked to Toyoka and he said he wouldn't mind if [his Wisp set](https://www.reddit.com/r/DotA2/comments/43nwja/datastar_progenitor_a_look_back_over_one_whole/) was used in the game.

I was thinking that those who are [top 100 on the leaderboard](http://www.eletd.com/leaderboard/players) would have access to use the set. So, it will act as a reward for getting top 100 on the leaderboard. Alternatively, it could just be given to people that have achieved a certain high score.

I wouldn't mind coding this. What are your thoughts?

**Comment by WindStrike72** [comment]
I believe in the future, we may be adding a feature for alternate builders in general, similar to SC2's alternate builders feature. It might be tied to leveling (aka, your general rank), not sure. That is an awesome set though and I'd love to see it used, be it default or alternate builder.
