### ISSUE TITLE
Terrible load/end rate

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#155]
According to [statcollection](http://getdotastats.com/#s2__mod?id=137) a big chunk of games are never reaching the 2nd (finished voting) phase, and 50:50 games get to the end.

**Comment by ynohtna92** [comment]
See if this improves over the next couple days since we now have dedicated servers.

**Comment by MNoya** [comment]
It improved the games that end after it started, but there's still 1/3 games not reaching the second stage of loading

**Comment by MNoya** [comment]
Games ended improved after the last patch, likely due to some fixes on the BuildingHelper/GDS library that made single player lobbies recording more consistent

![img](http://puu.sh/niuvu/c66bed0abd.png)

Currently sitting at 1/4 fail rate

**Comment by MNoya** [comment]
It's getting better!

Peak 24 Feb: 77.5k ended, 10k loaded, 2k started, thats around 86% end rate.

**Comment by MNoya** [comment]
We're stable now.
