### ISSUE TITLE
Money/Wealth Tower Stats

### ISSUE THREAD

**Issue by Karawasa** [Karawasa/Element-TD#165]
I quote from reddit;

Also how much gold Alch towers have earned you, much like how many the lives tracker currently in place for Omni towers atm.

**Comment by MNoya** [comment]
A single stack indicator like Life towers have could work but it would be over the 999 value very fast, kinda making it awkward. Any ideas?

**Comment by elklopso** [comment]
what if there would be a Stats panel? There could be Lifes gaines, Bonusgold, maybe towers buffed for wells and blacksmith, towers cloned?
