### ISSUE TITLE
Pure essence isn't refunded if building fails

### ISSUE THREAD

**Issue by patchandthat** [Karawasa/Element-TD#168]
Had a game where I was building the periodic tower - I had chosen the spot and my builder was on the way to build it.

Then, a trickery tower cloned another tower into the spot I had chosen for my periodic tower, preventing it from being built.

The gold cost of the periodic tower was refunded to me, as you would expect, but the pure essence was not.

**Comment by MNoya** [comment]
Known #152 I'll fix it next

Thanks for the detailed report
