### ISSUE TITLE
Pure Essence Picks

### ISSUE THREAD

**Issue by Karawasa** [Karawasa/Element-TD#174]
Are not being recorded in leaderboard.

**Comment by MNoya** [comment]
@ynohtna92 for this one, should I just send "pure" on any of the schema 1-11 entries?

We can use a mango icon

**Comment by ynohtna92** [comment]
Yes I have set it up to already give it an icon.

**Comment by MNoya** [comment]
![mango](https://cloud.githubusercontent.com/assets/401423/13253245/f0d99dda-da19-11e5-8ce9-5f8355cabb6d.png) 
or 
![periodic](https://cloud.githubusercontent.com/assets/401423/13253248/f4bc5852-da19-11e5-863b-681e7bf7c132.png)

---

If you want cropped versions

![mango](https://cloud.githubusercontent.com/assets/401423/13253339/5d55727c-da1a-11e5-9aac-d281dae19865.png)
![periodic](https://cloud.githubusercontent.com/assets/401423/13253338/5d5456a8-da1a-11e5-90c5-3b43a7db4872.png)

**Comment by MNoya** [comment]
![img](http://puu.sh/njazy/cfab840e96.png)

@ynohtna92 looks good but a bit stretched, try any of this ones:

![pure](https://cloud.githubusercontent.com/assets/401423/13273335/73f37904-da81-11e5-8066-a30984cc8e83.png)
![pure1](https://cloud.githubusercontent.com/assets/401423/13273339/73f9df42-da81-11e5-9377-10202578fa31.png)
![pure2](https://cloud.githubusercontent.com/assets/401423/13273336/73f4476c-da81-11e5-90bc-4dcdbc07a344.png)
![pure3](https://cloud.githubusercontent.com/assets/401423/13273337/73f54d56-da81-11e5-846c-1aa01a6d349e.png)
![pure4](https://cloud.githubusercontent.com/assets/401423/13273338/73f94320-da81-11e5-8152-b91b2838a15d.png)

(GitHub drag & drop upload is so good rofl)

**Comment by ynohtna92** [comment]
New image has been uploaded. Closing this issue.

**Comment by MNoya** [comment]
Did you try any of the circular background images?
