### ISSUE TITLE
Tower prioritizing creeps that are closer to the exit.

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#176]
Do we want this?

**Comment by WindStrike72** [comment]
For certain towers, maybe. I'm thinking Haste Tower would definitely be on there. I'll need to test around some more to figure out what else would really want that.

**Comment by WindStrike72** [comment]
Thought about it some more, I'd have this done to single-target towers. Specifically:
Arrow
Nature
Light
Darkness
Magic
Blacksmith (attack only)
Well (attack only)
Trickery (attack only)
Electricity
Hail
Quake
Haste
Jinx (attack only)
Ephemeral
Tidal

To clarify what this would be:
- Tower attacks creep closest to the exit.
- Tower continues to target and attack that creep until the creep dies or exits range.
- Rinse and repeat

**Comment by elklopso** [comment]
And what if the AoE towers would try to target a creep with most in range? like 
1. Choose Creep in Range with most Creeps in AoE
2. Focus that creep till death or out of range
3. repeat 

:)

**Comment by WindStrike72** [comment]
That would be awesome and most preferable, if possible.

**Comment by MNoya** [comment]
I'm just worried about the possible performance issues it could bring (this requires every-frame script thinkers), won't be adding this until the game is stable.

**Comment by elklopso** [comment]
Would it be possible to give Root, Thorn, Obliteration and Annihilation an attack point? So they target the next Creep near that point instead of their base? That way it would be possible to max the effects of the towers :) Like force them to shoot up a straight line while there are creeps?

**Comment by WindStrike72** [comment]
Obliteration/Annihilation already target furthest creep, which maximizes its effect. Roots/Thorns (along with Ice) should be getting an attack ground function down-the-road, though I think Noya and dizzle wanna knock out all the bugs and the rest of the open issues first.

**Comment by Karawasa** [comment]
I don't like this idea to be honest. At some point, the game plays itself. Placement can go a long way in taking care of this.

Root/Obliteration can benefit from attack ground. That would be fair to add to them.

**Comment by MNoya** [comment]
Root has attack ground already, but Obliteration doesn't, really easy to add though, not sure how good it will be because generally you want the projectiles to go over the max range

I was also doubting this idea that's why I labeled discussion. Really the implementation is no problem, I already have the attack target logic fully implemented in the other towers, changing the selection logic is trivial.

**Comment by MNoya** [comment]
@Karawasa @WindStrike72 What about giving it a go but only enabling it for Normal, as an experiment?

**Comment by elklopso** [comment]
Another Idea: What if you could set a flag or something where you want the tower to focus first instead of just near the tower? So you could make something like the Laser Tower attack the ones that try to leak first, but towers with nice aoe can be set to focus the newer creeps where they are still clumped?

Edit: 
http://puu.sh/nsNAD/92699454f7.png
In this Picture i would set the Quark tower to attack the creep most to the left, the laser to start focus as close to the leak as neccessary, and the Amp towers to amp the new creeps (if there would be more dmg towers behind them, because amping leaking creeps would not be important) :)

**Comment by MNoya** [comment]
'set a flag or something' needs an UI to handle those though.

**Comment by MNoya** [comment]
Should be fully working on Arrow towers, needs extensive playtesting before it can be added to all the single target towers

**Comment by MNoya** [comment]
The system should work well with other targeting logic so we can also add this to:

Disease (Lowest)
Moss (Highest)
Life (Lowest)
Gold (Lowest)

`change_on_leak` flag should be turned off for those.

Impulse (Furthest) will change on leaks (and do the sickest mix of targeting AI in the history of Tower Defenses really)

**Comment by ynohtna92** [comment]
@MNoya Was there anything left to be added to this?

**Comment by MNoya** [comment]
I don't think so, this can be closed
