### ISSUE TITLE
Tower List update

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#177]
I'd like to see the following things in http://www.eletd.com/towers
- [ ] Updated stats and descriptions
- [ ] Screenshot view of the tower
- [ ] Order the duals/triples with the dota order (Primary + Secondary1 + Secondary2)
- [ ] Organize the entries in the classic LDFWNE order
- [ ] Better css on the text, bold/colors
- [ ] Ignore entries that have nothing to show (currently `-`)
- [ ] Show/Hide the full row with 1 click

Optional:
- [ ] Build a system that can pull the data directly from the github repo files and keep an always up-to-date overview

**Comment by kevburnsjr** [comment]
I posted this to the forums but I'll put it here as well.

https://github.com/KevBurnsJr/elemtd_tower_graph

Let me know if there are any changes you'd like me to make for easier integration.

**Comment by MNoya** [comment]
Good work on the Ranges, I should totally add that ingame!

@Karawasa do add this, it's really good. and basically resolves all of the problems of the current design in my opinion.

**Comment by MNoya** [comment]
Oh well 0 fucks given.
