### ISSUE TITLE
Tower Table Discrepancy

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#179]
Flamethrower is currently highlight as a Damage Amp tower; it should not, and instead, Jinx should be highlighted as a Damage Amp tower.

**Comment by MNoya** [comment]
Not technically a bug, we agreed on marking it as amplify ^^
This can be quickly changed here https://github.com/Karawasa/Element-TD/blob/master/content/dota_addons/element_td/panorama/scripts/tower_table.js#L46-L49

**Comment by MNoya** [comment]
Flamethrower should then be marked as AoE.
