### ISSUE TITLE
Change the "1" respawn indicator for a dead icon

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#18]

**Comment by ynohtna92** [comment]
Isn't this already done with the top bar and flyout bar?

**Comment by MNoya** [comment]
Hmm I guess yeah, it's just the bar shows a big '1' that could also be filled with it (or just a dead symbol/RIP)

**Comment by ynohtna92** [comment]
I think a skull would be better like how it is done in scaleform ui.

**Comment by MNoya** [comment]
Done in 9a788bcc2e7b545b020d3ea0dd0d26fc8cb556ad
