### ISSUE TITLE
Next wave starts in 60 seconds

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#180]
So someone let me know of a certain abuse trick, where, on the first wave, blow up everything but one creep, sell all your towers, and then let the creep leak 49 times to accumulate god interest, and then play the game from there. Normally, this is considered a "cheap" way to play, but technically, nothing is preventing it... yet.

Could we add a 60 second timer to all waves? When you defeat the wave, the countdown timer for the next wave still starts; this would just prevent people from doing this particular trick. It would also theoretically make the game slightly harder, buuut that's negligible.

**Comment by MNoya** [comment]
This isn't critical please don't scare me :yum:

**Comment by WindStrike72** [comment]
Well, it kinda is. Based on the way scoring works, the combo stuff is done by consecutively winning, so only the first wave would drop to 0 score. The rest of the waves would score properly, annnd between having ungodly amounts of gold and being able to beat anything (like camping the front entrance on insane difficulty to max speed), anyone could get top score with this trick. Buuut in the sense of "game doesn't run properly", not critical... just game-breaking in balance.

**Comment by MNoya** [comment]
I see. Legit strat but we should probably remove it.

![img](http://puu.sh/ng4tU/463a09f973.jpg)

**Comment by MNoya** [comment]
Another option is making leaks from the same creep lose lives exponentially. So the 2nd team it leaks for 2, then 4, then 8, at the 5th leak you have lost 31 HP from the same mob and it will kill you on the next time it goes through.

**Comment by Karawasa** [comment]
I like Noya's idea. Let's roll with that.

**Comment by elklopso** [comment]
Yeah Noya's idea is better :) But I think elements shouldn't scale that way, since they are already independent from waves

**Comment by WindStrike72** [comment]
Still doable and still breakable, especially with life towers.

If a wave leaks, have it pause interest until that wave is defeated.

**Comment by vladmarica** [comment]
I'll fix this one up once I get home from school
