### ISSUE TITLE
Show best rank in player profile

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#183]
http://www.eletd.com/leaderboard/players/34961594
Alongside best score, show the rank that score achieved at that time. Should have some hours delay

**Comment by ynohtna92** [comment]
Players rank is already shown on the top right of the screen. I guess it would be better to combine them and list for both express and normal. Still need to fix the SQL query however since it is taking way to long to execute.

**Comment by MNoya** [comment]
Hmm I see, yeah just need to fix it to not take values of a different version then. Currently [our rank 1](http://www.eletd.com/leaderboard/players/13364551) player is **Rank 2 (0%)** even tho he also had the Rank 1 :p

**Comment by ynohtna92** [comment]
It is because Kara changed the function and the new function does a count on all entire ever received and not per version. He will need to revert this. I will be making a summary table in the db to speed up request.

**Comment by ynohtna92** [comment]
Closing this since it has been added a while ago.
