### ISSUE TITLE
Show how many lives has a life tower earned

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#19]
With a stack counter

**Comment by Karawasa** [comment]
Just wanted to confirm that a life tower itself has no individual counter right? Kills tallied are shared among all life towers.

**Comment by MNoya** [comment]
Correct, the stack indicator just goes to show "how good of a tower placement is this" by showing how many +1life lasthits were done by that tower. The counter is still global, all life towers contribute to it.
