### ISSUE TITLE
Ability to cancel tower upgrade

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#190]
http://forums.eletd.com/topic/95297-should-be-able-to-cancel-tower-upgrades/

Twould be nice to have a cancel feature in. It should full refund gold and essence, regardless of random or not.

**Comment by MNoya** [comment]
I think we can't bind Escape. But there could be a Cancel button tied to the first hotkey (Q)

**Comment by vladmarica** [comment]
@MNoya, see [this](https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Panorama/Events#Default_Event_Attributes), look at `oncancel`. Could that be used?

**Comment by MNoya** [comment]
I think that only works if you have the panorama panel on focus.
