### ISSUE TITLE
Loading Screen Tips

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#191]
Ingame. Ideas?

**Comment by MNoya** [comment]
We should introduce Tips on the loading screen and have the latest changelog show up there too.

"Tips" would say things about that game that many people would miss, like"
- You can play Sandbox in Single Player
- You can create single player lobbies if you do bla bla bla
- Slows stack multiplicatively (meaning 3 10% slows are worse than a single 30% slow)
- etc

**Comment by elklopso** [comment]
- View the Leaderboard on www.eletd.com
- Often Quality is better than Quantity
- The Interest Timer stops at the Boss waves, spend your gold!
- Don't choose Level 3 Elements too early
- Each Support Tower can supply 4 Towers with Buffs
- Got Ideas to make the game better? Join the discussion at www.eletd.com!

**Comment by MNoya** [comment]
Good, put them [here](http://forums.eletd.com/topic/95381-submit-your-tips-here/) if you get more
