### ISSUE TITLE
Hail Tower Not Buffed

### ISSUE THREAD

**Issue by Karawasa** [Karawasa/Element-TD#192]
From steam;

support towers avoid buffing "Hail Tower"

**Comment by MNoya** [comment]
Tried it, happened once but then I couldn't reproduce the problem. Pushed a small fix in dfe99203a235fec39a13a1af5864e90901f05920 that might have resolved it, due to cloning being on the mix

**Comment by MNoya** [comment]
Someone reported this again.

**Comment by MNoya** [comment]
Aand can't reproduce again.
