### ISSUE TITLE
Speed Bonus

### ISSUE THREAD

**Issue by Karawasa** [Karawasa/Element-TD#194]
Timer for time taken should start after the last creep has spawned. Not first as it is now.

**Comment by ynohtna92** [comment]
How should it be done?

This is how it is currently according to the spec sheet.

> When you clear a wave, you get a score multiplier based on the time you cleared the wave, depending on a base of 30 seconds.
> 30 seconds gives you a multiplier of 1. Every second below 30 increases the multiplier by 0.02.     Every second above 30 decreases the multiplier by 0.01.
> Since creeps spawn at a rate of 2 per second, if you're camping the entrance, the best score multiplier you can get is 1.3.
