### ISSUE TITLE
Builder Movement Speed

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#196]
This didn't work for some mysterious reason b57b252b70ec0e5d53170536ca1b3a896fd7a863

**Comment by MNoya** [comment]
I don't know what's up with this. If I do -createhero wisp and apply it, it works just fine

**Comment by MNoya** [comment]
modifier_tutorial_npcblocker seems to be the cause of this

**Comment by vladmarica** [comment]
Removing triggers was not necessary, removing the tutorial blockers is enough. Let me know what you think of it. 

The only problem I can see is that when a Wisp moves really fast, its particles get stretched out far and it looks weird.
