### ISSUE TITLE
Improve Match Info

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#198]
Take http://www.eletd.com/leaderboard/matches/4961943 for example
- [x] Show if the game was Same or All Random, or single random in All Pick
- [x] Show Life gained or Gold gained if any
- [x] #174 Pure Essence sequence
- [x] Show the Dota 2 MatchID

Not sure but:
- Normal should be called "Classic"?

**Comment by Karawasa** [comment]
I removed storage of life tower gains and gold tower gains (to save DB space) so do not display those :P.

Yes, normal should be called Classic.

**Comment by ynohtna92** [comment]
DB space is going to go up regardless of removing two columns, it is probably best to leave it. We can always come back to it in the future, but we can never get stats for data that does not exist.

**Comment by MNoya** [comment]
Added _Show the Dota 2 Match ID_ for matching replays. Seeing WindStrike's [how to look up replays](http://forums.eletd.com/topic/95307-how-to-look-up-replays/), we need to find a way to pull this data from the game coordinator after the match ends.

**Comment by ynohtna92** [comment]
I have messaged Daniel and Jeff regarding valve match id api. Lets see if they pull through.

**Comment by ynohtna92** [comment]
I suggest you try to reach Daniel or Jeff and ask about a steam match id api since they may listen to you.

**Comment by MNoya** [comment]
Alright I'll write them asking for a couple of things.

Unrelated, but I think the "Won" tab is now redundant if we are only going to save the finished games.

**Comment by ynohtna92** [comment]
I can remove it from the top 100, but why are we only tracking won games? It will be filled with people that use sandbox mode as well, skewing the data further. I want to track all games that finish no matter what so that all players will be able to rank on the leaderboard.

**Comment by MNoya** [comment]
I think it was because @Karawasa said that by doing so, the leaderboard summary would be way faster & disk size was also a concern

**Comment by MNoya** [comment]
@ynohtna92 I got an answer, it's happening!

> I've just added GetMatchID() to the Gamerules API, which will ship in the next update.

**Comment by MNoya** [comment]
Alright let's do it!

```
---[[ CDOTAGamerules:GetMatchID  Get the MatchID for this game. ]]
function CDOTAGamerules:GetMatchID(  ) end
```

**Comment by ynohtna92** [comment]
Done! http://hatinacat.com/leaderboard/matches/6672699
@Karawasa will need to update eletd.com with the files I have sent him for it to work there.
4e318da786fd87d8063f108a0b4760a5155bf9a7
