### ISSUE TITLE
Boss Kills Leaderboard

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#199]
On each difficulty

**Comment by ynohtna92** [comment]
Can you describe what you want clearer? This may be pointless to show since it will just look like the difficulty pick % that is already there.

**Comment by MNoya** [comment]
The idea with this was to give an alternative approach to the leaderboard, not focused on scores (so no Chaos+Rush spam), but just killing Icefrogs in Normal difficulty. It could be either an orderest list of matches witht he highest frog kill counts, or a total sum of lifetime frog kills, up to what you think would be best

**Comment by ynohtna92** [comment]
Different leaderboards can be added however, they will need their own table and be precalculated. So we need to be clear on what extra things we want to have since there can be hundreds of different combinations.

**Comment by ynohtna92** [comment]
Completed at http://hatinacat.com/leaderboard/players/frogs

**Comment by MNoya** [comment]
Perfect, now just need @Karawasa to add it for the next patch
