### ISSUE TITLE
UI List

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#2]
Scaleform elements to convert:
- [x] Voting (Game Setup) ae31b88dafd2f855d65de796bedfddce52ea1179
- [x] Element Board 5658ee55c8c33fc1e432b88613b032cfe2c8f564
- [x] Waves 3cb113fe3073d1ee549a21474abc55387f44f71a
- [X] Interest 2b859cec82a468087922c03aed82d485af865629

To add:
- [x] Tower tree 0e9b346d46eb7e146c4b1ef251acad99cb589489

**Comment by ynohtna92** [comment]
Interest scaleform element has been converted

**Comment by ynohtna92** [comment]
Element Board and Waves have been ported.

**Comment by ynohtna92** [comment]
Voting (In game) UI is done and thus concluding the scaleform port.
I may add voting progress in future to the existing UI so people know what others have voted for and who hasn't voted.

**Comment by ynohtna92** [comment]
How does this look?
![image](https://cloud.githubusercontent.com/assets/2245318/11802184/ee505112-a341-11e5-8d61-6ec060a3ae63.png)

**Comment by ynohtna92** [comment]
Not sure if it should disappear after this screen or the results screen though. Let me know.

**Comment by vladmarica** [comment]
Looks really good. I suppose it should disappear after this screen since it don't match the size of the Vote Results screen. @Karawasa @MNoya, what do you think?

**Comment by MNoya** [comment]
Disappear is fine, the not voted section is just a help to see what others are voting.

**Comment by MNoya** [comment]
Tower Tree done!
