### ISSUE TITLE
Pures build in a second

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#200]
Woops, didn't check this after all. Pure towers are taking 1 second to upgrade to instead of 3 seconds.

**Comment by MNoya** [comment]
Only Nature and Water towers actually, I forgot to revert the 1sec change we were discussing
- [dark](https://github.com/Karawasa/Element-TD/blob/master/game/dota_addons/element_td/scripts/npc/units/towers/basic/pure_dark_tower.txt)
- [earth](https://github.com/Karawasa/Element-TD/blob/master/game/dota_addons/element_td/scripts/npc/units/towers/basic/pure_earth_tower.txt)
- [fire](https://github.com/Karawasa/Element-TD/blob/master/game/dota_addons/element_td/scripts/npc/units/towers/basic/pure_fire_tower.txt)
- [light](https://github.com/Karawasa/Element-TD/blob/master/game/dota_addons/element_td/scripts/npc/units/towers/basic/pure_light_tower.txt)

Then
- [nature](https://github.com/Karawasa/Element-TD/blob/master/game/dota_addons/element_td/scripts/npc/units/towers/basic/pure_nature_tower.txt)
- [water](https://github.com/Karawasa/Element-TD/blob/master/game/dota_addons/element_td/scripts/npc/units/towers/basic/pure_water_tower.txt)
