### ISSUE TITLE
Wave timer delay feature

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#201]
(This suggestion came from WC3/SC2 EleTD player Venny)

Namely for new players, but would it be possible to add a feature for everyone where they can (as a one-time use) delay the wave timer for the next wave by 30 seconds? Could be used as a nice breather.

**Comment by MNoya** [comment]
Maybe but would new players know to use that delay?

**Comment by Karawasa** [comment]
I don't like it to be honest :(.

**Comment by WindStrike72** [comment]
Yeah, that's what I was worried about, new players not having a bloody clue the feature is even there.

**Comment by MNoya** [comment]
I take we are discarding this
