### ISSUE TITLE
Interest Timer Freeze

### ISSUE THREAD

**Issue by Karawasa** [Karawasa/Element-TD#203]
"The newest interest leak addition is bugged. it doesn't take into account leaks over multiple waves. So you could eventually kill everything and still have a non-functioning interest timer. This is true for both the same unit leaking twice (not uncommon in all random rush mode) and for leaks from multiple levels."

**Comment by vladmarica** [comment]
It was designed for leaks over multiple waves. Still, I'll look into it.

**Comment by vladmarica** [comment]
I cannot replicate this. Can anyone else?

**Comment by MNoya** [comment]
Try Rush mode, -lives 5000 and kill everything after 5 waves

**Comment by WindStrike72** [comment]
I've run into this once so far, but the timer eventually unfroze, not sure why.

**Comment by vladmarica** [comment]
Should be fixed in a0c10b2. Reopen this issue if it still comes up.
