### ISSUE TITLE
Hax

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#204]
I'm not entirely sure what's causing this, but you know that top score of "Insane + Chaos + Rush" on the top of the leaderboard? Watch the replay (to do so, **Watch** --> **Replays** --> enter the match id of 2171832787). At the start of the game, they're somehow spawning Tombstones and blowing 'em up for 200 gold each. I don't think it's a bug, just a straight hack or something. Sadly, said players can't even beat the game despite having unlimited gold.

Would it be possible to ban user ids from the leaderboards for anyone that does some sort of cheat method? If so, don't actually ban these two, just remove their scores from the leaderboard and then stick a warning at the top that anyone using some sort of cheat will have their userid banned from it.

Thoughts?

**Comment by Karawasa** [comment]
I deleted their scores. But I'm curious how they pulled off the hack...

**Comment by MNoya** [comment]
Cheating _ingame_ is on us, go easy on them. There's no need for any warning, that just makes more people want to hack

**Comment by MNoya** [comment]
I finally got what you meant with Tombstones, as in the actual `npc_dota_unit_tombstone1` unit, created using `dota_create_unit` on console. Should be easy to fix

**Comment by MNoya** [comment]
Apparently you can't do dota_create_unit even on cheat-enabled lobbies. Must be a problem with the cheated flag not being registered or a cheat code we dont know of yet

**Comment by MNoya** [comment]
Fixed in next. Just nuke those fools.
