### ISSUE TITLE
Can't hit the X button in a replay

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#205]
If you're watching a replay, trying to exit out of it with the little X button in the top-right corner is blocked due to the interest timer blocking it. In case you're wondering how to watch a replay, see this thread I just posted here - http://forums.eletd.com/topic/95307-how-to-look-up-replays/

**Comment by MNoya** [comment]
Does the interest work in replays, or it's just a static bar? Gimme a match ID

**Comment by MNoya** [comment]
@WindStrike72 is this still a problem?

**Comment by WindStrike72** [comment]
Yup. Interest bar completely covers the x button, it's not even visible.

**Comment by MNoya** [comment]
Solution will be having the interest bar hidden by default, instead of it being hidden at hud loading (which never happens, because the event to game start never gets called)
