### ISSUE TITLE
Add a toggle for full Alt-Grid

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#209]
Some people have mentioned that having the whole grid visible while building would help them decide the best spots to build (specially in between various towers). 

![img](http://puu.sh/nhMCa/d3544b8a5f.jpg)

A fully filled grid showing the valid positions, as a toggle button somewhere (maybe **G hotkey**?), could be easily implemented.

**Comment by ynohtna92** [comment]
What about double tap the key is already assigned to toggle it.

**Comment by MNoya** [comment]
Maybe I can just straight up bind Alt to toggle, not hold-to-show Alt.

**Comment by WindStrike72** [comment]
How bout adding it to one of the builder's item slots, so it's not an obscure feature?

**Comment by vladmarica** [comment]
I like Windstrike's idea.
