### ISSUE TITLE
Top bar wave indicators stopped updating after a point

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#21]
This might be due to players disconnecting.

**Comment by MNoya** [comment]
![img](http://puu.sh/mzDnw/717efc0f9a.jpg)

**Comment by ynohtna92** [comment]
Did it leave any errors? It is hard to figure out what is going wrong without them.

**Comment by MNoya** [comment]
Sorry was busy losing :smile: we think its related to reconnection, must try to reproduce it

**Comment by ynohtna92** [comment]
Fixed by c3b06819795ce9833530c2c61a4b28383ba11fd1
