### ISSUE TITLE
Bring back Start Wave button for the first wave in single player

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#213]
TreeSquirrel suggested -5 seconds per difficulty

I believe you don't get into an Insane Chaos Rush without knowing what will your opening be or being experienced with the game, so this makes sense.

**Comment by ynohtna92** [comment]
Alternatively we can bring back my start wave button for when the game is only played by one player at the start.

**Comment by MNoya** [comment]
Yeah that would be great!
