### ISSUE TITLE
Particle Effects Recoloring

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#215]
In an attempt to match Mayheim's new icons - http://puu.sh/njgXI/9f32244c45.png - annnd in order to match some attacks to their elements, I suggest some changes to certain towers' attacks, if possible:
- **Obliteration**, change the blue color to a purply color.
- **Electricity**, change to a orange-red lightning

Any others anyone can think of?

**Comment by vladmarica** [comment]
Change Trickery tower illusions to yellow

Also, that new Electricity icon looks ... odd. The colors seem off, like the saturation is too high.

**Comment by MNoya** [comment]
Will wait for the final icons before recoloring/readjusting everything

**Comment by MNoya** [comment]
Recolored effects for **Trickery, Poison, Obliteration, Electricity** coming up next
