### ISSUE TITLE
Add delay to Gunpowder's secondary explosions

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#216]
So instead of attempting that "artillery projectile" thingy to Gunpowder, here's a better change that'd effectively do the same thing: add a delay to the secondary explosions. Say, 0.3 seconds.

**Comment by MNoya** [comment]
Honestly the delay looks super odd. You sure you don't want to try attacks going to the ground? It would nerf the tower, but give it a more distinctive mechanic

**Comment by WindStrike72** [comment]
Well if that's the case, then sure, go for attacks going to the ground.

**Comment by MNoya** [comment]
Done.
