### ISSUE TITLE
Make the creeps level equal to the level of the wave

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#22]

**Comment by MNoya** [comment]
![img](http://puu.sh/mzDnw/717efc0f9a.jpg)

**Comment by ynohtna92** [comment]
Is it possible to set the level of a npc in lua? I can't seem to find a function for that.

If there is no function the only way to do it would be to update the npc kv sheet but since our units are not tied directly to a wave this will not be possible.

**Comment by MNoya** [comment]
unit:CreatureLevelUp(levels)
