### ISSUE TITLE
Sometimes the building queue process wont start

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#224]
See: https://www.youtube.com/watch?v=D4w98n-bs2A&feature=youtu.be&t=13m12s

Can't reproduce yet. Maybe related to Hold/Stop/Shift

If you find the repro steps, post here.

**Comment by WindStrike72** [comment]
I've run into this a few times, not entirely sure what the order of what the heck I did to cause it, it was mainly panic build. I'll see if I figure this out.

EDIT: Kay, it's not a bug. If you shift+queue a few towers but then right-click move in the middle of that process, it'll cancel the queue..... which is what happens in normal dota with anything. If you watch that video closely, he does that right after trying to shift+queue three of them. This is pretty much just a result of panic building.

Steps:
1. Shift+queue some towers far away.
2. Do a right-click move somewhere before you get to them.

**Comment by MNoya** [comment]
No, it is a bug, check the video again from that timestamp, he places 3 towers but the wisp doesnt move to build them. He only right clicked to be able to cancel the queue and start again.

**Comment by MNoya** [comment]
Repro steps:
1. Have autoattack off
2. Press Stop or Hold
3. Shift (mandatory)
4. Build (while keeping shift)
