### ISSUE TITLE
Lightning Tower particles broken

### ISSUE THREAD

**Issue by vladmarica** [Karawasa/Element-TD#227]
![](http://i.imgur.com/iCl9BTz.png)

Related errors:
`[ResourceSystem]: ERROR: RESOURCE_TYPE_PARTICLE_SYSTEM resource 'particles/units/heroes/hero_zuus/z_w.vpcf' (6BA65E0D264150C1) requested is not loaded and may have been deleted.` 
`[General]: Attempting to use invalid particle effect "particles/units/heroes/hero_zuus/z_w.vpcf"!`

**Comment by MNoya** [comment]
This happens only under tools when you don't precache the things in time. To increase loading performance, I separated the precache of towers in various stages, defined in [precache.kv](https://github.com/Karawasa/Element-TD/blob/master/game/dota_addons/element_td/scripts/kv/precache.kv#L66)

If you use the -dev cheat, it will [execute all the precache lines at once](https://github.com/Karawasa/Element-TD/blob/master/game/dota_addons/element_td/scripts/vscripts/developer.lua#L193-L203) and this particle problem should go away.

**Comment by vladmarica** [comment]
Never mind, precaching problem on my end
