### ISSUE TITLE
3 Pure random?

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#228]
http://www.eletd.com/leaderboard/matches/5202256

Something is off

**Comment by WindStrike72** [comment]
I just went random and cheated me some lumber to yoink this early. I was only able to get one **Pure Essence** and then red error message popped up. Here's the console shenanigans;

[   Developer            ]: ...ame\dota_addons\element_td\scripts\vscripts\summoner.lua:285: This object has been deleted from C++ and no longer exists. (Use :IsNull() to detect this.)
[   Developer            ]: stack traceback:
[   Developer            ]:     [C]: in function 'GetCurrentCharges'
[   Developer            ]:     ...ame\dota_addons\element_td\scripts\vscripts\summoner.lua:285: in function <...ame\dota_addons\element_td\scripts\vscripts\summoner.lua:262>
[ W VScript              ]: Script Runtime Error: ...ame\dota_addons\element_td\scripts\vscripts\summoner.lua:285: This object has been deleted from C++ and no longer exists. (Use :IsNull() to detect this.)
[ W VScript              ]: stack traceback:
[ W VScript              ]:     [C]: in function 'GetCurrentCharges'
[ W VScript              ]:     ...ame\dota_addons\element_td\scripts\vscripts\summoner.lua:285: in function <...ame\dota_addons\element_td\scripts\vscripts\summoner.lua:262>

**Comment by MNoya** [comment]
Well, in Random it's still possible to get lucky with 3 essences I guess. I checked and we have no other restriction that having at least 1 element at lvl 3 or everything at lvl >=1.
