### ISSUE TITLE
Scoreboard doesn't update until closed and open again

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#23]
![img](http://puu.sh/mzDvt/4db11ed97a.jpg)

Then

![img](http://puu.sh/mzDxv/ce07e3751c.jpg)

**Comment by ynohtna92** [comment]
Again were there any panorama errors being printed? I fixed this a while ago.

**Comment by MNoya** [comment]
It's likely a disconnection issue

**Comment by ynohtna92** [comment]
Fixed by c3b06819795ce9833530c2c61a4b28383ba11fd1
