### ISSUE TITLE
Frog got stuck

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#236]
See this thread - http://forums.eletd.com/topic/95350-frog-bug/#comment-120609

**Comment by WindStrike72** [comment]
Kay, ran another match, this time it was an Icefrog with Reincarnation that hadn't died yet. I'll get console log next time.

**Comment by MNoya** [comment]
Thread link hidden/removed

**Comment by MNoya** [comment]
WTB Reproduction steps

**Comment by MNoya** [comment]
Maybe fixed on 5348715d3dbfa89ec0712c8c9b589f8f02996e37

**Comment by WindStrike72** [comment]
So this is in a test prior to fix, but I managed to get the console log.

[   VScript              ]: scripts/vscripts/interest.lua:112: attempt to index a nil value
[   VScript              ]: stack traceback:
[   VScript              ]:     scripts/vscripts/libraries/timers.lua:135: in function '__index'
[   VScript              ]:     scripts/vscripts/interest.lua:112: in function 'PauseInterestForPlayer'
[   VScript              ]:     scripts/vscripts/wavedata.lua:418: in function <scripts/vscripts/wavedata.lua:410>
[   VScript              ]:     [C]: in function 'xpcall'
[   VScript              ]:     scripts/vscripts/libraries/timers.lua:134: in function <scripts/vscripts/libraries/timers.lua:95>
[   VScript              ]: 

This showed up in console at the exact time the icefrog bounced back. Had it happen once on boss wave 2, and twice in a row on boss wave 3.

**Comment by MNoya** [comment]
Hopefully fixed with 9eb5515d8868879f38531ac49d6b5f282daf409d
