### ISSUE TITLE
Units clumping too much on max slowing

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#240]
So in the doc, I believe it says there's supposed to be a minimum of 50 range between creeps to avoid clumping, though I've gotten cases of 5 creeps stacked almost completely on top of each other, making AoE unintentionally stronger than intended. Could we have the collision radius bumped up from whatever it is to 50?

**Comment by MNoya** [comment]
We aren't controlling distance at all, units have phasing.
