### ISSUE TITLE
Interest Timers bugged to hell

### ISSUE THREAD

**Issue by vladmarica** [Karawasa/Element-TD#241]
Certain things were overlooked which could cause bugs like interest timer restarting visually and creeps stopping movement. Please don't push updates to the workshop until this issue is resolved.

**Comment by MNoya** [comment]
Roger that

We also need to guarantee them working during disconnection/reconnection

**Comment by vladmarica** [comment]
The bugs I listed should be fixed in 8b0865a, but it will require playtesting to be sure. Disconnection/reconnection handling is next.

**Comment by MNoya** [comment]
Seems good
