### ISSUE TITLE
Moar Particle Effects Stuff

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#243]
So with the balance patch I pushed, I updated a lot of projectiles, annnd a few of them need some updates.
- [x] **Flamethrower Tower** now uses Ogre Magi's Ignite, need the projectile recolored to orange.
- [ ] **Quark Tower** now uses Skywrath Mage's Concussive Bolt, which looks cool, but the light might be a little too flashy and could use some toning down.
- [x] **Flame Tower** now uses Invoker's Fire Spirit's attack. I just need an opinion on whether you folks prefer this one or Phoenix attack.

**Comment by MNoya** [comment]
Doesn't tidehunter_gush (new Flooding) lag when fired every second?

I think Phoenix attack is better (bigger projectile) for Flame, and we aren't using it anywhere else so that can stay.

I will take care of those 2 particle edits (or maybe tell you how to do them, its really easy hehe)

**Comment by WindStrike72** [comment]
I would indeed like to learn how to do particle edits, though maybe after this patch, I've gone full double vision, lol. Gush surprisingly does not lag from that actually. Had two of 'em with level 3 waterfall, no lag on their part.
