### ISSUE TITLE
Hide Player's SteamID

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#245]
I was thinking having the steam ID of the players be public on their profiles, allowing for the replay download trick, gives up too much information that we would like players to have control over. We should either have a steam login and options to turn it off/on, or hide it completely.

**Comment by elklopso** [comment]
I would like to get the replay ID from that page :) I don't really care about the steamID. 
What if there would be a checkbox at the voting screen to disable Leaderboard? So you could not get you steamID exposed? or try where you would land with a new build, without getting everyone to look at it? But if you wanna rock the leaderboard you have to turn it on and then everything gets exposed?

**Comment by ynohtna92** [comment]
Since the whole system relies on steam IDs the only way we could do this is by having a steam login tied to their account.

I have emailed Jeff about replay/match ID API so we can easily determine the game played. We will see what he says.

**Comment by MNoya** [comment]
I mostly bring this up because of people complaining their strats are leaked and copied, and I believe its a legit concern.

**Comment by MNoya** [comment]
Continue the discussion about public matches here: http://forums.eletd.com/topic/95390-what-do-you-think-of-the-ease-of-access-to-builds/

MatchID API is confirmed to be on next Dota update.
