### ISSUE TITLE
Sandbox issues

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#246]
Just a list of stuff I screwed with:
1. When selecting something in a textbox, typing another number does not overwrite, and you have to hit backspace or delete first in order to input said number, which can be a little annoying.
2. You can input letters or other symbols in the text boxes. Not that they actually do anything...
3. Spawn Wave and Set Wave are redundant. Both of them set the wave to what you type in, just one has a countdown timer and the other is instant. Not sure if intended or not.
4. There's a button for halting the wave, but not a button for resuming it.
5. This one might not be fixable as I assume "Speed Up" is essentially host_timescale 2. Try turning it on and off a bunch of times repeatedly, and the game gradually slows down, dropping into a timescale that's lower than 1. I know this issue happens already when trying to change host_timescale manually.

I got some other issues I can post up, but I gotta pull some repros and figure out the steps before I can.

**Comment by MNoya** [comment]
1. Noted, will fix
2. I won't bother, if you type a letter its your fault, it won't have an effect if you write "Kappa" gold
3. Set is supposed to start the wave breaktime, Spawn just sends it automatically, they are similar both have their uses I think.
4. Resuming it it's hard and not really useful I think? There's Clear Stop and Start, after a Stop you can just Start again.
5. Speed Up it's host_timescale 3 then 1

**Comment by MNoya** [comment]
jk 2 is easy regex, fixed 1 now
