### ISSUE TITLE
Keep track of "Best Rank" after each reset

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#249]
When we reset the leaderboard, we should update an entry on every player at the moment of the reset, to keep track of their best rank. Players that achieve a top XX but get their rank forgotten forever would feel disappointed.

**Comment by ynohtna92** [comment]
Yeah already thought of this. Just top 10 or keep track of everyone?

**Comment by MNoya** [comment]
Everyone would be nice, if it's not too expensive on the DB.

**Comment by ynohtna92** [comment]
Milestones have been added for our versions http://hatinacat.com/leaderboard/players/87278757. However I am not sure how to display them at the moment. Please give advice.

**Comment by MNoya** [comment]
Just to the right of Best Score and naming it Best Rank perhaps?

Also but unrelated, should we make Sandbox a game mode in the end schema sending? Replacing All Pick/Random

**Comment by ynohtna92** [comment]
There won't be enough space to put them to the right of Best Score if we continue to track ranks for each leaderboard reset. I'm thinking I will just add an other section above stats and display them all there with the badges. 

I'm not sure I understand you but if the gamemode is sandbox, send 'Sandbox' instead of 'All Random'. This shouldl be done for the player random variable.

**Comment by MNoya** [comment]
Ranks for each leaderboard reset? I thought we were only going to display the best in the player profile. There's plenty of space, at least on this resolution http://puu.sh/nsHNb/3b5a3ba463.png
History review could be good but isn't that too expensive to keep for all players?

**Comment by ynohtna92** [comment]
It isn't the way I have it set up. The tables are approx. 15MB in size for both normal/express per version. It is only ever calculated once when we switched the version over and has almost no overhead.

**Comment by ynohtna92** [comment]
Updated on http://hatinacat.com/leaderboard/players/34961594. Please like it master!

**Comment by MNoya** [comment]
I like it! Align center with the same font size/bold than the "STATS" text imo. And probably replace "Milestones" with "Best Ranks"?

**Comment by ynohtna92** [comment]
Best ranks sounds stupid. I prefer milestones or something similar. Maybe 'achievements'. Reset your cache as the styling is already there.

**Comment by MNoya** [comment]
Oh I thought we were just going to do a single lifetime "Best Rank", you plan on just having this Milestone bare showing all the ranks ever? That works too. Probably ordered by better rank? Would those be Express or Classic?

I refreshed my cache, I see the badge and new styling is great, gotta do the same handling in the page for the >1% to show decimal points as 0.1%
