### ISSUE TITLE
Sandbox capable of getting score?

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#252]
Just happened to see this match, haven't tried looking up the replay yet, but under elements, it says 3 across the board.... which is only possible in sandbox mode.

http://www.eletd.com/leaderboard/matches/5618392

Could that also be the cause of the top score that's got 8 million points?

**Comment by MNoya** [comment]
Is the replay available? Enabling the sandbox should mark the lobby as cheated.

We need cheated/sandbox to be visible on the match data
