### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#254]
IPs http://pastebin.com/DuzSSKKM

**Comment by ynohtna92** [comment]
White-listing has been added to hatinacat.com and can be taken advantage of  with the new match table column 'whitelist = 1'. The files will be passed onto @Karawasa, a new tinyint column will need to be created after column ip in match_data.

`SELECT a.steamID, a.id FROM player_data a RIGHT JOIN (SELECT steamID, MAX(score) max_score FROM player_data p LEFT JOIN match_data m ON p.matchID = m.matchID WHERE m.version = '".VERSION."' and m.mode = ".$lb." and m.whitelist = 1 and cheat = 0 GROUP BY steamID) b ON a.steamID = b.steamID AND a.score = b.max_score ORDER BY score DESC;`
