### ISSUE TITLE
Need for public versioning

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#255]
We have our internal B-Day-Month-Year system which works fine, but I think after seeing how the balance changes & leaderboard resets are going, we should start making public the version each game was/is played. Things like "I made 500k points in ETD" don't have that much of a claiming value when you can't refer to an specific version of the game.

We have various choices:
1. Show the _B010316b_ string and let people figure out.
   - Easy and lazy solution, but it doesn't look pretty and its hard to remember/write down
2. Replace the internal version numbering for a traditional versioning system X.Y / X.Y.Z
   - I guess this isn't going to work either because of DB limitations? That was the reason of our current build version if I remember correctly
3. Add the versioning system in addition to the internal numbering
   - The internal number could be treated as a "Build Version" like Dota has (we are currently in [Client Build 1323 according to steambox](https://github.com/dotabuff/d2vpkr/commit/71d7a75bfb60ccadbe83c3cf901283866413bc09)) while the balance version is advertised under a fancier value. Then we just need to keep a translation list of the dated-build string in order to replace "B010316b" for "1.0" or whatever style we go for!

We can formalize a "1.0" version after we get rid of the last remaining bugs and stabilize the game balance for good.

**Comment by ynohtna92** [comment]
Go with 2. And just make sure that we track version dates somewhere (change logs). There are no database limitations, it is just easier as a developer to know the date of the last major change when reviewing through screenshots or videos.

We are on 1.1 now?

**Comment by MNoya** [comment]
Not even 1.0 yet I'd say lets get rid of some bugs and call the other versions Beta

**Comment by ynohtna92** [comment]
I have made an alias on the view for the beta version numbers so no database changes need to be made. So 'B230216' becomes '0.9' and 'B010216b' -> '0.9'
