### ISSUE TITLE
Scoring System Revamp

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#260]
- [x] Remove the score modifiers from **Chaos & Rush Modes**. They're just for fun.
- [x] Keep the **Speed & Clean Wave Bonuses** as they are, just kill the consecutive multiplier. So if you don't leak, you get *1.2 per wave, and for speed, you can get up to *1.3 per wave, depending how fast you kill it.
- [x] Should you finish the game (beat **Wave 55**) include a **Networth Bonus**, equal to your **Networth/Base Networth**. Aka, what **Express** has built in.
- [x] For the frog wave, drop the score multiplier from wave to wave back down to 10%, down from 20%.

**Comment by MNoya** [comment]
Need new values for Express and reasoning behind nerfing frog wave scaling

**Comment by Karawasa** [comment]
We should revert frogs to 20%. Express values remain the same. Classic networth base is;

Normal 60805
Hard 79445
Very Hard 90861
Insane 103951

**Comment by MNoya** [comment]
Close this after playtest, it's fully implemented for now

**Comment by MNoya** [comment]
Also @Karawasa @WindStrike72 should we also remove negative scoring for speed?

**Comment by WindStrike72** [comment]
For now, no. Gonna need to test it out.

**Comment by WindStrike72** [comment]
Overall speed bonus:
- Average time for **Classic** is 40 minutes. You get a multiplier bonus equal to **1 - (40 Minutes / Your Time)**
- Average time for **Express** is 20 minutes. You get a multiplier bonus equal to your **1 - (20 Minutes/ Your Time)**

To clarify, this should be at the same time you get the **Networth Bonus**, so after beating Waves 55 (Classic) and 30 (Express).

**Comment by MNoya** [comment]
Currently **AverageTime/EndTime - 1** and multiplicative with Networth bonus (I feel it should be additive but just need to run the math and playtest how it goes)

Edit: Additive updated.
