### ISSUE TITLE
New Creep Types

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#261]
- [x] **Avenger**
  - When it dies, it drops a 5 second, stacking debuff (each debuff has separate timers, like **Flame Tower's** attack). Said debuff decreases the damage and ability damage of all towers in a 550 AoE around it by 5%.
  - I was gonna call it **Vengeance**, but it'd stretch across the whole screen. Thinkin' maybe **Vengeful Spirit's** aura for the icon.
  - Covers the following **Waves:** 10, 17, 24, 29, 34, 42, 49
- [x] **Bulky**
  - Spawns at half the rate (every 1 second instead of 0.5 seconds), half the total count (15 instead of 30).
  - Each creep has double bounty and x2.5 HP (effectively a 25% hp increase over a standard wave).
  - Suck it, AoE.
  - Covers the following **Waves:** 6, 12, 21, 31, 40, 44, 48

**Comment by Karawasa** [comment]
Updated revenge to 2.5 seconds.

**Comment by MNoya** [comment]
Icons:
![vengefulspirit_command_aura](https://cloud.githubusercontent.com/assets/401423/13500805/e3d650d0-e142-11e5-9ec2-afa7a45e7f22.png)
![pudge_flesh_heap](https://cloud.githubusercontent.com/assets/401423/13500796/d5dc0b3c-e142-11e5-9fe0-d3778693c5bc.png)

**Comment by Karawasa** [comment]
First one.

**Comment by Karawasa** [comment]
Nice.

**Comment by vladmarica** [comment]
I think Vengeance can still fit well enough in the UI. It's not like Regeneration, haha

**Comment by MNoya** [comment]
Regeneration
Vengeance
Revenge
Avenger

We have:
Undead
Healing
Regen
Shield
Bulky
Fast

Vengeance is pretty long in comparison, but I'll try it

**Comment by Karawasa** [comment]
Please note the following change;

Wave 54 should be fast
Wave 6 should be bulky

**Comment by MNoya** [comment]
Bulky creeps in Classic:  6, 12, 21, 31, 40, 44, 48
- wolf (earth)
- raccoon (nature)
- crimson_demon (fire)
- sea_phantom (water)
- death_gazer (composite)
- balthazar (dark)
- crystal_apparition (light)

We should probably change models for those, something that looks more _bulky_

**Comment by Karawasa** [comment]
Or just rename bulky to tough. Prefer not to change models at this point (we are quite limited already).

**Comment by Karawasa** [comment]
Buffing avenger to 5 seconds. Can nerf if playtest reveals it to be too strong.

**Comment by MNoya** [comment]
Adding behavior to Vengeance debuff: Can't sell or upgrade while its active

After further discussion:
AoE location: On tower that killed the creep
Radius: 250 (hits up to 6 towers) http://puu.sh/nuMsl/f0b00e8800.jpg

**Comment by WindStrike72** [comment]
Ooooooh that's gonna cause some rage. Whelp, let's... try it... pretty sure that's over the top.

**Comment by vladmarica** [comment]
I didn't get enough progress on Vengeance creeps as I thought I could, sorry. I'll be gone for the next few days so someone can finish it if they'd like.

What needs to be done:
- Killing a vengeance creep applies the debuff to the tower that killed it
- Make the debuff lower the tower's damage per stack 
- Debuffed tower cannot be sold
- Chinese localization

**Comment by MNoya** [comment]
The abilities are now ready to playtest & balance.

I left a debug draw for testing radius on Vengeance:

![img](http://puu.sh/nvRD5/4e3f63c724.jpg)

You can see it hits towers separated by up to 2 grid cells

![img](http://puu.sh/nvRG6/115c45ba16.jpg)

A tower needs to be at least 3 grid cells away to not get hit by the debuff on the killer with the current 250 radius.

**Comment by MNoya** [comment]
Actually I'm missing the Sell/Upgrade interaction, I'm thinking it would be better if Upgrades just carry the debuffs instead of preventing the upgrade completely, but let me know after testing

**Comment by WindStrike72** [comment]
If the upgrade can carry the debuff, that'll work. It doesn't need to prevent sell cause by the time you build the tower back up, approx. 5 seconds have passed, give or take. Surprisingly... it seems balanced, buuuuuut then again I naturally play by spreading my defenses out. I'll try a game where I focus my defenses.

Bulky is scary. In a good way.
