### ISSUE TITLE
Express Mode Waves

### ISSUE THREAD

**Issue by Karawasa** [Karawasa/Element-TD#262]
All instances of shield creep should be replaced with fast creep (so same element, different model/ability).

All instances of normal creep (3, 6, 11, 15, 19, 23, 26) should become Undead (so same element, different model/ability).

**Comment by MNoya** [comment]
Shield creeps (aka Mechanical)
- battleship (water)
- dreadlord (dark)
- gaias_titan (nature)
- goblin_shredder (composite)
- holy_bomber (light)
- inferno_golem (fire)
- rock_monster (earth)

Fast creeps:
- lightning_angel (light)
- murloc (water)
- nether_spider (dark)
- satyr (composite)
- torchbearer (fire)
- elf_soldier (nature)
- centaur_warchief (earth)

Undead creeps:
- dust_fiend (earth)
- fire_acolyte (fire)
- immortal (light)
- shroomling (nature)
- skeleton (dark)
- turtle_rider (water)
- void_incarnate (composite)

**Comment by MNoya** [comment]
Waves will be a bit awkward in Express visually, wave 3 will now use the classic creep wave 43 and wave 8 will use classic creep 54. But I guess its better than start making new model/names just for looks.
