### ISSUE TITLE
Cancel + sell on building towers?

### ISSUE THREAD

**Issue by elklopso** [Karawasa/Element-TD#267]
When you upgrade a Tower there is a cancel and a sell button. Cancel gets Q as Button and Sell gets W. But if you have something like Roots tower normally there is Cast Roots on W . 
I had the problem that I wanted to set the Roots for the tower, but I accidently sold the Tower :(
So is it really important to have sell while building?

**Comment by MNoya** [comment]
You're right. I will remove sell while constructing, it's not usable during that process anyway, and the Cancel should fill that need.
