### ISSUE TITLE
Add confirmation when a match is succesfully recorded at end screen

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#268]
Seeing this will confirm the players that their match was properly received for leaderboards.

**Comment by ynohtna92** [comment]
Not running the js function correctly on the end scoreboard. It runs however it does not display the css, unless I manually call the function.

**Comment by MNoya** [comment]
I think the problem is end screen isn't created until the post game hits, so maybe the subscribe doesn't register until the event has already been triggered. I'd do a nettable storing match recorded yes/no and just make the end screen read that value on a schedule
