### ISSUE TITLE
Version Label

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#270]
Version should be visible somewhere ingame.

Maybe on bottom left, just over the minimap? We could place a leaderboard button there too (pulling the latest steamID-name-score list of Classic / Express depending on what mode they are playing)

**Comment by elklopso** [comment]
What about the Scoreboard? It would also be nice to see the mode there :) When you spectate a game you don't see the trophy in the bottom right :)

**Comment by ynohtna92** [comment]
@elklopso I will add the version and steam match ID to the match page of the leaderboard.

**Comment by elklopso** [comment]
<3

**Comment by ynohtna92** [comment]
It has been added to http://hatinacat.com/leaderboard/matches/6085652, the replay ID will appear under the match ID once it becomes available to us. The version can be viewed by hovering over the match ID with the mouse.

**Comment by MNoya** [comment]
Version takes like a full second to show up when hovering for me, is that intended? I think it could be made part of the match_secondary div, visible at all times. Now sure why Dotabuff doesn't do this, reviewing some of my old dota matches is very hard knowing at which version where they played

**Comment by MNoya** [comment]
Ingame view:

![img](http://puu.sh/nuAbm/d923ead63b.jpg)

(Working with minimap on the right)

**Comment by ynohtna92** [comment]
Why not have it over the minimap in the bottom black section and then have the eletd logo in the top black bar?

**Comment by MNoya** [comment]
Good idea
