### ISSUE TITLE
Sandbox Games in profiles

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#271]
http://www.eletd.com/leaderboard/players/39892871 the 2 elementless games are sandbox mode

Since we only show games won in the player profiles, and it's possible to win games on Sandbox (even without going to the last wave, just by pressing the End button), we should either skip all the games that are detected as cheats, or can easily make all games in sandbox count as a defeat (it will show YOU LOST! at the endscoreboard which isn't as good as just handling it on the web imo)

**Comment by ynohtna92** [comment]
If you added Sandbox to one of the game variables, I can detect that and not display the tagged matches on the player history.

**Comment by ynohtna92** [comment]
I just made sure games with cheats are no longer displayed on the player page.

**Comment by MNoya** [comment]
Alright, closing this one then.
