### ISSUE TITLE
Build towers for free gold!

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#275]
Not sure what latest update did, lol, but when you select to build any of your single-elemental towers or composite towers, as long as you have at least enough gold to build said tower, it gives you the cost of the tower before you confirm building it. As in, well... you can just repeatedly press the tower buttons without actually building them just to get lotsa gold.

I'd say this only needs a very slight nerf.

**Comment by MNoya** [comment]
I see the problem, I changed a player call to fix an issue with reconnection, I'll just revert it
