### ISSUE TITLE
Add current waves-#creep indicator

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#28]
Specially useful for competitive mode

**Comment by Karawasa** [comment]
Yes. Good way to see how close someone is to screwing you over!

**Comment by MNoya** [comment]
I'm not really sure where/how to design this one, any ideas/mockups welcomed

**Comment by Karawasa** [comment]
I would put it in the scoreboard. Heading being "Remaining" which represents number of creeps alive in your area. Put this in place of "Kills" because that is useless until frog wave.

**Comment by Karawasa** [comment]
At frog wave, nuke remaining and put back kills.
