### ISSUE TITLE
Tweaks on Bulky

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#282]
Dear god this is the scariest creep type in the game without a doubt. So yeah, reduce health from 250% to 225%, but.... each creep should count as 2 leaks.

EDIT: Another tweak on that, it should count as two kills for life tower.

**Comment by MNoya** [comment]
Line to tweak is https://github.com/Karawasa/Element-TD/blob/master/game/dota_addons/element_td/scripts/npc/abilities/creeps/creep_ability_bulky.txt#L16

Note that if you change that, the tooltip still reads 'x2.5' on the Description field, so that must be updated as well.
