### ISSUE TITLE
Ingame Rankings & Player Profiles

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#287]
- [x] Display your ranking at the start of the game
- [x] List the Top leaderboards for Classic, Express and Frogs f561b43ef0e84576301a01fda850f222be9e2b5d
- [x] List your friends rankings and percentiles
- [x] Stats Info
- [x] Matches
- [x] Milestones
- [x] Custom profile hover style, replacing the Dota avatar hover

**Comment by ynohtna92** [comment]
API for top leaderboard (normal, express, frogs) positions and friends ranking can be found described at http://hatinacat.com/leaderboard/changelog.txt

**Comment by MNoya** [comment]
Need rankings to send your own score so we can show it on the new player profile

![img](http://puu.sh/nHEzC/11ce8b62db.jpg)

**Comment by ynohtna92** [comment]
Did you increase percentiles by 1?

There already is an api to request a single player.

I will make another one that will run through all matches played and grab stats. Just tell me what you want to display and ill code it tonight.

**Comment by MNoya** [comment]
> Did you increase percentiles by 1?

Yes, I was getting 0%

> There already is an api to request a single player.

Sure but I didn't want to send an extra request all the time. I just took it from rankings now and stored all in a nettable

We want to display everything we can, as the player profile might/will be one of our premium features

**Comment by MNoya** [comment]
One particular thing we need is splitting Game Clears (I think this is what we call Wins) from PvP Wins

**Comment by ynohtna92** [comment]
Percentiles should be left alone and are not required to be increases. I assume that player friends ranking window also scrolls? What is the difference of player wins and PvP wins?

**Comment by MNoya** [comment]
Player wins is games completed regardless if they are the top score (basically all single player games, and all multiplayer games where they reach the end)

PvP wins is winning vs 2 or more players.

I didn't implement scrolling yet but should be easy, I only restricted it to top 10.

**Comment by ynohtna92** [comment]
I just added a new API call for player stats. Easier this way. 
http://hatinacat.com/leaderboard/data_request.php?req=stats&id=66998815
Described at http://hatinacat.com/leaderboard/changelog.txt

Percentages for difficulty or element counts will have to be calculated manually by added them together.

**Comment by MNoya** [comment]
Excellent.

6932b55835608389c98b8733b7fc257fef9062b7 just increased the top leaderboard ranks to 100 with scrolling, works very well after some tweaks to the rate the panels were created. I need to apply the same to the player profile and add the new stats for the player

**Comment by MNoya** [comment]
Replaced left Rank with the actual Friend-Ranking, replaced the Percentile column with "Global".

I'm not sure if we should have the own-profile entry mixed with friends, I think we should in order to show 'you are 3rd of your friend rankings', that's the reason why I wanted friend rankings to have the player data directly. I can add it to the received payload in js quite easily though, the stats APi works well

**Comment by MNoya** [comment]
`friends` request accepts steamID64 while stats needs 32 bits. I am only gonna handle this stats in client side so might as well make both 64 bits if possible (player Avatars in Panorama must have a 64bit `.steamid` field)

Edit: Scratch that, its working now. Both take 32 bits properly

**Comment by ynohtna92** [comment]
API for stats has been updated to include milestones, daily, weekly, monthly, version stats as well as raw match data for further processing.

Details available at http://hatinacat.com/leaderboard/changelog.txt

**Comment by MNoya** [comment]
One thing I forgot to ask for: `GetRank(steamID32, 2, "FrogsRank")` (currently only classic and express implemented). Same for friend ranks

If you want, nuke all `B230216` and rename `B010316b` as 0.9 (I will do so in the js backend)

**Comment by ynohtna92** [comment]
Why nuke it? People want to see stats since launch. I alias B230216 to 0.8 and B010316b to 0.9 on my front end. Which api calls do I need to add frogs to?

**Comment by MNoya** [comment]
- `friends&lb=2`
- `player&ids=XXXXX&lb=2`

Basically player frog rank and friend list with frog leaderboards

**Comment by ynohtna92** [comment]
> - `friends&lb=2`
> - `player&ids=XXXXX&lb=2`
> 
> Basically player frog rank and friend list with frog leaderboards

This has been already added if you were not informed.

**Comment by MNoya** [comment]
I wasn't aware yet, I'll add em next, profiles should be wrapped up this weekend.

**Comment by ynohtna92** [comment]
Just some things I noticed with the profile UI when I was playing around with it.
- [x] Click sounds for the UI elements (leaderboard, sandbox, profile, etc). Titles in the window should have their own click sounds (see what valve are using).
- [x] More hover tooltips for chaos, rush, etc (showing percentage of games played)
- [x] On hover over the element pie graph, make the saturation of everything black/white except the selected element.
- [x] Friends ranking should not load every time when you select though the leaderboards. It should load once and that is it, Maybe every 10 mins load it again.
- [x] Scrolling should be disabled for the camera when scrolling in a window.

**Comment by MNoya** [comment]
@ynohtna92 I think player stat request is missing the required info for me to position the self-player on the friend rankings.

This info is an array of the form: **{steamID, score, rank, percentile}** for any of the 3 leaderboards.

If the friend leaderboard request could just have the own player rankings included for that particular leaderboard, we wouldn't need to do any extra handling.

**Comment by ynohtna92** [comment]
Stats does have ranks for leaderboards under rank_<leaderboard name> (rank_exp, rank_frogs).

The player who is requesting the friends rank is now given under 'self' in the json result.

**Comment by ynohtna92** [comment]
Loading Icon css

```
#Loading.Hidden
{
    visibility: collapse;
}

#Loading
{
    width: 30px;
    height: 30px;
    vertical-align: middle;
    margin-right: 13px;
}

.Spinner
{
    width: 28px;
    height: 28px;

    background-image: url("s2r://panorama/images/status_icons/loadingthrobber_round_psd.vtex");
    background-repeat: no-repeat;
    background-position: 50% 50%;
    background-size: contain;

    animation-name: SpinnerRotate;
    animation-duration: 1.0s;
    animation-timing-function: linear;
    animation-iteration-count: infinite;
}

@keyframes 'SpinnerRotate'
{
    0%
    {
        transform: rotateZ( 360deg );
    }


    50%
    {
        transform: rotateZ( 180deg );
    }

    100%
    {
        transform: rotateZ( 0deg );
    }
}

```

**Comment by MNoya** [comment]
In friends request, frog leaderboard 'score' should be the frog kill count (or another field, but ideally just a score override)

**Comment by MNoya** [comment]
Milestones added and styled b37aaa03d598f2a4cef2cca09e140e438589886e

**Comment by MNoya** [comment]
@ynohtna92 we will need a match request API at some point. I intend to finish the custom builders next, which will require another request very early on game start to know which model to swap to. We can send this info on each match when the game ends, as a "hero" field (wisp default, phoenix custom, then the new 6 builders will be implemented as their own hero most likely). This way, the builder to use is know from the last match played. Unless you know a better way (perhaps a dedicated request just for getting the builder at game start?)

**Comment by ynohtna92** [comment]
How about for the custom builders I make a store and retrieval system for any data you want. I'll just add more rows when we need something else.

Might not be able to do it till the weekend so for now just implement it without the selection loading.

**Comment by MNoya** [comment]
That sounds great! I have almost finished the builder picking UI but was set back due to internet connection loss, will be pushing it as soon as I regain it

**Comment by ynohtna92** [comment]
The badge pop down no longer is working with the latest dev build.

**Comment by ynohtna92** [comment]
'match' API call has been added and is described here http://hatinacat.com/leaderboard/changelog.txt
