### ISSUE TITLE
21:9 UI Bugs

### ISSUE THREAD

**Issue by Karawasa** [Karawasa/Element-TD#289]
See the pic. In-game ranking floats around. Always same relative position so gets annoying. Upcoming wave info moves around with camera.
![bug](https://cloud.githubusercontent.com/assets/7691068/13595178/d3d5ad9a-e4ce-11e5-8249-446bf698051b.png)

**Comment by ynohtna92** [comment]
What am I looking at?
The silver badge ranking? Does it not disappear when it is meant to? It should only show when you over under the player top bar position.

**Comment by Karawasa** [comment]
It does not disappear like you mentioned. Wave info does not stay put between portals.

**Comment by MNoya** [comment]
How do you test 21:9 ?

**Comment by ynohtna92** [comment]
Set your width and height to this value https://github.com/Karawasa/Element-TD/blob/master/content/dota_addons/element_td/panorama/scripts/custom_game/resources.js#L118

**Comment by MNoya** [comment]
- [x] new interest positioning

**Comment by MNoya** [comment]
@Karawasa still waiting on an image in order to fix your interest positioning. Reopen this when you get it
