### ISSUE TITLE
Scoring Updates

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#295]
- [x] Points per frog reduced from 250 to 200 (regretfully)
- [x] Clean bonus buffed from +20% to +25%
- [x] Speed scaling per wave changed to -3% per second, from a max of +45% and down to a minimum of -100%, though I personally find it hilarious to actually lose points from leaking the same wave twice, lol
- [x] Increase the point values of all creeps by 10. So instead of Wave 1 being a value of 1 score per creep, they'd be a value of 11 score per creep. Likewise, Wave 55 would be 65 per creep instead of 55.

**Comment by MNoya** [comment]
Speed changed to -1.5% and +3% instead after some reconsideration

**Comment by Karawasa** [comment]
Change points to +5 on classic. Change points to +3 on express.

**Comment by Karawasa** [comment]
Change speed to -1% for over 30 seconds.
