### ISSUE TITLE
Single Player restart

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#296]
Featuring full reset of every object on the game.

This has to be handled with extreme care due to the nature of many objects which weren't planned to be restarted.

**Comment by Karawasa** [comment]
Very low priority on this one.

**Comment by MNoya** [comment]
Initially to be added on Sandbox
- kills all towers
- set life to 50
- set gold to starting gold (normal/express)
- reset all element to 0 and give a lumber to the player (normal/express)
- reset score to 0
- set spawn level to 1
