### ISSUE TITLE
Deprecated content

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#3]
Apart from every Scaleform interaction, this are the things in use that must go away:
- [x] addon_init.lua
- [x] dafuqs going on in addon_game_mode.lua
- [x] every `SetContextThink` 8502a48bd2ea3b994d56fb857573a72eab4879ec
- [x] global dummy caster 896cf04f49e190b06b718d091c4670d7552d5269
- [x] proper timers `CreateTimer` 54893f3188dbaaf376e0ec15da3048d3193f04f6
- [x] PhantomManager.lua
- [x] `commands.lua`
- [x] Pages system. Just use items or a custom UI for the builder.
- [x] `script_reload` issue

**Comment by vladmarica** [comment]
Removed global dummy caster https://github.com/Karawasa/ElementTD/commit/896cf04f49e190b06b718d091c4670d7552d5269

**Comment by MNoya** [comment]
createClass doesn't `script_reload`, we should get that fixed or move towards RunScripts to begin fixing the tower issues

**Comment by vladmarica** [comment]
So when you run `script_reload`, it doesn't reload tower scripts? I think we can get around this...

**Comment by MNoya** [comment]
Yeah I think it'll just be adding DynamicWrap on the tower class registering

**Comment by vladmarica** [comment]
Want to try that? If that doesn't work, I'll just add some `-rebuild_classes` command which deletes the old tower script object and replaces them with new instances.

**Comment by vladmarica** [comment]
What are the remaining issues with `script_reload`?

**Comment by MNoya** [comment]
We gucci, full sail ahead
