### ISSUE TITLE
Cooperative Mode

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#300]
Private design thread: http://forums.eletd.com/topic/95454-co-op-map-mode
### Core features left to do:
- [x] Balance
- [x] Fix stats sending (check http://hatinacat.com/leaderboard/players/coop)
- [x] Fix wave 50/51 ending and interest stopping early
- [x] Don't keep showing non-leaked world panels
- [x] Fix orientation of elemental trophies
- [x] Review scoring #372
- [x] Finish leaderboard adjustment
### UI
- [x] Coop loading screen change
- [x] Loading screen change on coop with new map style/layout
- [x] Add advertisement on loading screen classic
- [x] Leaderboard change (dont show classic map scores)

---
### Done
- [x] Fix Interest ticking early
- [x] Fix lives lost tracking
- [x] Fix leaks to be tracked per each lane
- [x] Fix incorrect precache sequence
- [x] Fix abandon
- [x] Add 6 new portals and set constants (end positions, sectors, spawn points, etc)
- [x] Handle wave spawns as a team
- [x] Handle breaktimes as a team
- [x] Different setting for max creeps
- [x] Opposite settings for leaks (leak starting from the other side's End Point then Spawn Point)
- [x] UI - Remove lives/remaining/score for players on the Scoreboard
- [x] UI - Remove Rush as a voting option
- [x] The less players there are, the more gold everyone starts with
- [x] Gold for killing creeps is split evenly
- [x] Interest is split evenly based on team gold
- [x] Increase default view distance
- [x] 100 Lives
- [x] Players should spawn scattered around the map, to give them decent starting areas should they not know where to build.
- [x] Increase builder movement speed to 1000.
- [x] Summon elements express-style.
- [x] For the co-op leaderboard, for listing the players, since there's not enough room for their names, show only their avatars initially, and then upon clicking into the Match ID, it'll show the avatars + names.
- [x] Fix portals
- [x] Fix random
- [x] Fast: x2 Speed (600), standard speed
- [x] Winner is a team instead of a single player (You Win!)
- [x] Don't revive / spawn after game ends
- [x] Handle scoring as a team. Fast is 20 seconds, rest same as classic
- [x] Frog scoring
- [x] Share units and hero control for abandoned players
- [x] Item Grid performance and team behavior
- [x] When you select an allied tower, show yellow indicator
- [x] Fix portals overlapping
- [x] Fix voting height
- [x] Use player colors on scoreboard instead of team colors
- [x] Add "Leaked: N" worldpanel on each lane
- [x] Adjust trophy areas
- [x] Improve middle portal
- [x] Add direction arrows
- [x] Fix Pathing on nature entrance
- [x] Update player positions

**Comment by MNoya** [comment]
Started in a33d7cfbfbc976d28657e63a6630fcd42b24f8d7

Adding ToDo List

**Comment by WindStrike72** [comment]
Added some more input

Still looking into the targeting UI thingy.

**Comment by MNoya** [comment]
@ynohtna92 in addition to the PvP/Solo Wins tracking, we will also want to track the number of Coop Wins

**Comment by ynohtna92** [comment]
We will use this to store the game type (https://github.com/Karawasa/Element-TD/blob/master/game/dota_addons/element_td/scripts/vscripts/statcollection/schema.lua#L52)

0 - Normal
1 - Express
2 - Coop
~~3 - Express Coop~~

**Comment by MNoya** [comment]
Tower changes required:
- [x] Life Tower (team lives)
- [x] Gold Tower (split gold)

**Comment by MNoya** [comment]
Went on the first multiplayer run with a helpful tester, some things to fix:
- [x] Top bar avatars not showing for other players
- [x] Portal panels only show once
- [x] Handle game losing http://puu.sh/odLVz/914c34b1b8.jpg
- [x] Cannon tower particle seems to have unattached childs, playing on origin
- [x] Scoreboard elements aren't hiding for 2nd player http://puu.sh/odMEw/fbdb41f768.jpg

As for Balance... we played 2-man in Normal and got decimated at wave 11, the game might need increased gold bounty on creeps. Waves leak very fast and there's not much room for error on early game with the current 1k gold base split per team member

**Comment by ynohtna92** [comment]
When sending stats for co-op games the following needs to be true.
- score, wave, icefrog_kills, cleared, duration, difficulty, type, health, boss_wave, clean_waves, under_30_waves, rand (depending on how you do random for players) will need to be the same for all players in the game. I will be reading for the first player with a matching matchID from these rows for game data instead of storing the data in the match table.

This is pretty much the only requirement I require to getting the coop leaderboard working.

**Comment by ynohtna92** [comment]
How will the Co-op leaderboard be ordered? Since the same 4 people can play co-op together over and over again, it is possible for them to fill up the leaderboard with there games. That same player could also play with other people and again get a highscore so it is not possible to just list the best team score for a player if they play in multiple teams as each game is equally unique. Should duplicates only be considered for games with exactly the same players?

**Comment by MNoya** [comment]
> Should duplicates only be considered for games with exactly the same players?

I think so. Also instead of Player: [Avatar] Name, we would just have 4 Avatars near the match ID. Small change I'd recommend is making the hover-avatar name popup instant, currently it waits for like half a second before showing the name.

**Comment by MNoya** [comment]
@ynohtna92 for the coop leaderboard request, `&lb=4`? I'll change the ingame leaderboard to show coop top 100 instead of the other 3 lbs.

Also, make sure that Frogs stay classic only

**Comment by ynohtna92** [comment]
> Small change I'd recommend is making the hover-avatar name popup instant, currently it waits for like half a second before showing the name.  

That is how the titles works for html, I could tipsy which uses javascript (it is what github has for their hovers).

> coop leaderboard request, &lb=4?  

Yes, but for other request, it will be 3. I'll update it so they are all the same soon.

**Comment by MNoya** [comment]
This is now the focus for next release in the next week.

**Comment by ynohtna92** [comment]
Bugs to fix:
![image](https://cloud.githubusercontent.com/assets/2245318/14578881/147ae598-03da-11e6-83a4-f954cc85f103.png)
- [x] Dead wisp on start of game (see on minimap as well)
- [x] ElementTD/Version overlays will need repositioning for coop
- [x] Grid overlay will not regenerate if another player removes a building on it.
- [x] Fix scoreboard and top bar

Mapping:
- [x] Increase contrast between lanes and building platforms (hard to distinguish without grids turned on), This should also affect the minimap image
- [x] Maybe rethink how split zone platforms are done, looks messy at the moment with half and half.
- [x] ~~Use the destruction mapping tool for the map edge to make it look cleaner.~~

**Comment by WindStrike72** [comment]
More stuff:
- [x] **Bug:** Sometimes, lives would drop down to a max of 50 and then back up to 100.
- [x] **Bug:** Random doesn't work properly. After the first element, you end up having to pick all your elements. BUT, later, I got random'd a **Pure Essence**.
- [x] **Balance:** Drop creep movespeed down to 230, increase spawn time interval to 0.65 seconds.
- [x] **Balance:** ~~Increase break time between waves from 30 to 45 seconds.~~
- [x] **Balance:** Bump builder movespeed to 1600, so double speed of normal game.
- [x] **Visual:** It's not particularly obvious where the creeps go until you start losing. Mayhaps a more apparent visual for the portal in the middle?

Regarding the split build platforms, while they are cool, they were rather difficult to tell what was what, especially in **Light/Dark** land. Perhaps some sort of texture/color that's in-between the element colors for any platform that's got a mix of both.

**Comment by WindStrike72** [comment]
When you select an allied tower, it gives the impression that it's mine, because the only thing difference about it is when I try to select any of the buttons, it deselects the tower. So in addition to the yellow range indicator, could we have the icons greyed out for ally selection?

**Comment by MNoya** [comment]
> could we have the icons greyed out for ally selection

I could put an overlay on the item and ability bar section but ugh, its gonna look quite bad.

Perhaps we can show a small UI with:
- Name of teammate
- Button to "Remove [This tower]" with a ping
- Button to "Upgrade [This tower]"

**Comment by WindStrike72** [comment]
- [x] Nuke Same Random
- [x] Remove Chaos Mode from voting screen and force it to be on by default
- [x] Voting Screen should just be difficulties + All Pick / All Random, so reduce the voting time to 30 seconds
- [x] Add Bulky Creeps back, should affect what's normally waves 1, 2, 3, 5, 7, and 28, aka all the waves with no ability.

**Comment by WindStrike72** [comment]
Scratch the movespeed/interval alteration, back to 300 and 0.5 seconds. Instead, run different difficulty hp scaling:
- Normal: 100%
- Hard: 120%
- Very Hard: 140%
- Insane: 170%

**Comment by WindStrike72** [comment]
Scratch different difficulty hp scaling; instead, drop base HP for co-op from 75 to 60. Also, need a different hp scaling starting wave 41.

Also, 6-ele random suuuuuucks- ignore that.

EDIT: So according to the bullet point above, the break time between every 5 waves (aka element pick) says it was updated to 45 seconds, but it's still 30 seconds in-game.

**Comment by MNoya** [comment]
@WindStrike72 Changed the 5waves back to 30 seconds because it felt really really slow (there is no elemental boss)

**Comment by ynohtna92** [comment]
> For the co-op leaderboard, for listing the players, since there's not enough room for their names, show only their avatars initially, and then upon clicking into the Match ID, it'll show the avatars + names.

Has been done on hatinacat for a while now. The only thing left is to display the ranking of the player on the player page.

**Comment by ynohtna92** [comment]
What is the eta for coop release? Still 1 million?

**Comment by MNoya** [comment]
Next week (28~29 April) at the latest. Version 1.6 should be up tomorrow!
Plans could change depending on this weekend's progress and whether we get a Dota 6.87 patch soon or not.

**Comment by ynohtna92** [comment]
Visually I think the map still needs improvements to better distinguish the lanes from the podiums. The borders will need covering up if they cannot be blended into the other zone texture. There are also some gaps in the map on the top left and along the left side of the map between the rocks that make up the boarders. @Azarak 
- [x] When the game ends and undead units are killed they will revive upon dying even if the team has no lives left.

**Comment by WindStrike72** [comment]
- [x] Ban 6-ele on random.

**Comment by WindStrike72** [comment]
Start the game from where wave 6 would normally be, meaning:
- [x] Starting gold of 500, up from 250
- [x] Start of 2 element picks for everyone, up from 1
- [x] Base Creep HP of 120, up from 60
- [x] Only 50 waves

That should be a little bit easier for everyone, cut down game length a bit, and give everyone more options from the start.

**Comment by MNoya** [comment]
I might have been using a bad formula. Oops

**Comment by WindStrike72** [comment]
- [ ] If possible, make **Cannon & Arrow Towers** (including elemental versions) 100% sell in All Pick.
