### ISSUE TITLE
Partial Frog Points

### ISSUE THREAD

**Issue by Karawasa** [Karawasa/Element-TD#302]
Currently, you only get frog points once you clear that particular frog wave.

Change it so that on the wave you die on, you get frog points for the frogs killed on that wave. This way, every frog kill gets counted!

**Comment by MNoya** [comment]
I see the problem, the function calculates the reminder but never adds it with 'extraFrogScore' https://github.com/Karawasa/Element-TD/blob/master/game/dota_addons/element_td/scripts/vscripts/scoring.lua#L264-L266
