### ISSUE TITLE
Time Lapse Creeps

### ISSUE THREAD

**Issue by Karawasa** [Karawasa/Element-TD#303]
I apologize in advance. 

Bulky creeps have ended up shifting the balance too far against AoE towers. So we need to undo them and replace with another creep type. That is going to be the time lapse creep.

When this creep is below 25% amount of health, it will time lapse 3 seconds back, restoring its health and position, one use per creep.

So that means new icon, normal model size.

**Comment by WindStrike72** [comment]
I should clarify, don't actually nuke the bulky creep type from the code and whatnot, we're gonna reuse it for a wars mode later.

**Comment by MNoya** [comment]
Ready to test and push the update when the numbers are confirmed to be stable

**Comment by Karawasa** [comment]
Reminder to add to boss sequence as last.

**Comment by Karawasa** [comment]
Quote from player;

The creeps are bugged. They are using Time Laps as soon as they got hit.

**Comment by MNoya** [comment]
I see the problem, fixing it now remotely. @WindStrike72 update the game if you can, I won't be able to do it for ~4 hours

**Comment by WindStrike72** [comment]
Kay, got some weird issue where time lapse creeps, no matter how long it's actually been, will go all the way back to the start with full hp. I have no idea what causes it.

**Comment by MNoya** [comment]
I see what can cause it, it's due to time frame rounding, I'll try to add some safeguards
