### ISSUE TITLE
Leaderboard names unable to show chinese/russian characters

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#305]
Currently a ton of "???" characters because of it.

**Comment by ynohtna92** [comment]
This should be fixed already if @Karawasa implemented my changes. It shouldn't be instantaneous as steam entires will only update when you navigate to the players profile once every 3 days. All new entires however should be using utf8_bin.

Example http://hatinacat.com/leaderboard/players/125874523
