### ISSUE TITLE
Express Picks

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#306]
Level 2 needs to be pickable as soon as Wave 6 clears.
Level 3 needs to be pickable as soon as Wave 15 clears.

**Comment by MNoya** [comment]
This should already be the case https://github.com/Karawasa/Element-TD/blob/master/game/dota_addons/element_td/scripts/vscripts/summoner.lua#L181-L189

I tried it on a solo lobby and it worked.

If it's not, its a bug, and needs a way to reproduce to fix it
