### ISSUE TITLE
Merge Erosion and Root debuffs

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#307]
The game has only 8 buffs/debuffs places and sometimes they take away so many of those

**Comment by Karawasa** [comment]
Not sure I understand this?

**Comment by MNoya** [comment]
Erosion and Root make multiple instances of debuffs so after you reach 8, it prevents other debuffs from showing (basically unneeded clutter)

Visually:

![img](http://puu.sh/nJSvY/673bb7388b.jpg)

**Comment by MNoya** [comment]
Now:

![img](http://puu.sh/nJXGL/6ef41b9969.jpg)

**Comment by MNoya** [comment]
Flamethrower should also have this
