### ISSUE TITLE
Hail Tower ability change

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#309]
This idea came from Karawasa:

Every X attacks, **Hail Tower** drops beams from the sky, hitting all targets in range. For visual, I'mma recommend the I5 Luna's Lucent Beam, Gold Version (since it is a Light tower), if possible. This would be separate from the main attack.

For the X, let's try out 10 to start with, and the beams deal the same damage as the tower, so 1000 / 5000.

**Comment by Karawasa** [comment]
Like a boss :).

**Comment by vladmarica** [comment]
Hey, take a look at it and let me know what you think. Still needs Russian and Chinese translations updated

**Comment by vladmarica** [comment]
Tower seems to be in good standing. Reopen this issue of you want further changes to it in the future.
