### ISSUE TITLE
Gray Icons

### ISSUE THREAD

**Issue by Karawasa** [Karawasa/Element-TD#31]
If you don't have the elements needed, gray out icon to indicate it's unavailable.

**Comment by MNoya** [comment]
I just realized this system [was already started](https://github.com/Karawasa/ElementTD/blob/master/game/dota_addons/element_td/resource/flash3/images/items/troll_warlord_fervor_disabled.png) so the boring legwork is done for the most part, it's only a matter of swapping the item upgrades whenever an element is acquired.
