### ISSUE TITLE
Electricity Ability Alteration

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#311]
Right now it's a bouncing attack that reduces by 20% damage per bounce. Have it also reduce the bounce range by 20% per bounce, and reduce base damage to 150. Obviously this'll require various amounts of tweaking.

EDIT: And no bounce limit.

**Comment by MNoya** [comment]
> reduce the bounce range by 20% per bounce

Bounce range is 550.

If it's based on the main value, it reduces 110 every jump:
550, 440, 330, 220, 110, 0. = 4 units hit max, super crappy

If its based on the reduced value:
550, 440, 352, 281, 225, 180, 144, 115, 92, 73, 59, 47 - Not sure how many targets are hit, and of course this would scale very well with slows.

**Comment by WindStrike72** [comment]
It should be the latter, aka scale with slows. So it acts just like the damage decrease.

**Comment by MNoya** [comment]
Total damage (25 jumps): 847

A jump limit might still be a good idea.

@WindStrike72  I haven't changed its base damage yet, I'll leave you to that
