### ISSUE TITLE
Fix eletd & hatinacat leaderboard saves

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#320]
Currently both servers are complaining they can't accept the payload

**Comment by ynohtna92** [comment]
Should do the trick https://github.com/ynohtna92/ElementTDLeaderboard/commit/f1d1ec96a4ef856d38b9f4abdbca8f3c059c4880

**Comment by MNoya** [comment]
GDS is back now and stats should be working

Hoping that @Karawasa db is accepting 64 bits, haven't heard from him on this yet.

Applying 1.3 patch
