### ISSUE TITLE
Pass Content

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#322]
- [x] Player Profiles #287
- [x] 6 custom builders
- [x] Custom Builder chooser panel
- [x] Voting Weight
- [x] Custom Builder save choice on db & request
- [x] Pass tracking on db
- [x] Pass player hover extra style
- [x] Inactive pass panel preview

---

Completely unintended issue number

**Comment by ynohtna92** [comment]
Can I just store builders with a number from 0-5? And how do we know what users have a pass? Do we have a list from volvo?

**Comment by MNoya** [comment]
We have a `HasCustomGameTicketForPlayerID` API in Lua and JS and we might get `GetGamePassExpiryTime` soon (I requested it in a email and DanielJ said he'll share the request)

**Comment by ynohtna92** [comment]
How do we validate the player when they save their builder? I assume server whitelist and something else?

**Comment by MNoya** [comment]
What's there to validate? The panel will only be available to pass owners. When they click the builder button panel, it replaces it. When the match end, we send the data of the player? We could send it every time the player changes builder but that's perhaps more charging on the servers .

**Comment by ynohtna92** [comment]
End of the game works. However if the game ends early then people may wonder why it didn't save :S

**Comment by ynohtna92** [comment]
Pass tracking and custom builder saves are completed on the database side.

**Comment by MNoya** [comment]
It's almost done guys! Just missing more work on the preview "inactive" version

@ynohtna92 not necessary for release but I'd still like to have a match request API so I can make an extra menu with advanced data when hovering/clicking on a match.

Also for the preview, I've setup one of my smurf accounts with the "Element TD" profile name, figured for the friend leaderboard it would be nice to pull some real data. @WindStrike72 @Karawasa and the rest have received a friend request from this account, and would be nice if you guys could have a real rank on Classic/Express so this request retrieves valid info :)

**Comment by ynohtna92** [comment]
What other information do you need to the match request API, you have pretty much everything with the raw argument.

That is dumb, just hard code it otherwise we will need to make sure all our accounts have a rank for every patch otherwise nothing will show.

**Comment by MNoya** [comment]
I still needed the account to update DOTAAvatarProfile and DOTAUserName panels (I'm not making diferent panels for this crap). I'll hardcode the friend data so that we don't need a request and always show ranks properly.

raw argument doesn't seem to show the other players in the game to build the full match page

**Comment by MNoya** [comment]
New to add:
- [x] allTime versionTime ~~dayTime~~ weekTime monthTime
