### ISSUE TITLE
Tower Table sizing issue

### ISSUE THREAD

**Issue by vladmarica** [Karawasa/Element-TD#323]
![](http://i.imgur.com/GL9hboD.jpg)

Note that Tidal and Ephemeral on the right icons are squished. Also, the Earth row seems to be smaller than all the other rows.

**Comment by MNoya** [comment]
resolution?

**Comment by vladmarica** [comment]
16:9, 1920x1080

**Comment by MNoya** [comment]
Fixed in e8eeca4926bd705e830446156e9eef1dfff78000
