### ISSUE TITLE
Yet more scoring changes

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#325]
Axe the Networth Score Bonus at the end of **Classic** (but not **Express**).

Nvm to the super clean finish bonus thingy.

Also, make all end-score bonuses multiplicative with each other instead of additive.

**Comment by MNoya** [comment]
I like that but keep in mind this will make everyone looking to highscore reset their game the moment they leak. Do we want that? I thought we were more towards frogs being the deciding factor of highscores

**Comment by WindStrike72** [comment]
Hmm, not necessarily. A lot of the highscores are not clean runs, though I can see it being a game of resetting a lot. Okay, nvm on the super clean finish thingy, I'll just adjust the individual clean wave bonuses a bit.

**Comment by WindStrike72** [comment]
Kay, nevermind axing **Networth Score Bonus**, just... for now, let's try making all the endscore bonuses multiplicative. Sorry for constantly changin' mah mind, testing ends up giving me different results than the theories.

**Comment by vladmarica** [comment]
@WindStrike72 is this done? If so, close this issue and let's release 1.4.

**Comment by WindStrike72** [comment]
Closed in commit [77629e4](https://github.com/Karawasa/Element-TD/commit/77629e4b2000ee4d10203958d14d6e460e40a102).

**Comment by WindStrike72** [comment]
Kay, bringin' this back, nuke the **Networth Score Bonus** in **Classic** only.

**Comment by MNoya** [comment]
Done this, test it up and reopen in case of any follow up

**Comment by WindStrike72** [comment]
Okee dokey, openin' this back up.

Bring back **Networth Score Bonus**, but it's a different formula (so old one would've gotten axed anyways). For every **2 Networth** you have, you gain **1 Score**, still applied after **Wave 55 / 30**.

Note that speed bonus multiplier still applies to the total, so it's your (Score + Networth Bonus) \* Speed Bonus.

**Comment by MNoya** [comment]
Done. Sounds weird but let's give it a try

**Comment by WindStrike72** [comment]
Seems to work well so far, closin'.
