### ISSUE TITLE
Improve tooltip format

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#33]
![img](http://puu.sh/mNnyZ/ec2cab68b3.jpg)

ToDo:
- The `Requires` and Element lines must match the Primary Element+Second/Third order visible on the ability icon.

Discuss:
1. Do we need "Requires" on the tooltips that are enabled (i.e. doesn't require anything else to build)?
2. Should the ability tooltip be on the very top of the description? What about the Damage type (if the Elements are in order, it would be redundant?)?
3. Should `X and Y and Z` be `X + Y + Z`?

**Comment by Karawasa** [comment]
1. No. If you have the requirements no need to list.
2. Nah I like where the ability is (since it's the most verbose). Also, damage type is fine to keep because some players might not realize the order.
3. X + Y + Z.

**Comment by MNoya** [comment]
Done in 1904b9e0afaa44f0cbb76e308d664c7a17b3256b
