### ISSUE TITLE
Show if a Top Rank has been achieved at game end

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#333]
We have this info through the leaderboard request, it should be possible to do a popup as soon as you die, showing that you got a highscore (or that you beat your former highscore for this version)

**Comment by ynohtna92** [comment]
What you can do is use the player stats with raw and analyse it there to see if a highscore has been achieved.  We cannot do a leaderboard highscore check live since the leaderboard updates every 5 mins but you can use existing pulled leaderboard scores to compare the end game score against those.

**Comment by MNoya** [comment]
I didn't do leaderboard top rank check but personal highscore check based on the ranking and percentile for killbanner particle purposes, I think it's good enough
