### ISSUE TITLE
Wave 1 is still worth 1 Score per creep

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#334]
As reported in [this post](http://forums.eletd.com/topic/95471-patch-1322/#comment-121391)

Just double-checked, you're only getting 30 Score from Wave 1 when you should be getting 180 (excluding the multipliers).

**Comment by MNoya** [comment]
In fact, all waves were broken...

This change is kind of a huge balance change. Please try it and take note of it on the changelog

**Comment by WindStrike72** [comment]
Checked it, looks good. Closing and adding to changelog.
