### ISSUE TITLE
Test Report - 3 Bugs

### ISSUE THREAD

**Issue by ghost** [Karawasa/Element-TD#34]
**_Bug 1:_ Infinite gold gains due to shift-queue building**

Pay attention to the gold before and after, in this video im basically shift-queue spamming a-ton of buildings while  hold is active, this is also doable WITHOUT hold but this allows me to click infinitely.
![](https://i.gyazo.com/980750894b99568106226e518ed0badd.gif)

---

**_Bug 2:_ Sometimes shift-queue buildings double builds**

---

**_Bug 3:_ Incorrect ability tooltips for some tower building**
Observed examples:
Nature Tower has 125DMG, but the tower building tooltip says 123
Light Tower has 125DMG, but the tower building tooltip says 83

**_I did not check all the tooltips._**

---

Irreproducible bug: I also managed in the process of spam clicking shift-queue to block the navgrid with no building ontop but I am unable to reproduce it.

**Comment by MNoya** [comment]
1 & 2 might have been fixed in some of the latest update, will check it out and update the workshop version. Thanks for the report :smiley:
