### ISSUE TITLE
Oh Hail no

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#343]
Could we have **Hail Tower's** 'shoot everything' shot have a range separate from its actual attack range? Say 2000?

**Comment by MNoya** [comment]
Yes it would be just changing the findRadius
https://github.com/Karawasa/Element-TD/blob/master/game/dota_addons/element_td/scripts/vscripts/towers/triples/HailTower.lua#L91

**Comment by WindStrike72** [comment]
Okay, that was nice an easy. What about showing its range indicator when hovering over the ability itself?

**Comment by MNoya** [comment]
Add `"AbilityCastRange" "2000"` in here:

https://github.com/Karawasa/Element-TD/blob/master/game/dota_addons/element_td/scripts/npc/abilities/towers/hail_tower_storm.txt#L10

The ability will also need an extra AbilitySpecial entry for tooltip and direct balancing, so I would just add it already and, in the AbilityCastRange value, you do `"%the_ability_special_name"` (and then in the code:

`self.findRadius = self.ability:GetSpecialValueFor("the_ability_special_name")`

#WeekendDotoModdingCourse :smile:

**Comment by vladmarica** [comment]
Has this not been finished in e6895e7 and c1966b6?

**Comment by MNoya** [comment]
It was, but I think we leave it open for a new balance addition: **Limit units hit** to 30 or so, because otherwise it is super broken for Coop.
