### ISSUE TITLE
Elemental Cannon/Arrow Towers

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#344]
IT'S HAPPENING! So, they should be 125 gold total (75 upgrade cost), x3 damage of the base towers, and then the respective elemental type. Annnd keep 98% sell on them.... we don't need a repeat of first half the game being cannon tower defense _cough_.

**Comment by MNoya** [comment]
![img](https://static-cdn.jtvnw.net/emoticons/v1/88/1.0)

This will be fun... I must check if there's enough models or I need to get creative
