### ISSUE TITLE
Toggle Attack

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#345]
So a bunch of people keep requesting this to stop getting arthritis for a use of a mechanic that's not even supposed to work that breaks the balance of the game, BUUUUT since it would tick people to turn it off, if we could have a Toggle Attack button (probably bound to S, which is what the majority of those people that do abuse it use), twould be cool. FYI, I'm not sticking this on Patch 1.5 Milestone cause it's low priority.

**Comment by ynohtna92** [comment]
How would this toggle attack button work? Switch to a different unit? Withhold all attacks?
