### ISSUE TITLE
Pass Icon too flashy and in the way

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#352]
As reported [here](http://forums.eletd.com/topic/95493-patch-15/?do=findComment&comment=121538), and I do agree with it, could we have it be capable of rolling into the side, similar to the **Sandbox Menu**?

**Comment by MNoya** [comment]
There is a small minimize button for this:

http://gfycat.com/WebbedAdorableGermanpinscher

**Comment by WindStrike72** [comment]
Derppity, straight up didn't see it. Nvm then.
