### ISSUE TITLE
Toggle behaviors on Impulse and Gold

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#355]
Of the towers with specific targeting behaviors, two of them have issues sometimes. **Impulse**, sometimes you want it to still shoot furthest targets, but actually focus it down instead of constantly switching, and **Gold** keeps wasting shots by hitting the same target when you have multiple. So, specifically for these two towers, could we stick a toggle on each of their abilities?
- On **Impulse**, toggle between "Shoot furthest, unfocused (default)", and "Shoot furthest, focused"
- On **Gold**, toggle between "Shoot lowest hp (default)", and "Shoot closest, focused", aka standard targeting behavior

**Comment by vladmarica** [comment]
@WindStrike72 Test it out and close this issue if you are happy with it.

**Comment by WindStrike72** [comment]
Gold works fine, Impulse's toggle behavior didn't do anything.

**Comment by MNoya** [comment]
Impulse works for me

Edit: Nevermind, it's not

**Comment by WindStrike72** [comment]
All good.
