### ISSUE TITLE
Camera Zoom

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#357]
It's super screwy when you zoom out a bunch, and then try to zoom back in. It thinks you're close up, so the fog blocks your view until you attempt to zoom back out just a little bit, but then it practically undoes your zoom in regardless of how much you zoomed in.

**Comment by MNoya** [comment]
Never happened to me but saw a couple of screenshots of people with the problem. Take a screenshot when it happens next time, do you have a way to reliably reproduce it, and need to find a way to do `r_farz 10000` on the clients

**Comment by MNoya** [comment]
Not fixed yet, probably an engine problem

**Comment by WindStrike72** [comment]
[Super zoomed out](http://prntscr.com/aub3sl)
[Super zoomed in afterwards](http://prntscr.com/aub43j)

Fog OP, pls nerf.
