### ISSUE TITLE
Axe higher tier names

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#360]
As brought up in [this topic](http://forums.eletd.com/topic/95492-tower-upgrade-names-unnecessaryconfusing-for-new-players/), just go with **Muck 2** instead of **Mire** and whatnot. Apply the same to the single-element towers as well, except the **Pure Towers**.

**Comment by MNoya** [comment]
I haven't changed the upgrade names and descriptions yet, does it also need to change or wanna keep the `Mire Tower`/`Upgrades this tower to a Mire Tower` text?
