### ISSUE TITLE
Switch Fire Tower ability to single-target

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#362]
Instead of Fire Tower's ability affecting everything it applies it, just have it affect the primary target. Don't worry about numbers, I'll get 'em.

**Comment by WindStrike72** [comment]
Oh yeah, apparently at 3 seconds, this ticks 4 times, I'm guessing there's an initial tick in there. Could we remove the initial tick?

**Comment by MNoya** [comment]
It ticks every 0.5 for half the damage, play with the duration if you want less/more ticks
