### ISSUE TITLE
Co-op interest ticking early

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#370]
Nothing shows up in console when it happens, it seems completely random, I've had it happen in both single-player and multi-player. However, the times I notice it happening the most are when a wave starts. I wanna say it might have something to do with the break times every 5 waves, but I can't really confirm that either.

**Comment by vladmarica** [comment]
Just to note that the ticking early appears to be visual only - your client being resynced with the server interest timer. The question now is how is it getting out of sync in the first place?

**Comment by vladmarica** [comment]
Fixed in 9881759
