### ISSUE TITLE
Stats on Coop

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#376]
Before we turn off the coop map as the default map, I'd like to see the result of some queries:
- [x] Pickrate of maps in the last days
- [x] Coop Winrate on each difficulty
- [x] Coop Wave lost aggregation (to graph which part is most difficult)

**Comment by ynohtna92** [comment]
https://getdotastats.com/#s2__mod_f?id=132 Pick rate of maps can be found here.

From my queries however I have aggregated the following results for you.

`SELECT * FROM`match_data`WHERE version = '1.7'`
`63171`

`SELECT * FROM`match_data`WHERE version = '1.7' and mode = 2`
`23040`

`Pickrate of maps for 1.7: 23040/63171 = 36.47%`

**Comment by MNoya** [comment]
What are those 75k matches in GDS, weekly?

1/3 of matches being coop is quite a success considering how easy it is to make a single player lobby

**Comment by ynohtna92** [comment]
True. I am going to upload the csv dump of the query 
`SELECT * FROM`match_data`md LEFT JOIN`player_data`pd ON md.matchID = pd.matchID WHERE version = '1.7' and mode = 2 group by md.matchID` 
 So you can do analytics of difficult and win/lost yourself. I'm not sure what win conditions are for coop.
[match_data.zip](https://github.com/Karawasa/Element-TD/files/253206/match_data.zip)

**Comment by MNoya** [comment]
wave > 50 or victory flag should be there too
