### ISSUE TITLE
Coop post-release requirements

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#377]
- ~~News entry on eletd.com~~ too late
- [x] ~~Update [workshop image](http://i.imgur.com/qVKtSxj.png)~~ and a top line for new Co-Op
- [x] Add the new leaderboard to http://www.eletd.com/leaderboard/ same as in [hatinacat](http://hatinacat.com/leaderboard/)
- [x] Add [russian workshop text description](https://github.com/Karawasa/Element-TD/blob/master/content/dota_addons/element_td/workshop_russian.txt)

**Comment by MNoya** [comment]
@Karawasa 3rd week's the charm? :smile:

**Comment by ynohtna92** [comment]
Email cli access whenever so I can update it. Here is a how to, remember to test it out to see if the new user has access to use mysqlimport, mysql, ftp, etc.

http://superuser.com/questions/149404/how-can-i-create-an-ssh-user-who-only-has-permission-to-access-specific-folders

**Comment by MNoya** [comment]
Both eletd and hatinacat leaderboards are down currently :disappointed:

**Comment by ynohtna92** [comment]
Please for the love of god grant cli access to eletd.com, the leaderboard has been down for 3 weeks.

**Comment by vladmarica** [comment]
3 weeks? How did something like this happen?

**Comment by MNoya** [comment]
Still waiting

**Comment by ynohtna92** [comment]
Getting ERROR 2006 (HY000): MySQL server has gone away which timesout the server. I have no idea what is causing it since all the timeout variables have been raised and it will still occur when importing the database. It also will crash the server which will need to be reset by @Karawasa. I suggest you contact AWS support @Karawasa as I cannot duplicate this issue to attempt to fix it on my end.

**Comment by Karawasa** [comment]
This was posted before I raised all the timeouts that you asked me for in your email...

**Comment by ynohtna92** [comment]
```
ERROR 2013 (HY000): Lost connection to MySQL server during query
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
```

The timeouts have not been raised on your server cvps8863561715. Did you reset mysql?
Can you contact AWS support and ask for advise?

**Comment by Karawasa** [comment]
Why not import one table at a time?

Date: Wed, 1 Jun 2016 00:37:38 -0700

**Comment by Karawasa** [comment]
Try again.

Date: Wed, 1 Jun 2016 00:37:38 -0700

**Comment by MNoya** [comment]
PogChamp
