### ISSUE TITLE
Ran into the gold cap

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#38]
Believe it or not, I ran into the gold cap of 99999 gold. Not just once either; my gold tower build is more than capable of reaching that number consistently in extra gold (and yet I still get roflstomped by Icefrogs). Is there a way to have the cap increased beyond 99999 gold?

**Comment by ynohtna92** [comment]
What we can do it put any extra gold into a buffer, so when gold overflows we can keep track of the gold above 99999 and make sure it returns to the gold pool when there is space for the resource.

**Comment by MNoya** [comment]
We can also override the :ModifyGold method to take from a custom pool and just include Gold into custom resources, the UI is already in position. The problem with buffer is that Interest still works out of `:GetGold` so you can only get 2k max gold from interest even if you implement it

**Comment by ynohtna92** [comment]
We can run interest on the entire total the instead than if it greater
