### ISSUE TITLE
Tower renames

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#381]
In preparation for the **Alt Tower Feature** down the road, some of the towers will need to be renamed... plus a few of them just suck period, lol. Here's the list of renames:
- **Quark**, switch to **Atom**
- **Hydro**, switch to **Geyser**
- **Erosion**, switch to **Corrosion**
- **Enchantment**, switch to **Incantation**

If anyone wants to point out any other stupid sounding names that should totally be renamed, list 'em.

**Comment by vladmarica** [comment]
Done. Reopen this issue if you decide to rename any more towers.

A note, this rename is tooltip only. Atom towers are still called Quark internally since it is too much of a pain to rename them in all the places they occur.
