### ISSUE TITLE
Attack stopping bug after micro

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#382]
Investigate http://forums.eletd.com/topic/95467-attack-stopping-bug-after-micro/

Could resume #176

**Comment by WindStrike72** [comment]
Let's see if we can resume that issue, not necessarily for 1.8, but for a later patch... unless it happens to be magically fixed in the next day.

**Comment by MNoya** [comment]
This is 100% caused by autoattack set to 'Never'
