### ISSUE TITLE
Poison Tower Rework

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#383]
Instead of doing a powershot every 4th attack (aka, x3 damage and increased AoE), scrap the x3 damage and purely go for increased AoE... specifically 400/800 (no joke).

**Tooltip**
- Every fourth attack hits a massive area of 400(Full)/800(Half) AoE.

**Comment by vladmarica** [comment]
Give it a try, let me know if you think that the particle should be modified (it doesn't accurately depict the AOE).

**Comment by MNoya** [comment]
I think we could use a modified venomancer ult particle that isn't as flashy, I can take care of that

**Comment by vladmarica** [comment]
The particle is the last thing to be done for this issue.
