### ISSUE TITLE
Life Tower Rework

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#384]
While you're below 50 lives, every 6 / 5 / 4 kills with this tower increases your lives by 1. Aka, keep that part same as is.

However, when you're at 50 lives, you don't gain lives, and instead, **Life Tower** gains a 25% damage increase as long as you're at 50 lives.

**Tooltip**
- Every few creeps killed by this tower will heal you. This takes into account all other Life Towers that you own. If you are at full health, this tower gets a damage bonus instead.

**Comment by MNoya** [comment]
50/100 for coop. Isn't 25% damage a bit low considering how many lifes could be gained normally? I like this rework, I just fear it might be too harsh of a nerf

**Comment by WindStrike72** [comment]
It sounds potentially low, but given how broken the current iteration of it is, plus I'm intending on buffing its base damage a bit... it shouldn't be too problematic. I'll test it out and tweak it if needs be.

**Comment by WindStrike72** [comment]
Yay, game is more balanced, all good.
