### ISSUE TITLE
Electricity Tower Rework

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#385]
This one is a minor tweak to the ability and then screw balance. Anyhow, instead of decreasing damage per bounce by a percentage, have it increase damage per bounce by a percentage.

**Tooltip**
- Each attack sends out a chain of lightning that jumps from creep to creep. Each jump increases in damage but decreases in bounce range, up to a cap of 6 bounces.

New stats:
- **Damage:** 120 / 600 / 3000
- **Damage Increase per bounce:** x1.2
- **Bounce Range:** 300
- **Bounce Range Decrease per bounce:** 30%
- **Bounce Cap:** 7

**Comment by WindStrike72** [comment]
All good now.

**Comment by vladmarica** [comment]
Wait, were the tooltips updated already?

**Comment by WindStrike72** [comment]
No, I'm gonna apply all the tooltip changes in one go.

**Comment by vladmarica** [comment]
Alright. Poison and life tower tooltips have already been done!
