### ISSUE TITLE
Erosion damage applying an extra tick

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#386]
The damage of **Erosion Tower** (or **Corrosion**, whatever the new name) is supposed to only tick 5 times, but it's currently ticking 6 times. I checked **Roots Tower**, and it's applying properly at only 5 ticks, same duration.

**Comment by MNoya** [comment]
Do you want the first tick to be dealt when the modifier is applied? I remember adding this on purpose because otherwise the tower feels awkward, as the projectiles hit but wont do any damage until 1 second has passed.

**Comment by WindStrike72** [comment]
Ahh okay. Derpity. In that case, I see the edit, I'll change it back and just decrease the damage amount.

**Comment by WindStrike72** [comment]
All good now.

**Comment by WindStrike72** [comment]
Could we get this applied to Flooding Tower as well?

EDIT: Nvm.
