### ISSUE TITLE
Remove Water and Earth abilities

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#388]
Of the single-element tower abilities, these two are really arbitrary and only there because of the reasoning "well if half of the single-element towers have abilities, the other half should too". Don't completely nuke their abilities, we could use them for alt tower abilities later, just remove them from **Water & Earth Towers**.

In their place, I'mma tweak their AoEs so that they'll still be unique, and way easier to balance.

**Comment by MNoya** [comment]
Bounce and Aftershock removed, proceed to close this after you're done tweaking their AoEs

**Comment by WindStrike72** [comment]
Already done. Thanks!

**Comment by WindStrike72** [comment]
Whoops, I didn't double-check it. The abilities are still listed on the towers, though thanks to my pseudo fixes earlier, they do nothing.
