### ISSUE TITLE
Trading Pure Essence for 12th Element

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#393]
So, I tested this out, and this actually isn't OP, provided there's a particular limitation. In the Elemental Summoner, could we get something in there that lets you trade one of your Pure Essences for a Lumber? However, the limitation is that you need to have 3 Level 3 Elements, and you can only do this once. Pretty much, it unlocks a few more builds into being usable, namely 3-3-3-3 and 3-3-3-2-1, neither of which are broken. They're strong, but as far as I can tell, they're no stronger than 2-2-2-2-2-1.

**Comment by ynohtna92** [comment]
Hatincat.com can now handle the extra element pick (also shown in view). For future reference database schema changes take a while to do an will require server maintenance (meaning the server will not be able to store matches) for the duration of the upgrade. So be certain that it needs changing before altering anything.
