### ISSUE TITLE
Force 4-element on random in co-op

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#394]
For the record, Noya suggested this before and I shot it down, but after experiencing pain, pain, and why god why, Master Noya is right, and for selecting random in co-op, prevent it from allowing you to get more than 4 different elements.

**Comment by MNoya** [comment]
:innocent: 

Should 2 player lobbies still be forced to 4-element randoms?

**Comment by WindStrike72** [comment]
Yes. I'm actually requesting this cause 5-ele randoms in solo tends to suck. That is, they give it in such an order in most cases that it's bad. 5-ele solo or 2-player can work, but if so, it pretty much has to be all pick.

**Comment by MNoya** [comment]
```
Generating 10000 random element sequences:
3-element random sequences: 103 (1%)
4-element random sequences: 9897 (98%)
```

In single player:

```
Generating 10000 random element sequences:
3-element random sequences: 1 (0%)
4-element random sequences: 480 (4%)
5-element random sequences: 4313 (43%)
6-element random sequences: 5206 (52%)
```
