### ISSUE TITLE
Save Toggle Grid state for next game

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#396]
@ynohtna92 can we add a field for this?

**Comment by ynohtna92** [comment]
Yes

**Comment by ynohtna92** [comment]
Completed, same as the other save function with added 'grid' (0 or 1). You will just need to handle it in game now.

**Comment by ynohtna92** [comment]
@MNoya No it won't however it probably won't be necessary to do. Can you not just save it at the end of the game?

**Comment by MNoya** [comment]
Yup, that's how it's done at the moment, one save a the end, should be enough.
