### ISSUE TITLE
Major Changes

### ISSUE THREAD

**Issue by ynohtna92** [Karawasa/Element-TD#4]
Todo list for major gameplay changes:
- [x] Express Mode
- [x] Tower Revisions 9e477d3b30a27ed67d02990a08a333f8ad785c8e
- [x] Swarm Creeps
- [x] Scoring System 566f63c5bc6f2419572fc70e7933dc57ef61003e
- [x] Creep/Tower Stats
- [x] First 5 waves removed 00a2175f85a84b9d3e92a62e0e3facdd392f6557
- [x] Simplified difficulty/hp/armor relationships 96c1816d6ee7e19be005b314a445e67f58575c37

**Comment by ynohtna92** [comment]
Scoring System Interface 
![image](https://cloud.githubusercontent.com/assets/2245318/11702563/c1cf3460-9f2b-11e5-842f-e7527b7f43ae.png)

**Comment by Karawasa** [comment]
Nice!

**Comment by ynohtna92** [comment]
Express mode and swarm creeps are done.

**Comment by ynohtna92** [comment]
Finished tower revisions with 9e477d3b30a27ed67d02990a08a333f8ad785c8e

All tower/creep stats should be up to date.
