### ISSUE TITLE
Tier 3 Triples

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#405]
Reserved for 1.9

Also debating whether this should happen, gotta revisit design philosophy for this sucker.

**Comment by WindStrike72** [comment]
Putting this idea on hold, although it's supposedly easy to implement, it might not be a good idea to implement yet from a balance structure perspective.

**Comment by WindStrike72** [comment]
Alright, let's do this, for all the triple-element towers. This'll be the main feature of 1.11, and although it's supposedly easy to implement according to **Noya**, it probably won't publicly release for a few weeks due to testing reasons and not wanting to horribly outpace the mobile version.

In terms of numbers, for now, make 'em identical to Tier 2 Triples. For cost, upgrade cost of 8000 and a pure essence, total gold cost of 13000. Requirements, requires Level 3 of all elements involved.

**Comment by MNoya** [comment]
Ok so the process to add a Tier 3 Triple is:
- In scripts/npc/items/upgrades/triples
  - Copy **item_upgrade_to_TARGET_tower_2** and **item_upgrade_to_TARGET_tower_2_disabled"
  - Replace the _2 by _3, same on the "2" of the requirements
  - Change the ItemBaseLevel to 3
- In scripts/npc/units/towers/triples
  - Copy **TARGET_tower_3**
  - Rename to _3, same with the "2" of the Requirements
  - Update "Cost" and "TotalCost' (8000 and 13000)
  - Add "Upgrades" block (can be grabbed from the base unit, changing the _2 for a _3):

```
"Upgrades"
{
    "Count" "1"
    "1"         "TARGET_tower_3"
}
```

And of course, there's the actual number changes on damage of the tower and ability scaling, as well as the item and unit tooltip.
