### ISSUE TITLE
6-Element Random happens waaaaay too often

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#409]
So this didn't used to happen, but I'm getting reports from others (myself included), that **Random** seems to be giving 1-1-1-1-1-1 (aka, 6-ele) just about every single bloody game. Just wondering if there was a change to how randoms were done (outside of the co-op change), and if it's possible to make 6-ele happen, well... not as bloody often, lol. Not ban it entirely like the co-op restrictions, just make it happen less if possible.

**Comment by MNoya** [comment]
Generating 10000 random element sequences:
3-element random sequences: 1 (0%)
4-element random sequences: 480 (4%)
5-element random sequences: 4313 (43%)
6-element random sequences: 5206 (52%)

So yeah, its more than half the time

**Comment by WindStrike72** [comment]
Lol, that 3-element chance. If it could be weighted a bit to give something closer to say, 10%, 30%, 30%, and 30%, that'd be awesome, though I figure it probably won't get that nice.

**Comment by MNoya** [comment]
That's on a 11 elem sequence, I should generate some more for 6 elem to see whats the chance of getting early 1-1-1-1-1-1 build. 

Also I just realized, the Lumber purchase 12-element lets you pick an element even on -Random mode, should that be allowed?

**Comment by WindStrike72** [comment]
I don't see why not; just as long as you don't get random'd the hilarity of Pure Essence + Extra Lumber, cause they cancel each other out, lol.

**Comment by MNoya** [comment]
```
Generating 10000 random element sequences:
3-element random sequences: 100 (1%)
4-element random sequences: 3436 (34%)
5-element random sequences: 4377 (43%)
6-element random sequences: 2087 (20%)
```
