### ISSUE TITLE
Movespeed slow stacking additively

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#41]
Currently, how slows work:
- Creep Speed - Slow 1 - Slow 2 = Result
- Ex: 300 - 30% (90) - 10% (30) = 300 - 40% (120) = 180

How they should work:
- Creep Speed \* (1 - % Value) \* (1 - % Value) = Result
- Ex: 300 \* (1 - 30%) \* (1 - 10%) = 300 \* 0.7 \* 0.9 = 189

It's not too big of an issue with that example, but when you go 6-ele and stack as many slows as possible, it drops creeps to 20% movespeed, aka 60. Multiplicatively, it's only supposed to drop down to minimum of 119 movespeed.

**Comment by MNoya** [comment]
The minimum is still 100 ms unless we override the value on all creeps, is this still relevant with this cap?

**Comment by WindStrike72** [comment]
It shouldn't be. The absolute lowest you can get is 119, using two Level 2 Slowing Towers and two Level 1 Slowing Towers via a 6-element build.

**Comment by MNoya** [comment]
Fixed with 0b57cd56657ad659f70dc8b4b7e036ae8ce48e33
