### ISSUE TITLE
Default Fire Tower behavior

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#418]
Can we make it so Fire Tower's default behavior is to **always** shoot closest target? So, switch to closest on each attack. That should help prevent it from causing drastic overkill with its primary attack.

**Comment by MNoya** [comment]
Animation is lost due to each attack needed to be Interrupted, check if you like it and close

**Comment by WindStrike72** [comment]
Gonna bump animation point to 0.1 to fix stiffness, otherwise all good.
