### ISSUE TITLE
Missing some UI localizations

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#423]
- [x] http://gogolik.ru/pic/eletd1.jpg Scoreboard
- [ ] http://gogolik.ru/pic/eletd2.jpg Element Message
- [x] http://gogolik.ru/pic/eletd3.jpg Interest
- [x] http://gogolik.ru/pic/eletd4.jpg Voting

**Comment by ynohtna92** [comment]
Where does the element message come from?
