### ISSUE TITLE
Short Mode

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#424]
Could we get the following two modes added? FYI, these would selectable as radio buttons alongside **Express Mode**, meaning you can only pick one of the three:
- **Short Mode**: Start the game at **Wave 11**, with 1000 Gold, 3 Lumber, 25000 Score, and 45 seconds to set-up before the wave begins. Additionally, when calculating the speed score bonus at the end, use 39 instead of 45.
- **Extra Short Mode**: Start the game at **Wave 26**, with 6000 Gold, 6 Lumber, 95000 Score, and 60 seconds to set-up before the wave begins. Additionally, when calculating the speed score bonus at the end, use 25 instead of 45.

The idea is to be able to get a decent score without having to go through the ultra-repetitive first parts of the game, cause when doing score runs, they have a tendency to be that way.

**Comment by WindStrike72** [comment]
Kay, just one **Short Mode**, no extra short. new numbers:
- Start the game at **Wave 16**, with 1600 Gold, 4 Lumber, 10000 Score, and 60 seconds to set-up before the wave begins. Additionally, when calculating the speed score bonus at the end, use 35 instead of 45.

**Comment by WindStrike72** [comment]
For description, do "Starts on Wave 16 of Classic."

**Comment by vladmarica** [comment]
All that's left to do is precaching towers for short mode, which I'll do tomorrow.

@WindStrike72, everything else should be done, let me know if you are happy with it!
Also, @MNoya said he would do the stats collection for this.

**Comment by WindStrike72** [comment]
Alllmost there, few little fixes:
- The starting **10,000 Score** should be affected by difficulty, so if you select say **Very Hard**, it'd be **30,000 Score**
- All initial element picks should be freebies, not just the first element pick.
- Unless you attempt to yoink a Level 3 element, those should still summon bosses.

**Comment by vladmarica** [comment]
So, Normal is 10000, Hard 20000, Very Hard 30000, Insane 40000?

**Comment by vladmarica** [comment]
@WindStrike72 ok, assuming I was right about how you want base score to scale, short mode is finished feature-wise!

**Comment by WindStrike72** [comment]
Little bug: it starts you with 4 lumber, and then adds another lumber a little bit later. Also, sorry for late response on the scoring, Insane should be 45,000 cause it's x4.5 score mult- oh, the UI text isn't updated.

... derp.

EDIT: Fixed the x4 to x4.5 thingy

But yeah, otherwise, perfecto!

**Comment by WindStrike72** [comment]
Kay, last fix for sure, I swear.
- Can we have the start game button available to skip any of the remaining starting timer?

**Comment by vladmarica** [comment]
Sorry, I though I already fixed that!
