### ISSUE TITLE
'In-hand' towers disappear

### ISSUE THREAD

**Issue by insunaa** [Karawasa/Element-TD#425]
When you have a tower 'in-hand' meaning to be built, and use your mouse at the edge of the screen to move around the map, the model becomes invisible and the marker for where to place the tower disappears. The tower can still be placed, but it has to be eyeballed and one can't use the grid as visual reference anymore.

**Comment by MNoya** [comment]
Ah yes this is a long overdue bugfix from the panorama part of the building library, thanks for the reminder!

**Comment by MNoya** [comment]
I can't seem to be able to reproduce it, do you have any specific steps for it to happen?

**Comment by insunaa** [comment]
This is how it looks like to me when the bug triggers:
I just tested it again and it seems to be only the upper edge of the screen, not the other ones.

![eletd_bug](https://cloud.githubusercontent.com/assets/3718129/15808082/98b5b3c2-2b6e-11e6-8d48-127b181f63ec.png)

**Comment by MNoya** [comment]
Still can't manage to reproduce this on my end :disappointed: 

I'll try some wild fix

**Comment by MNoya** [comment]
Does it still happen after that attempted fix @d3rrial?

**Comment by insunaa** [comment]
Sorry I didn't have the time to test until now, it does indeed work correctly now!
