### ISSUE TITLE
Random Mode broken

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#428]
Lol, every time something gets fixed, a new bug pops up.

For Short Mode only, the 30 second break time you get every 5 waves is broken and reverts to whatever the difficulty's cooldown wave timer is.

**Comment by vladmarica** [comment]
Sorry for leaving in all these problems. Leave this issue open when you can't find any more problems with short mode.

**Comment by WindStrike72** [comment]
Nah, I was worried you were gonna strangle me for finding a bug every time it loads.

Which, by the way, after beating Wave 16 now if you're on Short + Random (what), it thinks the next wave is Wave 2, and thus never starts.

This plopped up in mah console:

[   VScript              ]: 
[   VScript              ]: scripts/vscripts/coop/coop_mode.lua:123: attempt to call method 'LeakedWave' (a nil value)
[   VScript              ]: stack traceback:
[   VScript              ]:     scripts/vscripts/libraries/timers.lua:136: in function 'LeakedWave'
[   VScript              ]:     scripts/vscripts/coop/coop_mode.lua:123: in function <scripts/vscripts/coop/coop_mode.lua:117>
[   VScript              ]:     [C]: in function 'xpcall'
[   VScript              ]:     scripts/vscripts/libraries/timers.lua:135: in function <scripts/vscripts/libraries/timers.lua:93>

**Comment by WindStrike72** [comment]
I stand corrected, it's not Short Mode related at all, it's Random Mode causing this.

**Comment by WindStrike72** [comment]
Attempted to circumvent it by randoming after game started. Was going good until I ran into an Undead wave, and when the creep respawn, it stood still. Error I got was:

[   VScript              ]: MoveToPosition parameter 1: expected vector but got void.
[   VScript              ]: scripts/vscripts/coop/coop_mode.lua:119: Parameter type mismatch
[   VScript              ]: stack traceback:
[   VScript              ]:     scripts/vscripts/libraries/timers.lua:136: in function <scripts/vscripts/libraries/timers.lua:135>
[   VScript              ]:     [C]: in function 'MoveToPosition'
[   VScript              ]:     scripts/vscripts/coop/coop_mode.lua:119: in function <scripts/vscripts/coop/coop_mode.lua:117>
[   VScript              ]:     [C]: in function 'xpcall'
[   VScript              ]:     scripts/vscripts/libraries/timers.lua:135: in function <scripts/vscripts/libraries/timers.lua:93>

**Comment by MNoya** [comment]
Somehow the game is using `[DEBUG] Starting co-op break time for wave 1` on the default map.

**Comment by WindStrike72** [comment]
Whelp, the waves work, now random is giving me my elements automatically, regardless of whether I'm on express or not. That is, no elemental bosses.
