### ISSUE TITLE
Ultra Widescreen Interest Bar Error

### ISSUE THREAD

**Issue by Karawasa** [Karawasa/Element-TD#433]
3440 x 1440

![untitled](https://cloud.githubusercontent.com/assets/7691068/15982973/17f43436-2f5e-11e6-8a4b-538168322f00.png)

**Comment by ynohtna92** [comment]
Fixed with Panorama update and https://github.com/MNoya/Element-TD/commit/bc6c86c800660e137777f7a4199648ce7bc78914
