### ISSUE TITLE
Magic Tower range can be reset by upgrade/cancel

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#437]
You can reset Magic Tower's range to max by upgrading the tower and then canceling the upgrade. It's not that big of a balance issue really.

**Comment by MNoya** [comment]
It ok, we've handled these issues case-by-case with Runic and such, should be easy enough to fix

**Comment by WindStrike72** [comment]
[See this issue.](https://github.com/MNoya/Element-TD/issues/439)
