### ISSUE TITLE
List of abilities that can be refreshed via upgrade - cancel

### ISSUE THREAD

**Issue by Califax526** [Karawasa/Element-TD#439]
Light - Consecutive attack counter resets.
Poison - Poison Burst attack counter resets.
Atom - Consecutive attack counter resets.
Magic - Attack range goes back to 1500.
Tidal - Tidal Wave stacks resets.
Haste - Wrath stacks resets.

Well - Buff duration refreshes.
Blacksmith - Buff duration refreshes.
Trickery - Debuff duration refreshes.

Avenger Creeps - Debuff duration refreshes.

**Comment by WindStrike72** [comment]
Nothing remaining is abusable, closin' the issue.
