### ISSUE TITLE
Icefrog keeps going with 0/1 HP

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#44]
I kid you not:

[http://images.akamai.steamusercontent.com/ugc/307737558710999700/EAB631E03835EC5397775BCE3B6D151BBA779D1F/](url)

I'm pretty sure this is a result of Swarm + Undead though, because they kept endlessly coming back from the dead, until I guess the game broke. So in all likelihood, this will be naturally fixed from Undead being axed from the Boss Wave.

**Comment by MNoya** [comment]
![img](https://static-cdn.jtvnw.net/emoticons/v1/81248/1.0) BALANCED ![img](https://static-cdn.jtvnw.net/emoticons/v1/81248/1.0)
