### ISSUE TITLE
Minimum speed to 50

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#440]
Noya-senpai, I suck at figuring crap out despite my ability to partially redo life tower's ability, can you set the minimum movement speed down to 50?

**Comment by vladmarica** [comment]
I don't know if this is possible. It seems like the modifier function for `MODIFIER_PROPERTY_MOVESPEED_ABSOLUTE_MIN`,`GetModifierMoveSpeed_AbsoluteMin`  is never called.

**Comment by MNoya** [comment]
Doesn't this already work? If `modifier_slow_adjustment:GetModifierMoveSpeed_Absolute()` returns 50 the MS should be 50, there's no need to set a minimum I believe, but I could be wrong and having a Min is necessary.

**Comment by vladmarica** [comment]
I tested that, even if you return 50 from that function it is still 100 on the unit.

**Comment by MNoya** [comment]
There we go, needed to use Limit because Min is unlinked and Absolute is bugged below 100 in lua (works in datadriven)
