### ISSUE TITLE
Nuke 12th Element Pick

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#442]
Can we have the 12th element pick thingy nuked? It was cool while it lasted, but in conjunction with Tier 3 Triples, it simply can't exist and still be balanced. Also, there was a trick that let you have a free pure at Wave 46 instead of Wave 51 by buying an essence, and then trading your next essence for a lumber on the last pick, which was rather abusable.

**Comment by MNoya** [comment]
Alright, do tier 3 triples as if the 12th element pick wasn't there, I'll remove it

**Comment by WindStrike72** [comment]
Resolved in [#ec39c55](https://github.com/MNoya/Element-TD/commit/ec39c55ecd959ebe62a221afa94d9a0a0413c5b2)
