### ISSUE TITLE
Vapor Tower Update

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#447]
Been meaning to suggest this for a while to make it simpler to deal with and waaaaaay easier to balance, not to mention theoretically less lag. Could we change **Vapor Tower** to the following?
- Nuke the secondary explosions thing. Then, for every creep within its attack range, its damage is increased by a flat amount. For arbitrary numbers, try 30 / 150 / 750.

**Comment by vladmarica** [comment]
Try it out. If you modify the damage numbers, make sure you update the files npc/upgrades/duals/item_upgrade_to_vapor_tower_X.txt as well.

**Comment by WindStrike72** [comment]
Seems good. Definitely needs number tweaking, but functions nicely, and definitely less laggy than before. Thanks!
