### ISSUE TITLE
Custom Builders rider angles

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#449]
They broke?

![img](https://a.pomf.cat/zodwsd.png)

![img](https://a.pomf.cat/wddntk.png)

**Comment by ynohtna92** [comment]
Any idea how you would fix this? Changing the yaw does nothing.

**Comment by MNoya** [comment]
Does it happen every time or just when doing an specific animation?

**Comment by ynohtna92** [comment]
It is stuck in whatever orientation it starts in for all mountable cosmetics.

Also just to piggy back of this issue. The units are not animating in the custom builder panel.

**Comment by MNoya** [comment]
Nice job @ynohtna92 !
