### ISSUE TITLE
Flamethrower Tower Update

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#451]
Since this tower seems to have issues with regards to **Napalm** not going off, but at the same time, the chain reactions where everything dies awesome, suggestin' an update that'd help it out:
- **Active**: Detonates **all Napalm stacks on all creeps**

**Comment by vladmarica** [comment]
Not quite sure what this ability is supposed to do. Remove all napalm stacks off of all creeps in your maze, creating a sunburn remnant where they were? Does it work on creeps even if the debuff was added by a different flamethrower tower?

**Comment by WindStrike72** [comment]
Actually, scratch that idea, instead, go with just... instead of **Napalm** detonating only on death, if they're not dead in 15 seconds, detonate. Each time a stack of **Napalm** is applied, it should reset the timer. So no active, no global "detonate everything" button. Think **Sand King's Caustic Finale** passive, except that it stacks just like usual.
