### ISSUE TITLE
Slowing Abuse Bug

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#452]
How to permanently slow creeps down:
1. Build a Level 3 Slowing Tower at the front
2. Then, near it, build a Level 1 Slow Tower of that exact same type.
3. Creeps passing through both (as long as the Level 1 Slow refreshes the Level 3 Slow) will be permanently slowed down to 90 movement speed. This remains true even once they leave the slows.

Doesn't seem to work when trying with Level 2 & Level 1, so it's probably a coding error with just Level 3's interactions.

**Comment by vladmarica** [comment]
@WindStrike72 Try out my fix for this. Seems to work great in all of my test cases.

**Comment by WindStrike72** [comment]
Sweet, it works, and I can't seem to break it.
