### ISSUE TITLE
Periodic Tower Overhaul

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#454]
Periodic Tower, the... most boring tower in the game probably. I suggested this a while back, never got a response on it, so here goes attempt numero two:
- Fires 6 different projectiles per attack, one of each different element.
- Fires at up to 6 different targets.
- If there's less than 6 different targets in range, multiple projectiles can hit the same target.
- Keep the same range and attack speed, I'll tweak damage myself.

If it's too crazy, feel free to shoot it down.

**Comment by ynohtna92** [comment]
I started to write this and it is definitely doable with some changes to the core (for correct element damage type). Did you want to make it so that each element has the same passives as the 6 elemental towers?

**Comment by ynohtna92** [comment]
@WindStrike72 I have left the range and damage tweaking and tool-tips for you.

**Comment by WindStrike72** [comment]
No to the passives of the other towers, it should be its own unique split-shot tower of doom.

**Comment by ynohtna92** [comment]
Yep that is what I have done. Did you want to make sure that the targets are all in front of the unit? Right now it finds whatever is in range in whatever direction.

**Comment by ynohtna92** [comment]
@DogBollocks @biax for testing and review.

**Comment by DogBollocks** [comment]
My opinion:
**Insane mode**
->Attacks randomly - target not locked (correct me if I am wrong)
->Damage for the meantime seem suffice
->Might want to consider increasing the price (maybe 1k-2k)
->110k net worth (slow x4, support x7, enchantment x8, laser x4, periodic tower x2), only leaks around wave 7

**Comment by ynohtna92** [comment]
Added tooltips in e5426c20ebad3322a017833c20dd7b4f25f88542. Ready for 1.17 update.
