### ISSUE TITLE
Direct attacks no longer deal damage

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#456]
As of the latest Dota 2 patch, it broke yet even more bloody things. Here's the thingy that popped up in console every time a direct hit tried to deal damage:

[   Developer              ]: scripts/vscripts/towers/basic/WaterTower.lua:19: GetAverageTrueAttackDamage called with 1 arguments - expected 2
[   Developer              ]: stack traceback:
[   Developer              ]:   [C]: in function 'GetAverageTrueAttackDamage'
[   Developer              ]:   scripts/vscripts/towers/basic/WaterTower.lua:19: in function <scripts/vscripts/towers/basic/WaterTower.lua:17>
[   Developer              ]:   ...ddons\element_td\scripts\vscripts\towers\towerevents.lua:14: in function <...ddons\element_td\scripts\vscripts\towers\towerevents.lua:3>
[ W VScript                ]: Script Runtime Error: scripts/vscripts/towers/basic/WaterTower.lua:19: GetAverageTrueAttackDamage called with 1 arguments - expected 2
[ W VScript                ]: stack traceback:
[ W VScript                ]:   [C]: in function 'GetAverageTrueAttackDamage'
[ W VScript                ]:   scripts/vscripts/towers/basic/WaterTower.lua:19: in function <scripts/vscripts/towers/basic/WaterTower.lua:17>
[ W VScript                ]:   ...ddons\element_td\scripts\vscripts\towers\towerevents.lua:14: in function <...ddons\element_td\scripts\vscripts\towers\towerevents.lua:3>

And that wasn't just Water tower, it was other towers too.

From what I could tell, ability damage still worked, cause Flooding Tower was still hurting stuff.

**Comment by WindStrike72** [comment]
Fixed this and updated main client.

**Comment by MNoya** [comment]
Yeah Valve updated the API function `GetAverageTrueAttackDamage` to require an useless extra argument because whothehellknows

**Comment by wang37921** [comment]
> Yeah Valve updated the API function `GetAverageTrueAttackDamage` to require an useless extra argument because whothehellknows

thanks!
