### ISSUE TITLE
13 Elements

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#461]
Somehow, this happened:

http://www.eletd.com/leaderboard/matches/2707094449
http://forums.eletd.com/topic/95707-13-elements-bug-or-not/

No clue how it's possible.

**Comment by MNoya** [comment]
Sandbox?

**Comment by biax** [comment]
If I were to guess it would be the script parsing the database 
incorrectly. Maybe not all conditions are considered. Also if you 
notice: Sandbox.

**Comment by ynohtna92** [comment]
The database does not build the leaderboard based sandbox. It will only exclude data if cheat is set to 0 and the game is whitelisted. I'm pretty sure that cheat should have been set to 1 if the game was played in Sandbox, but for some reason in this case it wasn't.

In future the leaderboard builder will check for the order field != 'Sandbox' to prevent this from happening again.

I have manually set the cheat field to 1 in the database.

**Comment by ynohtna92** [comment]
This should fix it. https://github.com/ynohtna92/ElementTDLeaderboard/commit/22ee0f76634ed7f7982d68eeba0d3b273e7f732e
