### ISSUE TITLE
Geyser change

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#465]
I had a change applied to **Geyser Tower** recently. When it kills a creep, it causes a torrent, damaging nearby creeps. Torrents can chain other torrents. Aka, **Patch 1.3's Nature Tower**. Which makes it remarkably similar to **Flamethrower Tower**.

How would I make it so the torrents can't chain other torrents?

**Comment by ynohtna92** [comment]
A quick way to fix this is to change

```diff
		ParticleManager:SetParticleControl(torrent, 1, target:GetAbsOrigin())

+        DamageEntitiesInArea(target:GetOrigin(), self.explosionAoE, nil, self.explosionDamage)
-        DamageEntitiesInArea(target:GetOrigin(), self.explosionAoE, self.tower, self.explosionDamage)
	end
end
```

 https://github.com/MNoya/Element-TD/blob/master/game/dota_addons/element_td/scripts/vscripts/towers/duals/HydroTower.lua#L37
