### ISSUE TITLE
Missing attack projectiles

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#469]
For me, I got no projectiles on:
- Polar
- Muck
- Flooding
- Quake
- Poison
- Ephemeral
- Impulse
- Blacksmith
- Well
- Moss

**Comment by MNoya** [comment]
There's probably more, need to check the precache systems to see what's happening and why are some of them not loading

**Comment by WindStrike72** [comment]
All projectiles are showing up on my end, except for Ice and Obliteration as usual.

**Comment by biax** [comment]
Haste dont show for me in local. Fine in main.
