### ISSUE TITLE
Icefrogs still OP

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#47]
Wave 55 - got 2 leaks but otherwise slaughtered 'em.
Boss Wave - got 2 kills, got slaughtered.

However, rather than having Shield nuked, I got some second opinions on this: nuke Fast from the Boss Wave. Shield isn't that big a problem especially since it's only 1 second invulnerability on Swarm splits. Fast, on the other hand, screws over a lot of defenses.

**Comment by MNoya** [comment]
Still stronk, perhaps reducing its HP? I prefer them having abilities than just being a glorified punch bag

**Comment by WindStrike72** [comment]
I got a better idea. Have them alternate all the abilities as they come out of the gate. So in this order:
- Shield
- Swarm
- Healing
- Undead
- Fast

And then that on cycle. The issue is with the ability stacking on each icefrog, they're waaaay too strong, but if it's just one per creep, and the ability is rotating, it should be fine. Might need to upgrade its starting hp a bit, but for now, let's try this.

**Comment by Karawasa** [comment]
Interesting solution. If we are doing that they should probably go back to double HP of wave 55?

**Comment by WindStrike72** [comment]
Surprisingly, they're still really strong. Did a random run, twas able to beat wave 55, and then only got a few kills on the icefrog wave, though admittedly, that was a pretty bad build. I'll need to run some of my actual builds against it to see if they need an hp buff or not.

**Comment by WindStrike72** [comment]
Annnd all of them still have Undead + Swarm even if it's not listed on there.
