### ISSUE TITLE
Need AoE Popup for Fire Tower

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#471]
For **Fire Tower**, could we have it so there's a number popup over its head for whatever its AoE currently is?

**Comment by ynohtna92** [comment]
Do you want this to appear on the target instead?

**Comment by WindStrike72** [comment]
No, should be the tower. If it appeared over the target, it'd be mess of numbers in one spot w/ multiple fire towers.

**Comment by ynohtna92** [comment]
Added on the dev branch. It looks messy however. It might be better just to remove this visual.

**Comment by ynohtna92** [comment]
Leaving as it for now. Reopen this issue if you want to discuss this change further.
