### ISSUE TITLE
Making ETD Test public?

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#472]
Right now, ETD Test is private. The only ones that can access it are those that have **Noya** on their friends' list. However, I'd like to suggest that ETD Test goes public. Obviously, it still wouldn't have dedicated server support and never should, but it gives people a chance to look forward to potential future updates, instead of random out-of-nowhere "hey guys, we actually updated for once!" It's not like ETD Test scores go to the leaderboard anyways, so in theory, it shouldn't hurt. Plus it lets anyone new interested in it skip the waiting step of the **Noyanator**.

Thoughts?

**Comment by biax** [comment]
Agreed

**Comment by MNoya** [comment]
Done
