### ISSUE TITLE
Fire Tower isn't focusing vs. Highest HP

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#474]
On its default targeting, **Fire Tower** should be:
 - Shoot Highest HP Creep in range
 - Continue to shoot it till it's dead or out of range
 - Rinse and repeat

Currently though, it is not focusing, so it's just, on every attack, shooting Highest HP Creep in range. I have no idea why either.

**Comment by Karawasa** [comment]
Bump @MNoya

**Comment by WindStrike72** [comment]
Yeah, we actually already fixed this one, just forgot to close the issue. Derp.
