### ISSUE TITLE
Terrain selection screen changes -- need guidance

### ISSUE THREAD

**Issue by biax** [Karawasa/Element-TD#477]
![screenshot_67](https://cloud.githubusercontent.com/assets/15166474/20814426/89670d1c-b854-11e6-8e2f-c912a5057b1d.png)

Do review the screenshot

**Comment by biax** [comment]
I think this might involve the map editor although I can't be sure. Would like to be told whats involved to accomplish this.

**Comment by MNoya** [comment]
So if I understand this correctly, you want to do the following right after everyone loads (team selection aka terrain selection)

1. Show some form of leaderboard
2. Hide the current changelog & mobile ad to make space for point 1.

**Comment by biax** [comment]
exactly

**Comment by biax** [comment]
i have some time freed now.

this is the first feature that i'd like to add to the next version. i need some guidance on this.
