### ISSUE TITLE
Element selection

### ISSUE THREAD

**Issue by Karawasa** [Karawasa/Element-TD#481]
From forums:

I still encountered the bug when you cannot choose an element unless you reconnect again.

**Comment by ynohtna92** [comment]
This requires more detail. I can select elements from the element summoner at the top of the maze.

**Comment by biax** [comment]
Newer players probably won't realize they need to use the summoner. 
Perhaps the better way is the normal dota2 means of leveling up spells, 
which btw can be triggered via hotkey like ctrl-q,w,e,r etc.

**Comment by ynohtna92** [comment]
I can add a new panel similar to the old one that will pop up when new lumber is acquired.

**Comment by WindStrike72** [comment]
Kay, got clarification on the bug, prior to 7.00 breaking things, you could upgrade your elements from your hero, so @ynohtna92, that fix right there would be it.

**Comment by MNoya** [comment]
We basically need a new button on top of the new ui bar that selects the elemental builder
