### ISSUE TITLE
Speed wave only speed up once

### ISSUE THREAD

**Issue by DogBollocks** [Karawasa/Element-TD#483]
During the speed wave, the mobs will speed up once after it came out from the entrance and it will not speed up again after that.

**Comment by ynohtna92** [comment]
Confirming this is an issue. It will happen a couple times then fail to work.

@MNoya I can't tell why is is breaking as it doesn't seem to be causing the script to error. It has changed since the last time I looked at it.

**Comment by MNoya** [comment]
Fixed in dev, waiting for some other changes to merge and update the game
