### ISSUE TITLE
Elemental Summoning Center

### ISSUE THREAD

**Issue by Karawasa** [Karawasa/Element-TD#484]
From the forums:

I'm getting an error on the element spawner building which prevents spending lumber and the icons are sometimes missing from the builder action card despite being able to perform those actions nonetheless.

**Comment by DogBollocks** [comment]
I never encounter the element prevent spending lumber issue, but I've encountered the missing icon when I was in sandbox mode.

**Comment by ynohtna92** [comment]
Can you screenshot what this looks like? I can't fix it if I cannot replicate it.
