### ISSUE TITLE
What's needed for setup again?

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#487]
New computer, and been away from this too long to remember. Outside of GitHub, what things do I need to get set back up? FYI I'll be busy packing/traveling next few days, but I should be able to work on this probably Sunday.

**Comment by ynohtna92** [comment]
Dota 2 tools and that is about it.

**Comment by WindStrike72** [comment]
Okay. Annnnnd just remembered the other one I needed, Link Shell Extension. Sorry bout that. Thanks.
