### ISSUE TITLE
Acquiring Lumber in Multiplayer

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#49]
In a multiplayer game, right now, when you clear Wave 5, 10, or any multiple of it, you get a Lumber; or in Random mode, that's when the element auto-summons. However, that's not quite right.

When the first player clears Wave 5 (or any multiple of it), EVERYONE gets the Lumber (or in Random, the element auto-summons). Or in the case of Rush mode, when Wave 5 finishes spawning (or any multiple of it), that's when the Lumber/Elemental Summon kicks in.

**Comment by Karawasa** [comment]
So just to be clear, as soon as the first player gets his lumber/lumber spent (random)...all others do too.

So in random, everyone gets the elemental at the same time.

**Comment by WindStrike72** [comment]
Likewise, in Rush, when Wave 5 clears (or wave 3 in Express), everyone gets the elemental right then at the same time.

... Rush is slightly harder than intended at the moment cause of that, lol.
