### ISSUE TITLE
Crashs on reach wave 55

### ISSUE THREAD

**Issue by resial2** [Karawasa/Element-TD#492]
I'm playing Element TD on DotA 2 (7.32b) and the game are kicking when we reach on Ice Frog (First boss).

**Comment by ynohtna92** [comment]
I will have a look at it this week. Sorry for the delay.

**Comment by ynohtna92** [comment]
Fixed in https://github.com/MNoya/Element-TD/commit/7ad53ba096c30bcd9ec427ae63476241e50370f8
