### ISSUE TITLE
Elemental Summoner model

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#5]
Got an idea, based on rune models:
- Regen (Green) = Nature
- DD (Blue) = Water
- Haste (Red) = Fire
- Invis (Purple) = Darkness

Then there's Illusion (Yellow) and Bounty (Golden-Yellow). 
We could edit them to be Brown and White, and we got some good props to make a cool looking models! 

Have the runes in a circle around temple_portal001.vmdl or rune_point001.vmdl

Finally, whenever each element is upgraded/aquired, the runes appear bigger on the circle.

**Comment by Karawasa** [comment]
I like the rune idea in the trophy area. But I'd like to keep the trophy layout the same as WC3. That is because players sometimes want to see the element selection order.

**Comment by MNoya** [comment]
This is mostly done ([Runes](http://www.gfycat.com/UnripeSplendidBorderterrier) and [Trophy Area](http://puu.sh/lNVV0/b7889c303a.jpg)), the circular model is a bit bad (that pale green circle ruins it),I'll edit it alongside some extra particle visuals. And editing the Illusion and Bounty runes to better fit the Earth/Light elements would also be required

**Comment by MNoya** [comment]
Finished with af871701605c3970d4b736fce753bd7dd6e2eb0f
