### ISSUE TITLE
Rush Mode should give a bounty bonus

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#50]
As the title says, but rather than increasing the Bounty Base, this would just be a flat multiplier bonus that applies on the total. I'mma say a 25% Bounty Bonus.

It may need to be increased in combination with Express Mode, but let's see how the 25% Bounty goes first.

**Comment by ynohtna92** [comment]
How do you want it to round?

**Comment by Karawasa** [comment]
Wait, why are we doing this? Rush mode is supposed to be harder. I'm not sure I see a need to counter-balance that...especially since it already adds a score multiplier.

**Comment by MNoya** [comment]
I think the reasoning was that, given the waves spawn faster than usual, there is less interest gain ticks, so not only are you dealing with having to quickly decide which towers to build, you are also getting less gold gain overall, so a gold bonus made sense.

**Comment by WindStrike72** [comment]
In SC2 version, Rush mode was possible, but due to the increased HP scaling in the Dota version, it's... not. The first half of the game is fine, but the second half is a guaranteed crash and burn. 25% might be overkill on the bounty, and if it is, it's not hard to drop it down. An alternative might be to increase the interest rate from 2% to 3%, though given how fast you need to spend money in Rush mode and how little time there is to invest, it wouldn't make much difference.

**Comment by Karawasa** [comment]
I think if we're going to provide a "handicap" then it should be limited to a faster interest timer. Same interest percentage. Same bounty. Players will visually notice that the interest bar moves faster. Anything else is either confusing or unknown.

**Comment by WindStrike72** [comment]
Actually it wouldn't be unknown. Due to the new voting UI, when you click Rush Mode, it should display that the Bounty Bonus goes up. Not sure if it currently does, but it will.

**Comment by MNoya** [comment]
Yeah it currently does, when you hover/click it, the bounty +X% will update, and when the vote results come in you will see the final agreed results of HP/Health/Score Multiplier. Also, we can add a detailed tooltip description on the small [current mode view](http://gfycat.com/ImpossibleSameGalapagosmockingbird) when hovering hover each of the lines.

**Comment by Karawasa** [comment]
So @WindStrike72 what do you think about a faster interest timer?

**Comment by WindStrike72** [comment]
@Faster interest timer wouldn't help much, since in Rush mode, it's impossible to hoard, so you don't get much out of interest anyways. Buuut it would fit with the flow of the game, having say only a 10 second interest timer. I still haven't tried to see if that 25% bounty bonus works out or not.

And to answer your question Noya, round down.

**Comment by Karawasa** [comment]
I like the way you put that...fit with the flow of the game. Let's try a 10 second interest timer with no bounty bonus.

**Comment by MNoya** [comment]
It's perfectly fine to have seemingly impossible modes btw, at least to begin with, we will actually have the stats of beating each mode, and can tweak accordingly.
I'll implement the 10 sec interest rate for Rush now, and disable the gold bonus

**Comment by MNoya** [comment]
Note: The custom tooltip on gold still says "You gain interest every 15 seconds", I can change it but honestly it's always gonna be some kind of hidden mechanic, kinda need to playtest if 'faster interest rate' does make a difference on this

**Comment by WindStrike72** [comment]
Did I say 10 seconds? I meant 5 seconds.
