### ISSUE TITLE
Add gold bonus to Pure Essence Upgrade

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#51]
Not the free essences, specifically the upgrade that lets you manually get a Pure Essence. The gold bonus is:

([(Wave +5) ^ 2]) \* 2.5 \* Difficulty Bounty Bonus

Should help it stay valuable by comparison to getting an element upgrade.

**Comment by MNoya** [comment]
Done in b1c083c53a4b535e75bebed8151a77f9693cf066

**Comment by Karawasa** [comment]
I hesitate on this. We had bad experiences in SC2. Is there a good way to communicate this to the player anyway?

Also @WindStrike72 are you convinced that the DPS advantage of pure/periodic is not enough?

**Comment by MNoya** [comment]
[Tooltip says you get gold](http://puu.sh/n2K6x/9a9cf6394b.jpg) based on current wave and difficulty, and you get a big gold popup when you purchase it.

**Comment by MNoya** [comment]
So whats the status on this?

**Comment by Karawasa** [comment]
We're keeping the bonus.
