### ISSUE TITLE
Flamethrower Tier 2 causes 5 stacks

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#52]
Level 2 version of Flamethrower tower is causing 5 stacks of Napalm per hit. It should only be causing 1 stack per hit. I believe this was from the old version and I just now noticed it's doing x5 the damage it's supposed to, lol.

**Comment by MNoya** [comment]
That's what the description said originally. I'll change it back to 1

**Comment by Karawasa** [comment]
I'm assuming then that level 2 of flamethrower has stacks that do 5x damage compared to level 1?

**Comment by MNoya** [comment]
Yeah it goes from 240 to 1200 damage per stack
