### ISSUE TITLE
Remove "Support" Label from Triple Supports

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#53]
It occurred to me the only towers that genuinely should be lowest priority on being buffed are just Blacksmith, Well, Trickery, Arrow, and Cannon, since they're pretty much the lowest DPS/Gold towers in the game. That said, the label of "Support Tower" should be removed from the Triple-Element Support Towers, as they do have pretty decent DPS, even if they're a bit under the main damage towers. Aka:
- Windstorm (already done)
- Muck
- Roots
- Nova
- Jinx
- Incantation
- Polar
- Erosion

**Comment by Karawasa** [comment]
Doing this means that blacksmith needs to buff the ability damage for these towers. It also means that we need to be sure that the damage over time of the debuffs for roots and erosion stack.

**Comment by Karawasa** [comment]
I think we should also make these lower priority than normal damage towers if possible (I know the HP is the same).

**Comment by MNoya** [comment]
HP isn't taken to target at all at the moment, just dps (Damage/AttacksPerSecond)

This towers still have low priority, as their DPS is way lesser (sometimes 0) than most towers.

**Comment by WindStrike72** [comment]
Hence why there's pretty much no point in having the support label on them. I have had a few cases of Well and Blacksmith prioritizing themselves though over stuff like Roots and Nova, just cause the DPS thingy don't take ability damage into account, so with only Well/Blacksmith/Trickery as support towers, that should fix it.

**Comment by Karawasa** [comment]
Keep support label on arrow/cannon and dual supports because they should never be buffed.

**Comment by MNoya** [comment]
With the last BuffPriority system additions, this should be resolved. We can adjust particular tower priorities now in #57
