### ISSUE TITLE
Crash Error

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#55]
Built an Ephemeral Tower, a little bit later, it crashes. Tried building ephemeral later, no issues. Not sure what happened, but have the vconsole log:

[   AssetSystem            ]: On-demand recompile of asset particles/custom/towers/ephemeral/buff_cascade.vpcf
[   AssetSystem            ]:  -> reason: Invalid Dependency Information
[   AssetSystem            ]: Recompiling resource asset: 'particles/custom/towers/ephemeral/buff_cascade.vpcf'
[   ResourceCompilerSystem ]: - dota_addons\element_td\particles\custom\towers\ephemeral\buff_cascade.vpcf
[   AssetSystem            ]: On-demand recompile of asset particles/custom/towers/ephemeral/buff_blur_cascade.vpcf
[   AssetSystem            ]:  -> reason: Invalid Dependency Information
[   AssetSystem            ]: Recompiling resource asset: 'particles/custom/towers/ephemeral/buff_blur_cascade.vpcf'
[   ResourceCompilerSystem ]: - dota_addons\element_td\particles\custom\towers\ephemeral\buff_blur_cascade.vpcf
[   AssetSystem            ]: On-demand recompile of asset particles/custom/towers/ephemeral/buff_leaves_cascade.vpcf
[   AssetSystem            ]:  -> reason: Invalid Dependency Information
[   AssetSystem            ]: Recompiling resource asset: 'particles/custom/towers/ephemeral/buff_leaves_cascade.vpcf'
[   ResourceCompilerSystem ]: - dota_addons\element_td\particles\custom\towers\ephemeral\buff_leaves_cascade.vpcf
[   AssetSystem            ]: On-demand recompile of asset particles/custom/towers/ephemeral/buff_whirlwind_static_cascade.vpcf
[   AssetSystem            ]:  -> reason: Invalid Dependency Information
[   AssetSystem            ]: Recompiling resource asset: 'particles/custom/towers/ephemeral/buff_whirlwind_static_cascade.vpcf'
[   ResourceCompilerSystem ]: - dota_addons\element_td\particles\custom\towers\ephemeral\buff_whirlwind_static_cascade.vpcf
[   AssetSystem            ]: On-demand recompile of asset particles/custom/towers/ephemeral/buff_magic_trail_cascade.vpcf
[   AssetSystem            ]:  -> reason: Invalid Dependency Information
[   AssetSystem            ]: Recompiling resource asset: 'particles/custom/towers/ephemeral/buff_magic_trail_cascade.vpcf'
[   ResourceCompilerSystem ]: - dota_addons\element_td\particles\custom\towers\ephemeral\buff_magic_trail_cascade.vpcf
[   AssetSystem            ]: On-demand recompile of asset particles/custom/towers/ephemeral/buff_trail_d_cascade.vpcf
[   AssetSystem            ]:  -> reason: Invalid Dependency Information
[   AssetSystem            ]: Recompiling resource asset: 'particles/custom/towers/ephemeral/buff_trail_d_cascade.vpcf'
[   ResourceCompilerSystem ]: - dota_addons\element_td\particles\custom\towers\ephemeral\buff_trail_d_cascade.vpcf
[   AssetSystem            ]: On-demand recompile of asset particles/custom/towers/ephemeral/buff_burst_cascade.vpcf
[   AssetSystem            ]:  -> reason: Invalid Dependency Information
[   AssetSystem            ]: Recompiling resource asset: 'particles/custom/towers/ephemeral/buff_burst_cascade.vpcf'
[   ResourceCompilerSystem ]: - dota_addons\element_td\particles\custom\towers\ephemeral\buff_burst_cascade.vpcf
[   AssetSystem            ]: On-demand recompile of asset particles/custom/towers/ephemeral/buff_afterimage_cascade.vpcf
[   AssetSystem            ]:  -> reason: Invalid Dependency Information
[   AssetSystem            ]: Recompiling resource asset: 'particles/custom/towers/ephemeral/buff_afterimage_cascade.vpcf'
[   ResourceCompilerSystem ]: - dota_addons\element_td\particles\custom\towers\ephemeral\buff_afterimage_cascade.vpcf
[   AssetSystem            ]: On-demand recompile of asset particles/custom/towers/ephemeral/buff_fire_cascade.vpcf
[   AssetSystem            ]:  -> reason: Invalid Dependency Information
[   AssetSystem            ]: Recompiling resource asset: 'particles/custom/towers/ephemeral/buff_fire_cascade.vpcf'
[   ResourceCompilerSystem ]: - dota_addons\element_td\particles\custom\towers\ephemeral\buff_fire_cascade.vpcf
[   AssetSystem            ]: On-demand recompile of asset particles/custom/towers/ephemeral/buff_start_cascade.vpcf
[   AssetSystem            ]:  -> reason: Invalid Dependency Information
[   AssetSystem            ]: Recompiling resource asset: 'particles/custom/towers/ephemeral/buff_start_cascade.vpcf'
[   ResourceCompilerSystem ]: - dota_addons\element_td\particles\custom\towers\ephemeral\buff_start_cascade.vpcf
[   AssetSystem            ]: On-demand recompile of asset particles/custom/towers/ephemeral/windrunner_feet_effects_cascade.vpcf
[   AssetSystem            ]:  -> reason: Invalid Dependency Information
[   AssetSystem            ]: Recompiling resource asset: 'particles/custom/towers/ephemeral/windrunner_feet_effects_cascade.vpcf'
[   ResourceCompilerSystem ]: - dota_addons\element_td\particles\custom\towers\ephemeral\windrunner_feet_effects_cascade.vpcf
[   AssetSystem            ]: On-demand recompile of asset particles/custom/towers/ephemeral/windrunner_feet_effects_cascade_b.vpcf
[   AssetSystem            ]:  -> reason: Invalid Dependency Information
[   AssetSystem            ]: Recompiling resource asset: 'particles/custom/towers/ephemeral/windrunner_feet_effects_cascade_b.vpcf'
[   ResourceCompilerSystem ]: - dota_addons\element_td\particles\custom\towers\ephemeral\windrunner_feet_effects_cascade_b.vpcf
[   AssetSystem            ]: On-demand recompile of asset particles/custom/towers/ephemeral/windrunner_feet_effects_cascade_c.vpcf
[   AssetSystem            ]:  -> reason: Invalid Dependency Information
[   AssetSystem            ]: Recompiling resource asset: 'particles/custom/towers/ephemeral/windrunner_feet_effects_cascade_c.vpcf'
[   ResourceCompilerSystem ]: - dota_addons\element_td\particles\custom\towers\ephemeral\windrunner_feet_effects_cascade_c.vpcf
[   AssetSystem            ]: On-demand recompile of asset particles/custom/towers/ephemeral/buff_leaves_sides_cascade.vpcf
[   AssetSystem            ]:  -> reason: Invalid Dependency Information
[   AssetSystem            ]: Recompiling resource asset: 'particles/custom/towers/ephemeral/buff_leaves_sides_cascade.vpcf'
[   ResourceCompilerSystem ]: - dota_addons\element_td\particles\custom\towers\ephemeral\buff_leaves_sides_cascade.vpcf
[   AssetSystem            ]: On-demand recompile of asset particles/custom/towers/ephemeral/buff_debris_sides_cascade.vpcf
[   AssetSystem            ]:  -> reason: Invalid Dependency Information
[   AssetSystem            ]: Recompiling resource asset: 'particles/custom/towers/ephemeral/buff_debris_sides_cascade.vpcf'
[   ResourceCompilerSystem ]: - dota_addons\element_td\particles\custom\towers\ephemeral\buff_debris_sides_cascade.vpcf
[   AssetSystem            ]: On-demand recompile of asset particles/custom/towers/ephemeral/buff_leaves_swirl_cascade.vpcf
[   AssetSystem            ]:  -> reason: Invalid Dependency Information
[   AssetSystem            ]: Recompiling resource asset: 'particles/custom/towers/ephemeral/buff_leaves_swirl_cascade.vpcf'
[   ResourceCompilerSystem ]: - dota_addons\element_td\particles\custom\towers\ephemeral\buff_leaves_swirl_cascade.vpcf
[   AssetSystem            ]: On-demand recompile of asset particles/custom/towers/ephemeral/buff_debris_swirl_cascade.vpcf
[   AssetSystem            ]:  -> reason: Invalid Dependency Information
[   AssetSystem            ]: Recompiling resource asset: 'particles/custom/towers/ephemeral/buff_debris_swirl_cascade.vpcf'
[   ResourceCompilerSystem ]: - dota_addons\element_td\particles\custom\towers\ephemeral\buff_debris_swirl_cascade.vpcf
[   AssetSystem            ]: On-demand recompile of asset particles/custom/towers/ephemeral/buff_swirl_leaves_cascade.vpcf
[   AssetSystem            ]:  -> reason: Invalid Dependency Information
[   AssetSystem            ]: Recompiling resource asset: 'particles/custom/towers/ephemeral/buff_swirl_leaves_cascade.vpcf'
[   ResourceCompilerSystem ]: - dota_addons\element_td\particles\custom\towers\ephemeral\buff_swirl_leaves_cascade.vpcf
[   AssetSystem            ]: On-demand recompile of asset particles/custom/towers/ephemeral/buff_magic_cascade.vpcf
[   AssetSystem            ]:  -> reason: Invalid Dependency Information
[   AssetSystem            ]: Recompiling resource asset: 'particles/custom/towers/ephemeral/buff_magic_cascade.vpcf'
[   ResourceCompilerSystem ]: - dota_addons\element_td\particles\custom\towers\ephemeral\buff_magic_cascade.vpcf
[   AssetSystem            ]: On-demand recompile of asset particles/custom/towers/ephemeral/buff_leaves_sides_b_cascade.vpcf
[   AssetSystem            ]:  -> reason: Invalid Dependency Information
[   AssetSystem            ]: Recompiling resource asset: 'particles/custom/towers/ephemeral/buff_leaves_sides_b_cascade.vpcf'
[   ResourceCompilerSystem ]: - dota_addons\element_td\particles\custom\towers\ephemeral\buff_leaves_sides_b_cascade.vpcf
[   AssetSystem            ]: On-demand recompile of asset particles/custom/towers/ephemeral/buff_debris_sides_b_cascade.vpcf
[   AssetSystem            ]:  -> reason: Invalid Dependency Information
[   AssetSystem            ]: Recompiling resource asset: 'particles/custom/towers/ephemeral/buff_debris_sides_b_cascade.vpcf'
[   ResourceCompilerSystem ]: - dota_addons\element_td\particles\custom\towers\ephemeral\buff_debris_sides_b_cascade.vpcf
[   AssetSystem            ]: Reloading Resource [1/21]: particles/custom/towers/ephemeral/buff_afterimage_cascade.vpcf
[   AssetSystem            ]: Reloading Resource [2/21]: particles/custom/towers/ephemeral/buff_blur_cascade.vpcf
[   AssetSystem            ]: Reloading Resource [3/21]: particles/custom/towers/ephemeral/buff_burst_cascade.vpcf
[   AssetSystem            ]: Reloading Resource [4/21]: particles/custom/towers/ephemeral/buff_cascade.vpcf
[   AssetSystem            ]: Reloading Resource [5/21]: particles/custom/towers/ephemeral/buff_debris_sides_b_cascade.vpcf
[   AssetSystem            ]: Reloading Resource [6/21]: particles/custom/towers/ephemeral/buff_debris_sides_cascade.vpcf
[   AssetSystem            ]: Reloading Resource [7/21]: particles/custom/towers/ephemeral/buff_debris_swirl_cascade.vpcf
[   AssetSystem            ]: Reloading Resource [8/21]: particles/custom/towers/ephemeral/buff_fire_cascade.vpcf
[   AssetSystem            ]: Reloading Resource [9/21]: particles/custom/towers/ephemeral/buff_leaves_cascade.vpcf
[   AssetSystem            ]: Reloading Resource [10/21]: particles/custom/towers/ephemeral/buff_leaves_sides_b_cascade.vpcf
[   AssetSystem            ]: Reloading Resource [11/21]: particles/custom/towers/ephemeral/buff_leaves_sides_cascade.vpcf
[   AssetSystem            ]: Reloading Resource [12/21]: particles/custom/towers/ephemeral/buff_leaves_swirl_cascade.vpcf
[   AssetSystem            ]: Reloading Resource [13/21]: particles/custom/towers/ephemeral/buff_magic_cascade.vpcf
[   AssetSystem            ]: Reloading Resource [14/21]: particles/custom/towers/ephemeral/buff_magic_trail_cascade.vpcf
[   AssetSystem            ]: Reloading Resource [15/21]: particles/custom/towers/ephemeral/buff_start_cascade.vpcf
[   AssetSystem            ]: Reloading Resource [16/21]: particles/custom/towers/ephemeral/buff_swirl_leaves_cascade.vpcf
[   AssetSystem            ]: Reloading Resource [17/21]: particles/custom/towers/ephemeral/buff_trail_d_cascade.vpcf
[   AssetSystem            ]: Reloading Resource [18/21]: particles/custom/towers/ephemeral/buff_whirlwind_static_cascade.vpcf
[   AssetSystem            ]: Reloading Resource [19/21]: particles/custom/towers/ephemeral/windrunner_feet_effects_cascade.vpcf
[   AssetSystem            ]: Reloading Resource [20/21]: particles/custom/towers/ephemeral/windrunner_feet_effects_cascade_b.vpcf
[   AssetSystem            ]: Reloading Resource [21/21]: particles/custom/towers/ephemeral/windrunner_feet_effects_cascade_c.vpcf
[                          ]: Disconnected From 'Localhost:29000'
[                          ]: Connecting To 'Localhost:29000'
[                          ]: Connected To 'Localhost:29000'

On a random note, I have yet to experience a crash when I play from normal dota; loading from dota tools, on the other hand, this isn't the first time.

**Comment by ynohtna92** [comment]
AssetSystem crashes are normally a client issue. Verify your game cache and it should replace the missing/corrupt game files. By going to Dota 2 - Properties in steam (right click on dota 2) -> Local Files (tab) -> Verify Integrity of game cache.

These logs are not helpful if it is a Crash to desktop type of crash. We need the crash dump file found in the Steam directory under dumps. You should then see crash_dota2.exe_XXXXXXXXXXX_1.DMP which you can upload here for review.

**Comment by MNoya** [comment]
Yeah this type of crash is common but it wont ever be a problem in the main game (only inside tools). Basically the game is trying to use a particle that isn't compiled, so it tries to compile it (generating the _c version) but causes a crash in the middle.
