### ISSUE TITLE
Tower Buffing Priority List

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#57]
With regards to Blacksmith/Well/Trickery towers, this should be the order of how they get buffed, going top to bottom. It's a bit of a lengthy list...
1. Pure & Periodic
2. Level 3 Duals
3. Level 2 Triples
4. Level 2 Support Triples
5. Level 3 Singles (Refined)
6. Level 2 Duals
7. Level 1 Triples
8. Level 1 Support Triples
9. Level 2 Singles (Focused)
10. Level 1 Duals
11. Level 1 Singles

**Comment by MNoya** [comment]
What happens between 2 Pures of different type? Choose by DPS ?

**Comment by WindStrike72** [comment]
Yeah, that should be fine. That or randomize. At that point it shouldn't matter too much. The idea with the tower tiers is everything in that tier should have an equal impact with the right builds, so prioritizing one over another within each tier is, well... impossible to determine.

**Comment by Karawasa** [comment]
Randomize in case of tie breaker. Also, remove support duals (5, 10, 13) and cannon/arrow (15) completely. They should never be buffed.

**Comment by WindStrike72** [comment]
What about manual buffing? Or nuke that existence entirely?

**Comment by Karawasa** [comment]
Hmm manual buffing sure. If you want to really buff the wrong tower...go ahead!
