### ISSUE TITLE
Rotating towers 

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#6]
http://www.gfycat.com/LividJadedHackee
vs
http://www.gfycat.com/SafeNervousCrownofthornsstarfish

I'm considering making a "ShouldRotate" KV on the units that decides whether to apply the "MODIFIER_PROPERTY_DISABLE_TURNING" or not.

Also people have suggested that we break the models, leave the pedestal static but rotate the shaft of the tower.

**Comment by Karawasa** [comment]
Rotation looks better!

**Comment by ynohtna92** [comment]
I think it looks weird, structural towers shouldn't rotate, only unit towers.

**Comment by MNoya** [comment]
If we split the "base" from the top we could get the best of 2 worlds I think

**Comment by MNoya** [comment]
http://www.gfycat.com/CourageousHairyDipper

Need a better system to place the pedestals with scale/particling

**Comment by ynohtna92** [comment]
It looks much better.

**Comment by Karawasa** [comment]
Nice!! Just repeat for Arrow and we should be good. Elemental towers will use a hero model.

**Comment by MNoya** [comment]
Finished, it is now a system with `"PedestalModel"` and optional `"PedestalModelScale"` and `"PedestalOffset"` to place it on a higher height.

Arrow and Cannon: http://www.gfycat.com/RepulsiveGraveIndianpangolin
Elemental Towers: http://www.gfycat.com/FewBriefBoa
