### ISSUE TITLE
New Relative Bounty Bonuses for Voting UI

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#65]
Now that I got Express Mode bounty hammered out, here's the new bounty bonuses that should display in the Voting UI, depending on settings. All of these are relative to **Classic, Normal** mode.

**Classic:**
- Normal, +0%
- Hard, +14%
- Very Hard, +31%
- Insane, +50%

**Express:**
- Normal, +25%
- Hard, +39%
- Very Hard, +56%
- Insane, +74%

**Comment by MNoya** [comment]
1. Should I format it as "131%" now?
2. Can we round up to 5-0 values?
3. Are those values theoretical (i.e. 1.2 gold \* 30 = 36 gold instead of 30 because of rounding)?

**Comment by Karawasa** [comment]
1. Whatever we do for HP we should do for bounty...to ensure consistency. I think 131% looks fine.
2. Sure. So in order...+15, +30, +50 and +25, +40, +55, + 75.
3. These values (I assume) are based on total bounty over the course of the game. So it's the end result of the different bases.
