### ISSUE TITLE
Endgame Scoreboard missing some things

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#74]
See here:
http://steamcommunity.com/profiles/76561197995227322/screenshot/307738199212322980
- [x] Always shows a Networth of 0, probably because it nukes all of your towers before displaying the score. Thinkin' it should probably record the score prior to all the towers being nuked.
- [x] Showing Lives on the end-game scoreboard is pointless, that category should be axed.
- [x] It always shows Wave 0.
- [x] And due to the tower nuke, it also only shows 0 Towers.
- [x] Difficulty is always a dash '-'
- [x] Annnd could it also show how many Icefrog kills you got?

**Comment by MNoya** [comment]
![img](http://puu.sh/n3AhG/9feadc631f.jpg)

![img](http://puu.sh/n3Bjg/f6aaaeba7a.jpg)

Totally not cheated scores Kappa

**Comment by ynohtna92** [comment]
Do we really need networth on the normal scoreboard? It is redundant as everyone should have a similar networth anyway as waves are defeated.

**Comment by MNoya** [comment]
It is a bit redundant, but selling, random and interest can make networths different.
