### ISSUE TITLE
Creep HP Scaling

### ISSUE THREAD

**Issue by Karawasa** [Karawasa/Element-TD#78]
We are going with a constant HP multiplier for creep waves. So;

**Classic**
Base HP (wave 1) = 34
Multiplier = 1.1785
Final HP (wave 55) = 241700

**Express**
Base HP (wave 1) = 78
Multiplier = 1.315
Final HP (wave 30) = 219251

**Comment by Karawasa** [comment]
I recommend setting HP via formula so that any future balance change will be easy.

**Comment by MNoya** [comment]
Yeah the Health/HealthExpress values on https://github.com/Karawasa/Element-TD/blob/master/game/dota_addons/element_td/scripts/kv/waves.kv should be removed
