### ISSUE TITLE
Tiny looks too close to light

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#79]
After seeing the awesome purple Shadow Fiend, I noticed Tiny (Earth Elemental) looks kind of bright and rather close to Keeper of the Light in color (Light Elemental). Could Tiny's color be altered to be a more golden/earthly color?

**Comment by MNoya** [comment]
Tiny looks super rocky tho, I could try recoloring a bit darker/brown [similar to this set](http://dota2.gamepedia.com/The_Igneous_Stone)
I'll give it a try, but I'm not positive it would look good

**Comment by WindStrike72** [comment]
It's not too big a deal, just a  little something I noticed.

**Comment by MNoya** [comment]
![img](http://puu.sh/n57lw/20580fc197.jpg)

Doesn't look as good, its mask has too many light/specular property and I don't know how to change that. Plus it doesn't match the rocky pedestal, gonna give up on this one

**Comment by WindStrike72** [comment]
Alrighty, no problemo. Thanks for tryin'!
