### ISSUE TITLE
Element Panel rework

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#8]
The [current element panel](http://puu.sh/lOinX/fad9c122fb.jpg) isn't the greatest although it serves its purpose.

Should we improve it, if so, how?

**Comment by Karawasa** [comment]
We could get rid of it altogether. I think with the rune circle and element trophy area...we don't need a UI element to list the number of elements you have. As for lumber, that is a resource. Let's find a place to put all three resources together (maybe around the leaderboard).

FYI...Lumber = Mana now.

**Comment by MNoya** [comment]
One quick idea I had: [Use the element icons](http://puu.sh/lOiyV/c3e5de7bd6.jpg), desaturate or low brightness [when the element level is 0](http://puu.sh/lOiKX/f2a064d2f7.jpg), some number indicating the level, and we could probably have the shortcut button to click on the icons to spawn the elemental as long as there's enough resource.

Or yeah we can get rid of it :smile:

**Comment by ynohtna92** [comment]
I think we still should have a ui element for it so we don't have to mentally keep track if the user has their camera elsewhere.

**Comment by vladmarica** [comment]
Element icons should also be redone. Water and nature and fire are done by three different artists, dark is recolored fire, and light is recolored Wex.

**Comment by vladmarica** [comment]
For the lumber UI, how about something like what DotaCraft does? 

![](http://i.imgur.com/vA2Qwet.png)

**Comment by MNoya** [comment]
Well @Karawasa wanted to move towards Mana, I think Lumber is legit but whatever sounds/looks best. We could keep building onto the dota UI or [take a page from the SC2 board](http://forums.eletd.com/uploads/monthly_05_2014/post-2-0-65831100-1401272726.jpg) and put the resources near the wave indicator

**Comment by ynohtna92** [comment]
I think @Karawasa meant that Lumber <--- Mana not the other way round.

And we need to also display pure essences some where

**Comment by Karawasa** [comment]
Mana makes more sense to summon elements with. So I do mean Lumber --> Mana.

**Comment by ynohtna92** [comment]
It now looks like this. Can this issue be closed?
![image](https://cloud.githubusercontent.com/assets/2245318/11771090/b2d3b81e-a25f-11e5-89a3-3f89b5896e31.png)
http://snag.gy/gIV89.jpg

**Comment by MNoya** [comment]
Did the mango look any good? I'll toy with the PNG for essence later, apart from that it's excellent, closing.

**Comment by ynohtna92** [comment]
Didn't even try it haha.

Also 5x4 and 4x3 ratios look like this 
![image](https://cloud.githubusercontent.com/assets/2245318/11771693/09182a40-a268-11e5-9726-aa1cd3c24ba2.png)
