### ISSUE TITLE
Icefrog kills do not reward points

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#82]
Actually, I'm not even sure what the point system for them is. Clearing the waves didn't reward points either.

**Comment by WindStrike72** [comment]
Oh, that explains it. The doc doesn't have anything on their scoring. Rather than have this one be wave-based, since it keeps track of the kills, it should be per-kill based. Here's what I'm thinking for it:
- Initially, each creep is worth 100 points \* Difficulty Modifier, netting a total of 3000 points \* DM.
- Each wave, the amount of points each one is worth goes up by 10% of the previous wave. So Wave 1 , 100 points \* DM | Wave 2, 110 points \* DM | Wave 3, 121 points \* DM, etc.

Thoughts?

EDIT: Err, not Difficulty Modifier, total Score Modifier.

**Comment by Karawasa** [comment]
Boss actually is in the document;

Boss Bonus is equal to 1.05 score multiplier. Boss Bonus Streak gives an additional 0.01 score multiplier per combo in streak. Combo being defined as successive waves cleared.

**Comment by MNoya** [comment]
I'm not sure I understand how it is supposed to add up. The way I see it now is: lets say you end game game with 100k score. We'll show "Game Cleared! ...", then Boss wave 1, if you clear it, you get "Boss Wave 1 Cleared! Boss Bonus +X%" and so on, all the boss bonus does is just multiply your total score by some value. Is that correct?

What about Kill based score? Boss waves are kinda hard to beat past a few

**Comment by Karawasa** [comment]
Yes, you are correct. We can have a kill based score too if we want (like we do for normal creeps). I'll let @WindStrike72 determine that value. But for the bonus multiplier, the values above are too low.

Let's do 1.10 score multiplier with 0.05 combo bonus. So if you clear 3 waves of frogs you get 20% higher total score.

**Comment by WindStrike72** [comment]
Wait, are we doing both? So "20% higher total score" or "20% more icefrog score"?

**Comment by Karawasa** [comment]
The percentage increase is on total score. If we want a flat amount of points per kill (in addition), that is fine as well.

**Comment by WindStrike72** [comment]
So nutshell:
- Gain (100 \* Score Multiplier) points per Icefrog kill.
- For each wave you clear, you gain a **Total Score Modifier** of +5%, stacking additively.
- Then, once defeated, your total score is multiplied by your **Total Score Modifier**.

Yes?

EDIT: Accounted for 5 per.

**Comment by Karawasa** [comment]
The total score modifier is 10% + 5% for each additional wave cleared. Additive. So if you clear two frog waves, you get a 15% increase in total score. Three frog waves would be 20%.

I think in doing that we should probably nerf points per kill to 50 \* Difficulty Multiplier.

**Comment by WindStrike72** [comment]
Well, in Very Hard, my end score usually gets to about 100k. So with 100 \* Difficulty Multiplier, that's 300 \* 30 = 9,000 points per wave. That seems pretty fair.

**Comment by Karawasa** [comment]
In that example, say you clear two waves. You'll get 18,000 points. Then add 15% brings you to ~136,000 points. So two waves of frogs gets you 36,000 points. That's a big increase!

**Comment by WindStrike72** [comment]
It's a testament of the strength of your defense. Weaker defenses won't get much of an increase. Powerful decreases will get a large increase. If it's too weak, then spawn-camper builds will automatically win by default, there's no point in going any other strategy.

**Comment by Karawasa** [comment]
Alright we compromise at keeping kill points the same (100 base) but nerfing the total score modifier. For that we'll do 5% total score increase (additive) per wave cleared. You complete three frog waves, you get 15% increase in total score of the game.
