### ISSUE TITLE
Icefrog HP Scaling

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#83]
New HP Scaling:
- First wave should just be a continuation off the base hp scaling. So \* 1.1785 of Wave 55.
- Each successive wave should be 20% stronger than the previous, so \* 1.2 of the previous wave.

**Comment by Karawasa** [comment]
Eh in that case let's just do a flat 1.2 modifier. So the first frog wave is 1.2 more than wave 55. Then each successive is 1.2 like you said.
