### ISSUE TITLE
Flooding Tower hover UI weirdness

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#84]
On the damage hover UI, the AoE displayed is:
- 400(Full)/NaN(Half)

Not sure what that stands for, but I'm going to guess it's a euphemism.

**Comment by Karawasa** [comment]
It stands for not a number...in this case probably because it is undefined.

**Comment by MNoya** [comment]
Yeah that key should be removed, Flooding shouldn't have an AOE, as its part of the internal ability, not on the autoattack.
