### ISSUE TITLE
Enchantment Tower Alteration

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#85]
In order to make Enchantment more distinct and add synergy to single-target stuffs (or just non-slows period), here's an alteration to its ability:

Amplifies damage done to the target by 5% / 15%.
If there's only up to 2 more creeps nearby within 150 AoE of the target, the damage amp is cranked up to 15% / 45%.

Still targets 1 creep at a target, 1 sec cooldown, 15 second duration.

**Comment by MNoya** [comment]
Isn't 150 AoE the standard distance for "one behind, one in front" creeps? 200 AoE towers don't get to hit 5 creeps in a non-swarm/undead wave

**Comment by WindStrike72** [comment]
Yep, that's the idea. Tis might be a little tricky to balance.

**Comment by WindStrike72** [comment]
Okay, I got an update to this idea. By default, it causes 15% / 45% damage amp to the creep. For each creep around it in a 150 AoE, it reduces by 3% / 9%, down to minimum of 6% / 18%. So for default waves w/ no slowing, it'll be a 9% / 27%, but as creeps are taken out, it'll increase towards the maximum. However, with slows, or on undead/swarm waves, it'll decrease towards the minimum.

**Comment by MNoya** [comment]
That sounds complex to put in words and mechanically :/

How about we just make it amplify longer? How much does it take for non-fast creeps to do a full trajectory? Does it take more than 1 of the amp towers to debuff a whole wave? We could have Erosion deal more damage (with its DoT) and Enchantment just last longer. Hell, even "X% chance to crit for Y% damage" would be a more straightforward way to do an amplification

**Comment by Karawasa** [comment]
I agree with @MNoya that your second idea is too complicated. Let's keep it the way we first proposed;

Debuff increases damage taken by 5%/15%. If there are 2 or less creeps within 150 range, then damage taken is increased by 15%/45%.

**Comment by MNoya** [comment]
Should the damage increase be decided on application of the debuff, or at every time the creep takes damage?

**Comment by Karawasa** [comment]
On application.

**Comment by Karawasa** [comment]
Every time the creep takes damage.

**Comment by MNoya** [comment]
Just to be sure, amplification stacks additively, right? 45 & 15 = 60% damage (*1.6) on top of everything else

**Comment by Karawasa** [comment]
Yes. But different levels of the same tower do not stack. So 45 + 15 would not be possible. 45 + 10 (erosion) is however.
