### ISSUE TITLE
Sounds stuff

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#88]
Didn't hear sounds for:
- [x] Jinx
- [x]  Obliteration
- [x]  Muck

Sounds were too quiet for:
- [x]  Cannon

Sounds that didn't fit for:
- [x]  Haste (try stacking it for the lulz and notice your ears bleeding)
- [x]  Flame, well I suppose it kinda fits, but it's a little loud

Regarding sounds in general, just scrolling a little bit away from a tower seems to kill the sound completely
- [x]  Increase the break distance to 2000

Also, is there a way to include this for the standard gold sound? It kinda overpowers everything, every time you kill a creep and get gold, and it doesn't seem to have a break distance.
- [x] Gold break with distance

**Comment by Karawasa** [comment]
If the break distance has a gradual decrease in volume until it's reached...then 2000 seems perfect.
