### ISSUE TITLE
Fog blocks things badly

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#89]
When scrolling out too far, the fog of war blocks things really badly. I know it's supposed to, but it's not a gradual thing, it's like part of your screen is just getting blocked in a bad looking way.

**Comment by MNoya** [comment]
How far did you scroll? We made sure the fog distance was like 10k so it could go up to a good height of the whole zone: 

![img](http://puu.sh/n5743/2b788798c7.jpg)

It is possible to [disable fog completely](http://puu.sh/n2nd5/efe35cf358.jpg) but having some fog adds a bit more depth to the terrain.

**Comment by WindStrike72** [comment]
Barely any, and then I got blank sheeted at the top. This was latest official release.

http://steamcommunity.com/sharedfiles/filedetails/?id=622201680
http://steamcommunity.com/sharedfiles/filedetails/?id=622201833

However, I just checked the latest tools build, and it works fine there, so I guess it's fixed.

**Comment by MNoya** [comment]
Oh yeah that was caused by lack of 'r_farz' which determines how much can you look up in distance. Should be good now then
