### ISSUE TITLE
Fast Creeps

### ISSUE THREAD

**Issue by Karawasa** [Karawasa/Element-TD#92]
These creeps go to "max" speed upon activating. That's 522. Their base is 300. So let's make it double speed. Thus, upon activating they get 600 base speed.

More importantly, the timing of the activations causes them to clump. The game document is ambiguous in this regards. What is actually meant is that each creep bursts in consistent intervals...but timer is unique to each creep.

What you should notice after changing this is that at certain locations in the path, a creep will always burst. That's because the timer starts upon spawn so the activation happens at the same location (unless there is slowing).

**Comment by ynohtna92** [comment]
522 is as fast dota will allow any unit to go by default without lifting the speed limit with a modifier. We should add this. How soon after spawn do you want the speed to activate?

**Comment by Karawasa** [comment]
3 seconds. Then it activates every 3 seconds after that.
