### ISSUE TITLE
Ultra Widescreen UI

### ISSUE THREAD

**Issue by Karawasa** [Karawasa/Element-TD#94]
The bottom right resource area is messed up again. See pic.

![screen](https://cloud.githubusercontent.com/assets/7691068/12999479/4d7fdee0-d115-11e5-923a-dce0eb6c271c.png)

**Comment by ynohtna92** [comment]
Noya didn't add any 21:9 stuff to his ui's. Will also have to check everything in 16:10, 16:9, and 4:3 as well.

**Comment by Karawasa** [comment]
So we getting this fixed right?

**Comment by ynohtna92** [comment]
Yeah I'll do it now
