### ISSUE TITLE
Add active casts to Tidal and Ephemeral

### ISSUE THREAD

**Issue by MNoya** [Karawasa/Element-TD#98]
This towers should have an ability that can be cast to reset them. What should the cooldown of this abilities be?
- Ephemeral resets 3 seconds after reaching minimum damage or after 2 seconds of not attacking
- Tidal resets after 1 second of not attacking

I am actually not sure how useful is having the cast if its gonna be reset every second or so.

**Comment by WindStrike72** [comment]
For Ephemeral, 3 seconds. For Tidal, 2 seconds. Likewise, Tidal's passive cooldown should go up to 2 seconds as well.

**Comment by MNoya** [comment]
So we aren't doing this at the end, decided against it because the ability wouldn't be of much use.
